Faster and clearer wiggle plot
gazprom-neft/SeismicPro pull request #100
Opened 2022-06-30 17:00 UTC by nikita-klsh

2022-07-01 11:09 UTC, alexanderkuvaev requested changes

2022-07-01 11:09 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +        ax.plot(amps.ravel(), np.tile(range(amps.shape[1]), amps.shape[0]), color=color, lw=lw, **kwargs)
```suggestion
        ax.plot(amps.ravel(), np.broadcast_to(np.arange(amps.shape[1]), amps.shape).ravel(), color=color, lw=lw, **kwargs)
```
Avoids mixing numpy and pure python, avoids excessive copying

2022-07-01 11:09 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +        ix_start = [0, *shifted_boarders + 3]
You use lots of array unpacking here, which is expensive, almost everything here can be performed in numpy without casts to python types

2022-07-01 11:09 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +        boarders = np.argwhere(np.diff(xy[:, 1]) != 1).flatten()
```suggestion
        boarders = np.argwhere((np.diff(xy[:, 0]) == 1) & (np.diff(xy[:, 1]) != 1)).ravel()
```
1. Check for the trace id as well, you check may fail in strange rare cases
2. Switch to `ravel` to avoid copying

2022-07-01 11:30 UTC, a-arefina reviewed
Good work!

Please add some benchmarks showing increase in performance

Please recalculate the notebooks that use this method

2022-07-01 11:30 UTC, a-arefina commented on seismicpro/src/gather/gather.py
> +        positive_amps = amps[tuple(xy.T)]
same result can be obtained by `amps[np.nonzero(traces > 0)]`

2022-07-01 11:30 UTC, a-arefina commented on seismicpro/src/gather/gather.py
> +        FINE_ALPHA_MIN = 0.25 # value from [0, 1]
Please describe the meanind of these constants in comments

2022-07-01 11:30 UTC, a-arefina commented on seismicpro/src/gather/gather.py
> +    #pylint: disable=invalid-name
This is due to `xy` and `lw` ?
Please rename `lw` to `line_width` 
`xy` can be renamed to `positive_coords`, or even split into 2 variables: `x_pos`, `y_pos`

then, remove this ignore

2022-07-01 11:30 UTC, a-arefina commented on seismicpro/src/gather/gather.py
> +        xy = np.argwhere(traces > 0)
consider `x_pos, y_pos = np.nonzero(traces > 0)`

2022-07-01 11:30 UTC, a-arefina commented on seismicpro/src/gather/gather.py
> +        alpha, lw = [FINE_RATIO * (axes_width_inches / len(traces)) if val is None else val for val in [alpha, lw]]
transparancy and line width are measured in different units, so it is rather surprising to have equal default values for them.

please add some comment on this

2022-07-04 11:45 UTC, nikita-klsh commented on seismicpro/src/gather/gather.py
> +        FINE_ALPHA_MIN = 0.25 # value from [0, 1]
Add comments

2022-07-04 11:45 UTC, nikita-klsh commented on seismicpro/src/gather/gather.py
> +    #pylint: disable=invalid-name
This is due to the capital variables

2022-07-04 11:57 UTC, nikita-klsh commented on seismicpro/src/gather/gather.py
> +        xy = np.argwhere(traces > 0)
Either your suggestion or my version simplifies one pieces and complicates another.
I find it more readable having one 2d array `xy` and slicing its columns e.g. `xy[:, 1]`, rather than having two 1d arrays and stacking them, e.g. `np.column_stack([x_pos, y_pos])` (4 times)

2022-07-04 12:25 UTC, nikita-klsh commented on seismicpro/src/gather/gather.py
> +        alpha, lw = [FINE_RATIO * (axes_width_inches / len(traces)) if val is None else val for val in [alpha, lw]]
Add comment

2022-07-04 14:50 UTC, alexanderkuvaev approved these changes

2022-07-04 15:30 UTC, anton-br approved these changes

2022-07-04 15:53 UTC, merged