Add standard zero centred normalization for SGDRegressor
gazprom-neft/SeismicPro pull request #102
Opened 2022-07-12 12:23 UTC by bestetc

Fixed some rare cases where `calc_init_by_layers` would return an incorrect evaluation for `init`. @nikita-klsh suggested using the zero-centered normalization after splitting data into layers instead of using normalization to [0, 1] interval before splitting the data.

We did a the small reasearch how different types of normalization and hyperparameters for SGDRegressor affect the calculation of "initialization", and chose the best of the stable options.

This pull reqest
* fix the bad cases
![bad_fit](https://user-images.githubusercontent.com/53880304/178486088-3b6210de-50ea-4a43-a425-6cd8e2fe2e7e.png)

* good cases still good cases
![same_fit](https://user-images.githubusercontent.com/53880304/178486117-7fab1d8c-aace-4317-b97b-d61089ccac30.png)

* makes RefractorVelocity fit a little bit faster
![timing](https://user-images.githubusercontent.com/53880304/178486133-f70143dc-14ec-4f17-94e4-949d1d26f136.png)

2022-07-13 11:56 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +                                                                initial_slope * std_offset / std_time, 0)
Is not it?

```suggestion
                fitted_slope, fitted_time = self._fit_regressor(scaled_offsets.reshape(-1, 1), scaled_times, 1, 0)
```

2022-07-27 09:20 UTC, anton-br reviewed
Overall, do you really need to be able to dump single RV?? Probably you want to dump only RV field? The dump and load you wrote here are easelly expanding for many RV.

2022-07-27 09:20 UTC, anton-br commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +            f.write(values_format.format(*values, col_size=col_size))
```suggestion
            values = list(self.coords.coords) + list(self.params.values())
            values_format = '\n' + '{:>{col_size}}' * len(self.coords) + '{:>{col_size}.2f}' * len(self.params)
            values_format = values_format.format(*values, col_size=col_size)
            
            columns = list(self.coords.names) + list(self.params.keys())
            cols_format = ()'{:>{col_size}}' * (len(columns)).format(*columns, col_size=col_size)
            with open(path, 'w', encoding=encoding) as f:
                f.write(cols_format + values_format)
```

2022-07-27 09:20 UTC, anton-br commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        """Dump RefractorVelocity instance to disk.
```suggestion
        """Save the RefractorVelocity instance to a file.
```

2022-07-27 09:20 UTC, anton-br commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +            path to the file with parameters.
I've stolen this from gather.dump, seems better for me.
Also, make sure that the sentences start with capital letters
```suggestion
            The directory to dump the RefractorVelocity instance in.
```

2022-07-27 09:20 UTC, anton-br commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        col_size = max(col_size, max(len(name) for name in self.coords.names) + 1)
Do you really need to change the size of all columns if the coords.name is longer than col_size? May be change only the coords-related columns, leaving other columns' size to col_size?

2022-07-27 09:20 UTC, anton-br commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        """Load parameters from a file and create a RefractorVelocity instance from the loaded parameters.
simplify the sentence, you have two `parameters` here.
Also, it is not clear what parameters do you load

2022-07-27 10:00 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        return ['t0'] + [f'x{i}' for i in range(1, n_refractors)] + [f'v{i + 1}' for i in range(n_refractors)]
a little bit less symbols.
second will be `[f'v{i}' for i in range(1, n_refractors + 1)]`. It's a little more symbols.

2022-07-28 11:59 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +            path to the file with parameters.
It's full path to a file

2022-08-03 10:17 UTC, alexanderkuvaev requested changes

2022-08-03 10:17 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +                current_slope[i] = current_slope[i] * (n_refractors / (n_refractors + 1)) if i else 4 / 5
But it's initialized empty in the rhs

2022-08-03 10:17 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        init = [current_time[0], *cross_offsets[1:-1], *(velocities * 1000)]
Velocities can be non-increasing here

2022-08-03 10:17 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
>          self._model_params = optimize.minimize(partial_loss_func, x0=self._ms_to_kms(self.init),
`piecewise_times` and `piecewise_offsets` are updated on each optimization step inside `partial_loss_func`, while `_model_params` contains parameters of the best iteration, which can be not the last one. In this case `self.params` and `piecewise_*` become out of sync

2022-08-05 06:38 UTC, dpodvyaznikov commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        data_scaled = (data - mean) / (std + 1e-10)
I'd suggest using `normalization.scale_standard`:

```suggestion
        data_scaled = normalization.scale_standard(data, mean, std, 1e-10)
```

2022-08-05 14:50 UTC, alexanderkuvaev requested changes
1. Remove `_update_piecewise_coords` and `_create_piecewise_coords` completely
2. Make a new **static** method `calc_knots_by_params` that takes **only params** and returns offsets and times of knots of the piecewise-linear velocity function
3. Call it in `loss_piecewise_linear` and in `from_first_breaks` after the fit

2022-08-05 14:50 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +    def _scale_standart(data):
```suggestion
    def _scale_standard(data):
```

2022-08-08 12:03 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        data_scaled = (data - mean) / (std + 1e-10)
Also move normalization from `gather.utils` to `utils`

2022-08-08 12:28 UTC, alexanderkuvaev requested changes

2022-08-08 12:28 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +    def calc_knots_by_params(self, params, n_refractors, max_offset):
I asked you to make it static. You don't need `n_refractors` here, they can be calculated from params

2022-08-08 12:28 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
>          piecewise_times = np.zeros(n_refractors + 1)
Why not `empty`?

2022-08-08 12:28 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
>          self.piecewise_offsets, self.piecewise_times = \
Don't update `self` here

2022-08-08 12:28 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        data_scaled = normalization.scale_standard(data, mean, std, 1e-10)
I'd stick to the previous version, `normalization` module was designed to perform inplace normalization whenever possible. `scale_standard` is the only exception now, but may change in the future.

2022-08-08 12:28 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +                current_slope[i] = current_slope[i - 1] * (n_refractors / (n_refractors + 1)) if i else 4 / 5
Don't get why `current_time` is not updated here. Maybe simply use slope and time from the previous layer?

2022-08-08 12:50 UTC, alexanderkuvaev requested changes

2022-08-08 12:50 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        current_time = np.zeros(n_refractors)
Why do you need an array of current times if you use only the first one?

2022-08-08 12:58 UTC, alexanderkuvaev requested changes
`_empty_layers` is unused now. `_ms_to_kms` uses default value of `to_array` all the time.

2022-08-08 13:03 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +                current_slope[i] = current_slope[i - 1] * (n_refractors / (n_refractors + 1)) if i else 4 / 5
defaults params for t0 is 0, if no data found (or this data could not be normalize) current_time still set to init values. 
init values for time is 0.

2022-08-08 13:03 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        current_time = np.zeros(n_refractors)
change `np.zeros` to `0`.

2022-08-08 14:58 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
>          piecewise_times = np.zeros(n_refractors + 1)
changed to 0

2022-08-08 15:25 UTC, alexanderkuvaev requested changes

2022-08-08 15:25 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        current_time =  max(0, current_time)
Move it in the loop

2022-08-08 15:25 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        current_time = 0
Why `current_`? Its `t0`

2022-08-08 15:25 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +                current_slope[i] = current_slope[i - 1] * (n_refractors / (n_refractors + 1)) if i else 4 / 5
Make this a one-liner before the loop instead of instantiation using `empty`

2022-08-08 15:42 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        current_time = 0
`init_t0` is OK?

2022-08-08 18:17 UTC, alexanderkuvaev requested changes

2022-08-08 18:17 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        """Update the given `offsets` and `times` arrays based on the `params` and `n_refractors`."""
Update docs

2022-08-08 18:17 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
>          """Update the piecewise linear attributes and returns the loss function result.
It only calculates the loss

2022-08-08 18:17 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
>          constraint_velocity = {  # velocities ascend.
Use `append` kwarg in the above line, can't comment on it

2022-08-08 18:17 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +            if std_offset not in [0, np.nan] and std_time not in [0, np.nan]:
```suggestion
            if std_offset and std_time:
```
And return 0 std in `_scale_standard` for empty data

2022-08-08 18:17 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +                current_slope[i] = current_slope[i - 1] * (n_refractors / (n_refractors + 1)) if i else 4 / 5
Still unresolved

2022-08-08 18:17 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +                current_slope[i] = lin_reg.coef_[0] * std_time / std_offset
Call it `slopes`

2022-08-09 09:53 UTC, alexanderkuvaev approved these changes

2022-08-09 09:54 UTC, merged