Refractor field improvements
gazprom-neft/SeismicPro pull request #105
Opened 2022-08-04 11:12 UTC by bestetc

Add next improvements to RefractorVelocityField:

1. Dump and load.
RefractorVelocityField can now be dumped to and loaded from a file.
Also added dump and load methods to the RefractorVelocity class.

2. Calculate from survey.
RefractorVelocityField can now be calculated by `calculate_refractor_velocity_field` method of the Survey class.
Field can be constructed by gathers or supergathers.

3. Plot.
Added plot method to show parameters of items in the RefractorVelocityFieldField (mode="items") and expected values (mode="grid")
Sample plot with grid mode
![download](https://user-images.githubusercontent.com/53880304/182832937-eff587ff-0691-4823-9cec-c4a1f6c642d2.png)

2022-08-04 11:14 UTC, alexanderkuvaev commented
Split this pool request into 3 and compare them not to `master`, but `more_fields` branch

2022-08-05 10:09 UTC, alexanderkuvaev requested changes

2022-08-05 10:09 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +    def load(cls, path, encoding="UTF-8"):
```suggestion
    def from_file(cls, path, encoding="UTF-8"):
```
+ unify params with `__init__`

2022-08-05 10:09 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +            f.write(cols_str + data_str)
1. Write a separate function that dumps a `DataFrame` to a file with a single `to_csv` call,
2. Construct a dataframe in both RV and RVF dumps an call the cuntion defined above.

Current code is extremely complicated and is almost copy-pasted

2022-08-05 10:09 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        self.update(rv_list)
1. Write a separate function that reads all RV instances from a file
2. Call it in both `RV.from_file` and `RVF.from_file` 
3. In case of RV: return the only loaded instance
4. In case of RVF: simply run `cls(items, survey=survey, ...)` without this strange `n_refractors` setting

2022-09-02 12:28 UTC, anton-br requested changes
Overall, docs need a grammar check! I have not tried to rewrite any part of the docs, leave it up to you.

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +         - The second row contains the coords names, coords values, and parameters values of a RefractorVelocity.
If you'll change this part, please unify other docs as well.

```suggestion
        File should have coords and parameters of a single RefractorVelocity with the following structure:
         - The first row contains names of Coordinates parameters (name_x, name_y, coord_x, coord_y) and
        the RefractorVelocity parameters ("t0", "x1"..."x{n-1}", "v1"..."v{n}", "max_offset").
         - The second row contains the coords names, coords values, and parameters values of a RefractorVelocity.
```

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +            path to the file with parameters.
fix it in all docs
```suggestion
        path : str
            Path to the file with parameters.
```

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        """Dump the RefractorVelocity instance to a file. Coords should be preloaded.
Move note about coords to Note section. looks strange here

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +            rv_list.append(rv)
```suggestion
            rv_list.append(RefractorVelocity(max_offset=max_offset, coords=coords, **params))
```

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        Parameters
`is_geographic` is missing

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/utils.py
> +    """Calculate a DataFrame with coordinates and parameter of the passed RefractorVelocity.
```suggestion
    """Calculate a DataFrame with coordinates and parameters of the passed RefractorVelocity.
```

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/utils.py
> +    """Dump list of DataFrame to a file.
```suggestion
    """Dump list of DataFrames to a file.
```

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/utils.py
> +    0   SourceX     SourceY     1111100     2222220     50.00   1000.00   1500.00   2000.00    2000.00
```suggestion
        SourceX     SourceY     1111100     2222220     50.00   1000.00   1500.00   2000.00    2000.00
```

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/utils.py
> +    Each DataFrame in the list should have next structure:
unify this block. You describe file structe at least 5 times and they all differ from each other..

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/utils.py
> +    df_list : iterable of :class:`~pandas.DataFrame`
I suggest passing `df` not only as iterable but as object as well.

Just add `to_list` to first line of this function and change `df_list` name to `df` or `dfs`.  


If not, at least change docs or name of `df_list`, sinceyou have a mismatch of name and docs

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/utils.py
> +        Each DataFrame in the passed list should contain coordinates and parameters of a :class:`~RefractorVelocity`.
```suggestion
        Each DataFrame in the passed list should contains coordinates and parameters of a :class:`~RefractorVelocity`.
```

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/utils.py
> +    None
delete

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/utils.py
> +    encoding : str, optional, defaults to "UTF-8"
you don't have default here

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/utils.py
> +    params_list : list of dict
```suggestion
    params_list : list of dicts
```

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/utils.py
> +            raise ValueError(f"Wrong parameter type in the row {row} to create a correct RefractorVelocity instance.")
```suggestion
            raise ValueError(f"Found wrong parameter type in the row {row}")
```

2022-09-02 12:28 UTC, anton-br commented on seismicpro/src/refractor_velocity/utils.py
> +            raise ValueError(f"Unsufficient parameters in the row {row} to create a correct RefractorVelocity "
anyway, do you really need this check? under what conditions can you get `np.nan`?
Maybe change it to `np.isfinite`?

```suggestion
            raise ValueError(f"Found unsufficient parameters in the row {row}"
```

2022-09-05 10:15 UTC, bestetc commented on seismicpro/src/refractor_velocity/utils.py
> +    0   SourceX     SourceY     1111100     2222220     50.00   1000.00   1500.00   2000.00    2000.00
I added an unnecessary index value to this example to indicate that it should be a DataFrame.
There are no problem to remove it.

2022-09-05 10:57 UTC, bestetc commented on seismicpro/src/refractor_velocity/utils.py
> +    Each DataFrame in the list should have next structure:
2 times for RefractorVelocity, 2 times for RefractorVelocityFiled, once  for DataFrame. They are really a little different.
But I have no idea how to combine all 3 options and I describe them all in detail.

2022-09-07 10:32 UTC, bestetc commented on seismicpro/src/refractor_velocity/utils.py
> +            raise ValueError(f"Unsufficient parameters in the row {row} to create a correct RefractorVelocity "
The last item in a row will `np.nan` if a row has less values than expected.
The number of expected parameters is defined by first row with names of parameters.
If any row contains more values that expected, the pandas backend will raise ParseError.

2022-09-09 10:33 UTC, alexanderkuvaev requested changes

2022-09-09 10:33 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +
Don't forget `encoding`

2022-09-09 10:33 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        min_col_size : int, defaults to 11
Do we actually need this param?

2022-09-09 10:33 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        if self.coords is None:
```suggestion
        if not self.has_coords:
```

2022-09-09 10:33 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +    def from_file(cls, path, is_geographic=None, encoding="UTF-8"):
Add `survey` argument

2022-09-09 10:33 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        File should have coords and parameters of a RefractorVelocity with next structure:
```suggestion
        The file should define near-surface velocity model at one or more field locations and have the following structure:
```

2022-09-09 10:33 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +            CROSSLINE_3D)). Inferred automatically on the first update if not given.
```suggestion
            CROSSLINE_3D)). Inferred from coordinates of the first `RefractorVelocity` in the file if not given.
```

2022-09-09 10:33 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        df_list = [calc_df_to_dump(rv) for rv in self.item_container.values()]
```suggestion
        df_list = [calc_df_to_dump(rv) for rv in self.items]
```

2022-09-09 10:33 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/utils.py
> +def calc_df_to_dump(rv):
I'd change the signature to
```suggestion
def calc_df_to_dump(*refractor_velocities):
```
and construct a single dataframe from all of them at once. This will simplify code a bit an will be a bit more clear

2022-09-09 10:33 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/utils.py
> +            raise ValueError(f"Found wrong parameter type in the row {row}.")
This can be omitted: it will fail either when you create an instance of `Coordinates` or `RefractorVelocity`

2022-09-09 10:33 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/utils.py
> +        max_offset_list.append(row[-1])
Instead 3 lists create a single list of tuples with the following structure: (`coords`, `params_dict`), where `params_dict` also contains `max_offset` key. It will simplify the code a lot in other places.

Also, don't use `get_params_names` here, but df columns: this will help checking them for their name-consistency.

2022-09-09 15:12 UTC, bestetc commented on seismicpro/src/refractor_velocity/utils.py
> +        max_offset_list.append(row[-1])
It could be one list of  dict with params and coords.

2022-09-09 15:13 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        min_col_size : int, defaults to 11
No, it can be hardcoded or removed.
If `min_col_size` is removed, the output file will be less readable.
Example with `min_col_size` removed:
```
 name_x  name_y  coord_x  coord_y    t0      x1      v1      v2  max_offset
SourceX SourceY   724099  5790549 62.21 1616.46 2467.95 4124.87        2999
SourceX SourceY   724049  5790549 66.36 1611.77 2473.66 4101.66        3000
SourceX SourceY   724000  5790549 71.35 1615.74 2485.96 4099.83        3000
```

2022-09-09 16:19 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        min_col_size : int, defaults to 11
It can be easily calculated from data

2022-09-13 09:11 UTC, bestetc commented on seismicpro/src/refractor_velocity/utils.py
> +        max_offset_list.append(row[-1])
don't like instantiating `RefractorVelocity` or `RefractorVeloctiyField` in utils.

2022-09-13 11:35 UTC, alexanderkuvaev requested changes

2022-09-13 11:35 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/utils.py
> +def calc_df_to_dump(rv_list):
`calc_df_to_dump` is called only in conjunction with `dump_df` like `dump_df(calc_df_to_dump(...))`. Unify it in a single function called `dump_refractor_velocities`

2022-09-13 11:35 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/utils.py
> +        data = [*rv.coords.names] + [*rv.coords.coords] + list(rv.params.values()) + [rv.max_offset]
Create an array of data first and then make it a dataframe

2022-09-13 11:35 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/utils.py
> +def dump_df(df, path, encoding):
Set default encoding to UTF-8

2022-09-13 11:35 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/utils.py
> +def load_rv(path, encoding):
Set default encoding to UTF-8 and rename it to something like `load_refractor_velocities_params`

2022-09-13 11:35 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/utils.py
> +    params_list : list of dict,
```suggestion
    params_list : list of dict
```

2022-09-13 11:35 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/utils.py
> +        at one or more locations.
```suggestion
        at a given location.
```

2022-09-13 11:35 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/utils.py
> +            raise ValueError(f"Unsufficient parameters in the row {row}.")
Don't get this check, do you really want to validate max offset?

2022-09-13 11:35 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        min_col_size : int, defaults to 11
Or removed completely, you use it only to reconstruct a field

2022-09-13 11:35 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        # pylint: disable-next=not-a-mapping
Is it still valid?

2022-09-13 11:35 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        if len(params) > 1:
```suggestion
        if len(params) != 1:
```

2022-09-14 13:14 UTC, dpodvyaznikov reviewed
Looking forward to see existing comments fixed and `dump_df` function removed

2022-09-14 13:14 UTC, dpodvyaznikov commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        The output file should define near-surface velocity model at one or more field locations and have the following
```suggestion
        The output file defines near-surface velocity model at one or more field locations and has the following
```

2022-09-16 08:53 UTC, bestetc commented on seismicpro/src/refractor_velocity/utils.py
> +        data = [*rv.coords.names] + [*rv.coords.coords] + list(rv.params.values()) + [rv.max_offset]
using list of params allows you to save different data types (int and float) in the one data structure. creating dataframe from a dict allows you to cast type of data separately to different columns.
using one np.array don't allow that.

2022-09-16 09:18 UTC, bestetc commented on seismicpro/src/refractor_velocity/utils.py
> +            raise ValueError(f"Unsufficient parameters in the row {row}.")
The last item in a row will `np.nan` if a row has less values than expected. It will be True if any items is missing.

2022-09-16 09:22 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        # pylint: disable-next=not-a-mapping
removed

2022-09-28 23:42 UTC, nikita-klsh requested changes

2022-09-28 23:42 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/utils.py
> +        pd.concat(df_list).to_string(buf=f, float_format="%.2f", index=False)
```suggestion
        pd.concat(df_list).to_string(buf=path, float_format="%.2f", index=False, encoding=encoding)
```

2022-09-28 23:42 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/utils.py
> +def dump_refractor_velocity(rv_list, path, encoding="UTF-8"):
```suggestion
def dump_refractor_velocities(rv_list, path, encoding="UTF-8"):
```

2022-09-28 23:42 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/utils.py
> +    """Dump DataFrames to a file.
You dump RVs

2022-09-28 23:42 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/utils.py
> +        data = [*rv.coords.names] + [*rv.coords.coords] + list(rv.params.values()) + [rv.max_offset]
Remember the types of parameters, then create array from all of them.
When creating dataframe from this array, pass the types back

2022-09-28 23:42 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/utils.py
> +        columns = ['name_x', 'name_y', 'coord_x', 'coord_y'] + list(rv.params.keys()) + ["max_offset"]
Move out of the loop, infer from the first RV

2022-09-28 23:42 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/utils.py
> +    """Load the coordinates and parameters of RefractorVelocity from a file.
A bit missleading namings and docs, you loading multiple RVs, not a single one

2022-09-28 23:42 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/utils.py
> +        List of :class:`~refractor_velocity.RefractorVelocity` instances.
```suggestion
    rv_list : RefractorVelocity or iterable of RefractorVelocity.
        Refractor Velocity instances to dump to the file.
```

2022-09-28 23:42 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/utils.py
> +    for row in df.to_numpy():
Here you actually missing all the paramteres types, which you mention in the comment regarding dump

2022-10-04 13:22 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        self : RefractorVelocity
We used `self : class_name` in the same cases

2022-10-04 13:42 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        return self
We'd like to `return self` in most methods.
I'd check dump method in the another classes. `gather.dump` return self and `VFUNC.dump` doesn't.
I decide to add `return self`.

2022-10-04 13:52 UTC, bestetc commented on seismicpro/src/refractor_velocity/utils.py
> +        columns = ['name_x', 'name_y', 'coord_x', 'coord_y'] + list(rv.params.keys()) + ["max_offset"]
from_dict consturctor infers type sepately by cols. Using this construtor allows me do not track the types of data.

2022-10-05 15:18 UTC, bestetc commented on seismicpro/src/refractor_velocity/utils.py
> +    for row in df.to_numpy():
restored by `df.dtypes` below.

2022-10-06 10:25 UTC, alexanderkuvaev requested changes

2022-10-06 10:25 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +from .utils import get_param_names, postprocess_params,  dump_refractor_velocity, load_refractor_velocity
```suggestion
from .utils import get_param_names, postprocess_params, dump_refractor_velocity, load_refractor_velocity
```

2022-10-06 10:25 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +         name_x     name_y    coord_x    coord_y        t0        x1        v1        v2 max_offset
Pull `master` and remove `max_offset` from dump and load

2022-10-06 10:25 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/utils.py
> +    pd.DataFrame.from_dict(dict_list).to_string(buf=path, float_format="%.2f", index=False, encoding=encoding)
Avoid dicts, create numpy arrays for each group of columns

2022-10-06 10:25 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/utils.py
> +    encoding : str, defaults to "UTF-8"
```suggestion
    encoding : str, optional, defaults to "UTF-8"
```

2022-10-06 10:25 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/utils.py
> +        Each dict in the returned list contains parameters and coords sufficient to define near-surface velocity model
```suggestion
        Each dict in the returned list contains parameters and coords sufficient to define a near-surface velocity model
```

2022-10-06 10:25 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/utils.py
> +        at a given locations.
```suggestion
        at given field locations.
```

2022-10-06 10:25 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/utils.py
> +        params = dict(zip(params_names, row[4:].astype(df.dtypes[4:])))
What's the problem with params dtypes?

2022-10-06 16:40 UTC, alexanderkuvaev requested changes

2022-10-06 16:40 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +    def from_file(cls, path, survey=None, is_geographic=None, encoding="UTF-8"):
Also, don't forget about `auto_create_interpolator` flag

2022-10-12 11:57 UTC, nikita-klsh reviewed
Please unify docs with `VFuncs/VFuncFeild`, for example:

describe the format once only in utility functions, in `rv.load, rv.dump, rvf.load, rvf.dump` refer to this description

2022-10-12 11:57 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/utils.py
> +    df.to_string(buf=path, float_format="%.2f", index=False, encoding=encoding)
Let's pass formatter as function, as they ask in docs. Then pd.float32 are formatted as expected.

```suggestion
    df =  pd.DataFrame(data, columns=columns).convert_dtypes()
    df.to_string(path, index=False, encoding=encoding, float_format=lambda x: "{:.2f}".format(x))
```

2022-10-12 11:57 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        The file should define a near-surface velocity model at a given field location and have the following
Confusing reference to the field here

2022-10-12 11:57 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +    - by creating a fully updated field from the velocity model parameters and coords loaded from a file.
confusing, inspire by SFV docs

2022-10-12 11:57 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        - Each next line contains the coords names, coords values, and parameters values of one RefractorVelocity.
stick to rows everywhere

2022-10-12 12:04 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        The file should define a near-surface velocity model at a given field location and have the following
without coords this method do not work. remove `field`.

2022-10-12 12:23 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        structure:
Used simpler decription before but https://github.com/gazprom-neft/SeismicPro/pull/105#discussion_r966888349

2022-10-14 12:20 UTC, dpodvyaznikov requested changes

2022-10-14 12:20 UTC, dpodvyaznikov commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        - The first row contains names of the Coordinates parameters ("name_x", "name_y", "x", "y") and
```suggestion
        - The first row contains names of the coordinates parameters ("name_x", "name_y", "x", "y") and
```

2022-10-14 12:23 UTC, dpodvyaznikov commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        - The first row contains names of the Coordinates parameters ("name_x", "name_y", "x", "y") and
Here and below, it is discussional whether to use **Coordinates** as the name of the object, or **coordinates**. I'll accept either option if it will be used consistently

2022-10-16 15:21 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        """Dump the near-surface velocity model to a file.
Change to "a near-surface velocity model" to align with other constructors docs.

2022-10-17 10:13 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +
fixed to all these cases

2022-10-17 11:31 UTC, alexanderkuvaev approved these changes

2022-10-17 11:31 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +    - by loading a field from a file with velocity models parameters using `from_file` `claassmethod`.
```suggestion
    - by loading a field from a file with velocity models parameters using `from_file` `classmethod`.
```

2022-10-17 11:31 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        The file should define a near-surface velocity models at one or more field locations and have the following
```suggestion
        The file should define near-surface velocity models at one or more field locations and have the following
```

2022-10-17 12:50 UTC, nikita-klsh reviewed
There is a bit of mess in the docs of `RV.dump` and `RVF.dump` formats. 

Why not to describe the format once in the `utils.dump` and `utils.load` and refer there from public methods? The same is done the in `SV` and `SVF`

2022-10-17 12:50 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/utils.py
> +    """Load coordinates and parameters of the velocity models from a file.
We dump parameters, but load coordinates and parameters. Please unify

2022-10-17 12:50 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        """Load field with velocity models from a file.
You refer almost everywhere as `near-surface velocity`
```suggestion
        """Load field with near-surface velocity models from a file.
```

2022-10-17 12:50 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +            Path to the file.
```suggestion
            Path to the created file.
```

2022-10-17 12:50 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +            Path to a file.
```suggestion
            Path to the created file.
```

2022-10-17 12:50 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +         - The second row contains the corresponding values of the velocity model.
```suggestion
         - The second row contains the corresponding values of the near-surface velocity model.
```

2022-10-17 12:50 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +         - The second row contains the corresponding values of the velocity model.
In the dump below there are parameters, not values. Please unify
```suggestion
         - The second row contains the corresponding parameters of the velocity model.
```

2022-10-17 12:50 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        RefractorVelocity in the RefractorVelocityField.
In the `RV` you dump the paramteres of the near-surface velocity
In the `field`  you dump names, coords values and parameters for each RefractorVelocity

Same for load. Can we unify?

2022-10-18 11:15 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +         - The second row contains the corresponding values of the velocity model.
using of the parameters word can confuse the reader. "Values of parameters" are here. Or "values" to make it simpler

2022-10-18 13:09 UTC, dpodvyaznikov approved these changes

2022-10-18 13:09 UTC, dpodvyaznikov commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +    Note that in all these cases all velocity models in the field must describe the same number of refractors.
In the following PR I've commented that two "all"s in a row does not sound right. Also, all velocity models in the field must always describe the same number of refractors, not only in those cases.

2022-10-19 09:44 UTC, nikita-klsh approved these changes

2022-10-19 09:44 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/utils.py
> +    The file should define a near-surface velocity model at a given location and have the following structure:
```suggestion
    The file defines near-surface velocity models at a given locations and has the following structure:
```

2022-10-19 10:44 UTC, merged