Calculate RefractorVelocityField
gazprom-neft/SeismicPro pull request #106
Opened 2022-08-24 13:24 UTC by bestetc

Add to survey:
1. Calculate the RefractorVelocityField.
- could be calculated by supergather gathers.
- could be calculated init based on the full survey data.
- could be smooth RV parameters based by the nearest RV.
2. Add a loss plot to see how many refractors can be found. (Two refractors found on example.)
![Figure 92](https://user-images.githubusercontent.com/53880304/186429261-61133dae-f2e9-465c-8c8d-143ab9b6b787.png)

2022-10-06 10:36 UTC, alexanderkuvaev requested changes

2022-10-06 10:36 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +    Or creating from survey:
```suggestion
    Usually a field is directly created from a survey with loaded first breaks:
```

2022-10-06 10:36 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +    Or creating from survey:
And update class docs above

2022-10-06 10:36 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +    def from_file(cls, path, is_geographic=None, encoding="UTF-8"):
Why is it here?

2022-10-06 10:36 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        if len(survey.indices) < 1:
use `n_gathers`

2022-10-06 10:36 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        survey_data = survey[['offset', first_breaks_col] + list(coords_name)]
rename `data` to `headers`, confuses when it becomes `gather_data`

2022-10-06 10:36 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +            coords_value = gather_data[:, [2, 3]]
don't copy, slice

2022-10-06 10:36 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        max_offset : float, optional
This has changed in master

2022-10-06 10:36 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        """Calculate nearsurface velocity models for all gather in the passed Survey.
```suggestion
        """Calculate a near-surface velocity model for each gather in the survey.
```

2022-10-06 10:36 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        Read :class:~`RefractorVelocity` docs for more information about the calculating velocity model.
The method doesn't perform what is described here

2022-10-07 08:26 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +    def from_file(cls, path, is_geographic=None, encoding="UTF-8"):
merged with issues

2022-10-12 11:48 UTC, anton-br commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +                    loss='L1', huber_coef=20, min_velocity_step=1, min_refractor_size=1, tol=1e-5, bar=True,
please, unify artuments' order with `RV.from_first_break` method (do not forget to update docs either)

2022-10-12 11:48 UTC, anton-br commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +            times = gather_data[:, 1]
use `gather_data[:, 0]` and `gather_data[:, 1]` directly, not need to store them since you use them only once here

2022-10-12 11:48 UTC, anton-br commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +    - by creating a populated field using `from_survey`.
```suggestion
    - by creating an empty field and then iteratively updating it with estimated velocities using `update`,
    - by constructing a field directly from a survey using `from_survey`.
```

2022-10-12 11:48 UTC, anton-br commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +    Usually a field is directly created from a survey with loaded first breaks:
Seems wierd to write "usually" in last option of field creation. For me usually means most often way to create. If you think that this method will be the popular one, this example should be the first one here and first way in docs above.

2022-10-12 11:48 UTC, anton-br commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +    Note that in both these cases all velocity models in the filed must describe the same number of refractors.
```suggestion
    Note that in all these cases all velocity models in the filed must describe the same number of refractors.
```

2022-10-12 15:01 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +            times = gather_data[:, 1]
Think about. Just want to make this code more explicit.

2022-10-12 15:12 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        Read :class:~`RefractorVelocity` docs for more information about the calculating velocity model.
rework

2022-10-13 10:33 UTC, nikita-klsh reviewed
Please think about the same interfarce not only for `Survey`, but `SesimicDataset` as well.

2022-10-13 10:33 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +            times = gather_data[:, 1]
You already infer max_offset implicitely above, use directly

2022-10-13 10:33 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +            gather_data = survey_headers[trace_idx]
```suggestion
        for gather_idx in tqdm(survey.indices, desc="Calculate velocity models", disable=not bar):
            traces_locs = survey.get_traces_locs([gather_idx])
            gather_headers = survey_headers[traces_locs]
```

2022-10-17 10:07 UTC, dpodvyaznikov requested changes

2022-10-17 10:18 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +            should be preferably explicitly passed.
I'd like to remove `max_offset` from parameters and it infer always from survey.

2022-10-17 10:34 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        max_offset = survey_headers[:, 0].max() if max_offset is None else max_offset
changed, will always infer from survey.

2022-10-17 11:47 UTC, alexanderkuvaev approved these changes

2022-10-17 11:47 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +            CROSSLINE_3D)). Inferred automatically on the first update if not given.
```suggestion
            CROSSLINE_3D)). Inferred automatically by the type of survey gathers if not given.
```

2022-10-17 11:47 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        coords_name = get_coords_cols(survey.indexed_by)
```suggestion
        coords_cols = get_coords_cols(survey.indexed_by)
```

2022-10-17 11:47 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        survey_headers = survey[['offset', first_breaks_col] + list(coords_name)]
```suggestion
        survey_headers = survey[('offset', first_breaks_col) + coords_cols]
```

2022-10-17 11:47 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        for gather_idx in tqdm(survey.indices, desc="Calculate velocity models", disable=not bar):
```suggestion
        for gather_idx in tqdm(survey.indices, desc="Velocity models estimated", disable=not bar):
```

2022-10-17 11:47 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +                raise ValueError(f"Coordinates non-unique for gather with index {gather_idx}.")
```suggestion
                raise ValueError(f"Non-unique coordinates are found for a gather with index {gather_idx}.")
```

2022-10-17 11:47 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +            coords = Coordinates(names=coords_name, coords=gather_headers[0, 2:])
```suggestion
            coords = Coordinates(gather_headers[0, 2:], names=coords_cols)
```

2022-10-17 11:55 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +            coords = Coordinates(names=coords_name, coords=gather_headers[0, 2:])
change to `coords = Coordinates(coords=gather_headers[0, 2:], names=coords_cols)` to make it a little bit more explicit.

2022-10-18 13:19 UTC, dpodvyaznikov approved these changes

2022-10-19 09:58 UTC, nikita-klsh approved these changes

2022-10-19 09:58 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        for gather_idx in tqdm(survey.indices, desc="Velocity models estimated", disable=not bar):
```suggestion
        for gather_idx in tqdm(survey.indices, desc="Near-surface velocity models estimated", disable=not bar):
```

2022-10-19 09:58 UTC, nikita-klsh commented on seismicpro/src/refractor_velocity/refractor_velocity_field.py
> +        """Create a field by fitting a near-surface velocity model for each gather in the survey.
You use fit here and estimate in the bar desc, please unify.
```suggestion
        """Create a field by estimating a near-surface velocity model for each gather in the survey.
```

2022-10-19 10:45 UTC, merged