Coherency
gazprom-neft/SeismicPro pull request #109
Opened 2022-10-11 11:43 UTC by nikita-klsh

2022-11-10 13:50 UTC, anton-br requested changes

2022-11-10 13:50 UTC, anton-br commented on seismicpro/gather/utils/correction.py
> +        In case `False`, the nearest trace amplitude obtained.
If `False` you took not `nearset` value but round to lower time sample.

BTW, why do you use `int(hodograph_time)` there? not `int(np.round(hodograph_time))`

2022-11-10 13:50 UTC, anton-br commented on seismicpro/gather/utils/correction.py
> +    for i, hodograph_time in enumerate(hodograph_times / sample_rate):
Why enumerate? Isn't it slower than `prange`?

2022-11-10 13:50 UTC, anton-br commented on seismicpro/gather/gather.py
> +            This mutes the areas where the time reversal occured after the correction.
```suggestion
            Whether to mute areas where the time reversal occurred after nmo corrections.
```

2022-11-10 13:50 UTC, anton-br commented on seismicpro/gather/utils/correction.py
> +    """ Retrieve hodograph amplitudes from the `gather_data`.
We ususally dont add space here
```suggestion
    """Retrieve hodograph amplitudes from the `gather_data`.
```

2022-11-10 13:50 UTC, anton-br commented on seismicpro/muter/muter.py
> +        This muter is supposed to attenuate the effect of waveform stretching after the nmo correction.
```suggestion
        """ Create a muter from a stacking velocity that is supposed to attenuate the effect of waveform stretching after the nmo correction.
```

2022-11-10 13:50 UTC, anton-br commented on seismicpro/muter/muter_field.py
> +
delete empty line

2022-11-10 13:50 UTC, anton-br commented on seismicpro/muter/muter.py
> +            Maximum allowed stretch factor.
Docs and parameter name confuses a bit. If it is a maximum stretch factor, why name it not `max_stretch_factor`?

Either docs or name should be changed.

2022-12-13 16:13 UTC, nikita-klsh commented on seismicpro/semblance/semblance.py
> +        clip_threshold_quantile : float, optional, defaults to 0.99
Added

2022-12-13 16:20 UTC, nikita-klsh commented on seismicpro/semblance/semblance.py
> +    def _calc_res_semblance_numba(semblance_func, coherency_func, gather_data, times, offsets, velocities,
Its either all the methods move to `njitted functions` or stay as `njitted staticmethods`.
I'd rather keep all the logic in the class

2022-12-13 16:29 UTC, nikita-klsh commented on seismicpro/semblance/semblance.py
>          Temporal window size for smoothing the semblance. Measured in samples.
Not really

2023-01-19 15:48 UTC, alexanderkuvaev requested changes

2023-01-20 14:39 UTC, alexanderkuvaev requested changes

2023-01-20 14:39 UTC, alexanderkuvaev commented on seismicpro/semblance/utils/coherency_funcs.py
> +        denominator[i] = np.nansum(corrected_gather[i, :] ** 2) * sum(~np.isnan(corrected_gather[i, :]))
Is `sum` faster than `np.sum`? Actually, I'd simply change `nansum` to `nanmean` in numerator, probably it would be even faster.

2023-01-20 14:39 UTC, alexanderkuvaev commented on seismicpro/semblance/utils/coherency_funcs.py
> +        numerator[i] = np.nanmean(corrected_gather[i, :])
Let's add `abs` here, otherwise velocity picking algorithm will fail

2023-01-20 14:39 UTC, alexanderkuvaev commented on seismicpro/semblance/utils/coherency_funcs.py
> +    denominator = np.full(corrected_gather.shape[0], 2)
Considering wrong time-window aggregation in semblance code, denominator should be `np.ones` and division by 2 should occur in `numerator` calculation

2023-01-20 14:39 UTC, alexanderkuvaev commented on seismicpro/semblance/utils/coherency_funcs.py
> +        denominator[i] = input_enerty * sum(~np.isnan(corrected_gather[i, :])) / 2
```suggestion
        denominator[i] = input_enerty
```

2023-01-20 14:39 UTC, alexanderkuvaev commented on seismicpro/semblance/utils/coherency_funcs.py
> +        numerator[i] = output_energy - input_enerty
```suggestion
        numerator[i] = (output_energy - input_enerty) / (np.sum(~np.isnan(corrected_gather[i, :])) - 1)
```

2023-01-27 16:28 UTC, nikita-klsh commented on seismicpro/gather/utils/correction.py
> +    for i, hodograph_time in enumerate(hodograph_times / sample_rate):
This prange would be 3rd level of parallelism(over velocities and times).
Adding this dramatically slows down semblance

2023-02-08 12:38 UTC, alexanderkuvaev requested changes
Also, please rerun the benchmark. Hopefully nothing will change)

2023-02-08 12:38 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +        velocity_spectrum_slice = np.zeros(t_max_ix - t_min_ix, dtype=np.float32)
Let's init it with `empty`

2023-02-08 12:38 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +                                                    (np.sum(denominator[ix_from : ix_to]) + 1e-8)
Not sure if this is a bottleneck at all, but this block may be simplified to:
1. Calculation of window sums of `numerator` and `denominator` using `np.convolve` with array of ones,
2. Element-wise division

2023-02-08 12:38 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/utils/coherency_funcs.py
> +
Please add a general comment, that `corrected_gather` is transposed here and has shape `(n_samples, n_traces)`. Not valid, if you remove transpose after `apply_nmo` in spectrum calculation.

2023-02-08 12:38 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/utils/coherency_funcs.py
> +    return numerator, denominator
Here `denominator` should be 1 after window summation, now it will become equal to window size.

2023-02-08 12:38 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/utils/coherency_funcs.py
> +        denominator[i] = np.nansum(corrected_gather[i, :] ** 2) * np.sum(~np.isnan(corrected_gather[i, :]))
```suggestion
        numerator[i] = (np.nansum(corrected_gather[i, :]) ** 2) / max(np.sum(~np.isnan(corrected_gather[i, :])), 1)
        denominator[i] = np.nansum(corrected_gather[i, :] ** 2)
```

2023-02-10 11:25 UTC, alexanderkuvaev requested changes

2023-02-10 11:25 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +        self.half_win_size_samples = math.ceil((window_size - gather.sample_rate) / gather.sample_rate / 2)
```suggestion
        self.half_win_size_samples = math.ceil((window_size / gather.sample_rate / 2)
```

2023-02-10 11:25 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +    For different coherency measures the numerator and denominator calculated as follows:
I'd list all of them here since they lack docs in their module. And please add a short name after the full one for each of them

2023-02-10 11:25 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +    The gather should be sorted by offset.
I'd drop this note, we sort the gather on our side

2023-02-10 11:25 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +    The gather should be sorted by offset.
Also remove

2023-02-14 14:30 UTC, anton-br commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +            stacking_times_ix = stacking_times / self.sample_rate
`times_to_indices`?

2023-02-14 14:30 UTC, anton-br commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +            `semblance`,
what about shot names here?

2023-02-15 13:09 UTC, nikita-klsh commented on seismicpro/gather/gather.py
> +            The available options are:
There is already a link 20 lines above

2023-02-15 13:10 UTC, nikita-klsh commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +        self.half_win_size_samples = math.ceil((window_size - gather.sample_rate) / gather.sample_rate / 2)
Not worth compilingfunction for single division

2023-02-15 13:11 UTC, nikita-klsh commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +            stacking_times_ix = stacking_times / self.sample_rate
Not sure it's worth compiling the function for single call

2023-02-15 13:31 UTC, nikita-klsh commented on seismicpro/gather/gather.py
> +        amplify_factor = np.clip(amplify_factor, 0, 1)
Since the logic here: the more - the stronger, i believe it's fine to clip

2023-02-15 14:26 UTC, nikita-klsh commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +        If not provided, velocities evenly sampled from  `const.DEFAULT_STACKING_VELOCITY` with step 100 m/s.
How would you extend existing description?

2023-02-15 16:35 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +            stacking_times_ix = stacking_times / self.sample_rate
@anton-br semblance assumes constant sample rate and validates it implicitly calling `gather.sample_rate`, thus simple division is enough

2023-02-16 10:05 UTC, alexanderkuvaev approved these changes

2023-02-16 10:05 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +    def calc_single_velocity_spectrum(coherency_func, gather_data, times, offsets, velocity, sample_rate,
This may accept `out` arg similar to `get_hodograph`. This will avoid excessive allocations and simplify code formatting below

2023-02-16 10:05 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +        numerator(i, v) = (sum^{M-1}_{j=0} f_{j}(i, v))^2
```suggestion
        numerator(i, v) = (sum^{M-1}_{j=0} f_{j}(i, v))^2 / M
```

2023-02-16 10:05 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +        denominator(i, v) = M * sum^{M-1}_{j=0} f_{j}(i, v)^2
```suggestion
        denominator(i, v) = sum^{M-1}_{j=0} f_{j}(i, v)^2
```

2023-02-16 10:05 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +        denominator(i, v) = 1
We can set it to 2 here as well as in `coherency_funcs`

2023-02-16 10:05 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +        numerator(i, v) = (sum^{M-1}_{j=0} f_{j}(i, v))^2 - sum^{M-1}_{j=0} f_{j}(i, v)^2
```suggestion
        numerator(i, v) = ((sum^{M-1}_{j=0} f_{j}(i, v))^2 - sum^{M-1}_{j=0} f_{j}(i, v)^2) / (M - 1)
```

2023-02-16 10:05 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +        denominator(i, v) = (M - 1) * (sum^{M-1}_{j=0} f_{j}(i, v)^2)
```suggestion
        denominator(i, v) = sum^{M-1}_{j=0} f_{j}(i, v)^2
```

2023-02-16 10:44 UTC, alexanderkuvaev commented on seismicpro/velocity_spectrum/velocity_spectrum.py
> +        If not provided, velocities evenly sampled from  `const.DEFAULT_STACKING_VELOCITY` with step 100 m/s.
As an option:
If not provided, velocity range is inferred from `const.DEFAULT_STACKING_VELOCITY` evaluated for gather times and extended by 20%. Velocities themselves are then evenly sampled from this range with a step of 100 m/s.

Also, this line is used several times, fix it everywhere

2023-02-16 14:02 UTC, anton-br approved these changes

2023-02-16 15:26 UTC, merged