Store headers from gather to survey
gazprom-neft/SeismicPro pull request #116
Opened 2022-11-17 13:24 UTC by anton-br

Add an abilibty to save any columns from `Gather` to the parent `Survey`. 

Used in pipeline, method `store_to_survey` (any suggestions about naming are highly welcome) will save columns to `Survey` that generated certain `Gather` object.

2022-11-17 14:22 UTC, alexanderkuvaev requested changes

2022-11-17 14:22 UTC, alexanderkuvaev commented on seismicpro/index.py
> +                   for survey, headers, pos in zip(surveys, gather_headers, traces_pos)]
`traces_pos` is already in `gather_headers` in index case. Seems like storing them in `headers` setter of a `Survey` class will simplify code a lot: no changes here, in `Survey.load_gather` and in `Gather.__init__` will be required

2022-11-17 14:22 UTC, alexanderkuvaev commented on seismicpro/index.py
> +        headers["GLOBAL_TRACE_POS"] = np.arange(survey.n_traces)
Please merge `1d_ix` in your branch: it changes the code nearby a bit

2022-11-17 15:54 UTC, nikita-klsh commented
What if gather being filtered after the load?

```
copy_survey = survey.copy()
copy_survey.sample_gather().sort('offset').store_to_survey('offset')
(copy_survey['offset'] == survey['offset']).all()
>> False
```

2022-11-17 17:42 UTC, anton-br commented
> What if gather being filtered after the load?
> 
> ```
> copy_survey = survey.copy()
> copy_survey.sample_gather().sort('offset').store_to_survey('offset')
> (copy_survey['offset'] == survey['offset']).all()
> >> False
> ```

Should work, now :)

2022-11-17 17:47 UTC, anton-br commented on seismicpro/index.py
> +                   for survey, headers, pos in zip(surveys, gather_headers, traces_pos)]
added, also I add `trace_indexer` to track traces positions in case when `Survey` was somehow  changed after `Gather` sampling
.

2022-11-18 09:04 UTC, alexanderkuvaev requested changes

2022-11-18 09:04 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +            if column not in self.survey.headers.columns:
```suggestion
            if column not in self.survey.headers:
```

2022-11-18 09:04 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +    def store_to_survey(self, columns):
I'd call it `store_headers_to_survey` to be more explicit

2022-11-18 09:04 UTC, alexanderkuvaev commented on seismicpro/const.py
> +HDR_TRACES_POS = 'TRACES_POS'
```suggestion
HDR_TRACE_POS = 'TRACE_POS'
```
I'd at least remove "s" to match other headers like "FirstBreak" or "offset" which refer to a single trace.
Probably I'd also rename it to `TRACE_POS_IN_SURVEY`. It's used only in a couple of places, so a longer but more explicit name seems acceptable.

2022-11-18 12:58 UTC, alexanderkuvaev requested changes

2022-11-18 12:58 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +        self.headers[HDR_TRACES_POS] = np.arange(self.n_traces, dtype=np.int32)
Follow the logic of `tsf_dtype` in init

2022-11-21 10:02 UTC, alexanderkuvaev requested changes

2022-11-21 10:02 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +            raise ValueError(f"Unknown headers: {', '.join(unknown_headers)}")
Do we really need this check?

2022-11-21 10:02 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +            headers[column].array[self[HDR_TRACE_POS]] = self[column]
Precalculate `self[HDR_TRACE_POS]` once before the loop

2022-11-21 10:02 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +        headers = self.survey._headers  # pylint: disable=protected-access
```suggestion
        headers = self.survey.headers
```

2022-11-28 08:48 UTC, anton-br commented on seismicpro/gather/gather.py
> +            raise ValueError(f"Unknown headers: {', '.join(unknown_headers)}")
yes. Otherwise you'll first add a new column in the survey headers and then fall with an error since you don't have this column in gather headers.

2022-11-29 11:22 UTC, a-arefina commented on seismicpro/tests/test_gather.py
> +    drop_cols = to_list(drop_cols) + to_list(EXTERNAL_HEADERS) if drop_cols is not None else EXTERNAL_HEADERS
check parentheses and execution order to ensure that you get what you want here

2022-11-29 11:23 UTC, a-arefina commented on seismicpro/tests/test_gather.py
> +    gather.store_headers_to_survey(columns)
what about checking the content of `gather.survey,headers` ?

2022-11-29 11:23 UTC, a-arefina commented on seismicpro/gather/gather.py
> +        pos = self[HDR_TRACE_POS]
Why not use `TRACE_SEQUENCE_FILE`?

2022-11-29 11:33 UTC, anton-br commented on seismicpro/gather/gather.py
> +        pos = self[HDR_TRACE_POS]
because TSF might not be unique in survey. For example, if you create supergathers with step < sp_size.

2022-11-29 16:30 UTC, nikita-klsh commented
```
gather = survey.sample_gather()
gather['offset'] = gather['offset'] * 0.1
gather.store_headers_to_survey('offset')
```
```
display(gather.headers.head())
```
![image](https://user-images.githubusercontent.com/8656643/204586511-5e438a84-4b05-435c-a1ab-786f1adb7497.png)
```
display(survey.headers.head())
```
![image](https://user-images.githubusercontent.com/8656643/204586770-4b30f1d1-ccb4-40d6-a967-cf60772ca16d.png)

2022-11-29 17:41 UTC, nikita-klsh commented on seismicpro/gather/gather.py
> +        in the Gather.
```suggestion
    def save_headers_to_survey(self, headers):
        """Save given headers from `self` to `self.survey`.
```

2022-11-29 17:41 UTC, nikita-klsh commented on seismicpro/gather/gather.py
> +        the method.
```suggestion
        The correct result is guaranteed only if the `self.survey` hasn't being changed after `self` creation.
```

2022-11-29 17:41 UTC, nikita-klsh commented on seismicpro/gather/gather.py
> +            raise ValueError(f"Unknown headers: {', '.join(unknown_headers)}")
You will fall here with `index_header`, for example `FieldRecord`

Would be nice to deligate this check to `self[columns]`.

2022-11-29 17:41 UTC, nikita-klsh commented on seismicpro/tests/test_gather.py
> +def gather_with_cols(survey):
Does this object deserve new fixture if it's used once?

2022-11-29 17:41 UTC, nikita-klsh commented on seismicpro/tests/test_gather.py
> +    headers_from_gather = gather_with_cols.headers.sort_values(by="offset")
With this sort on the `DataFrame` level you actually guarantee that equality bellow holds, even if you mess with trace positions in your action. 

```suggestion
    headers_from_survey = survey.headers.loc[gather_with_cols.index]
    headers_from_gather = gather_with_cols.headers
```

2022-12-05 08:46 UTC, dpodvyaznikov requested changes

2022-12-05 08:46 UTC, dpodvyaznikov commented on seismicpro/tests/test_gather.py
> +    drop_cols = (to_list(drop_cols) + to_list(EXTERNAL_HEADERS)) if drop_cols is not None else EXTERNAL_HEADERS
First, `compare_gathers` right now is used only in `test_dump_mere`, where you already add `EXTERNAL_HEADERS` to `drop_cols` list in line 85. It seems that after this line EXTERNAL_HEADERS would be duplicated in `drop_cols`. Since this function should just compare two gathers and already has a `drop_cols`  arg, I believe it is better to cook `drop_cols` properly everywhere else and make this function unaware of any external constants.
Second note, regarding the code style only: IMO it would be better to write such an expression like this
```suggestion
    drop_cols = to_list(EXTERNAL_HEADERS) + (to_list(drop_cols) if drop_cols is not None else [])
```

2022-12-05 08:46 UTC, dpodvyaznikov commented on seismicpro/tests/test_gather.py
> +def gather_with_cols(survey):
I see no problem here

2022-12-05 08:46 UTC, dpodvyaznikov commented on seismicpro/tests/test_dump_merge.py
> +                                                  & set(tuple(expected_survey.headers.columns))
Maybe there is a simpler way to achieve this?

2022-12-05 08:46 UTC, dpodvyaznikov commented on seismicpro/tests/survey/asserters.py
> +EXTERNAL_HEADERS = {HDR_TRACE_POS}
Check please, maybe you can make `DEFAULT_DROP_HEADERS` constant and add "TRACE_SEQUENCE_FILE" there too

2022-12-05 11:59 UTC, anton-br commented on seismicpro/gather/gather.py
> +        Notes
I am okay with any of these appoarches. What's others thoughts?

2022-12-05 13:12 UTC, anton-br commented on seismicpro/tests/survey/asserters.py
> +EXTERNAL_HEADERS = {HDR_TRACE_POS}
No, we can't. Since we use TSF as new_index in test_reindex for in Survey tests and there we don't want to drop it, while want to drop HDR_TRACE_POS.

2022-12-05 14:55 UTC, anton-br commented on seismicpro/tests/test_gather.py
> +    drop_cols = (to_list(drop_cols) + to_list(EXTERNAL_HEADERS)) if drop_cols is not None else EXTERNAL_HEADERS
done

2022-12-05 14:56 UTC, anton-br commented on seismicpro/tests/test_dump_merge.py
> +                                                  & set(tuple(expected_survey.headers.columns))
I rewrote it a bit:)

2022-12-13 12:42 UTC, alexanderkuvaev requested changes

2022-12-13 12:42 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +        _ = self[columns] # Make sure that columns are in headers
Now you select columns twice, I'd do it once only here and use the results in the loop

2022-12-13 12:42 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +            if np.issubdtype(headers[column].dtype, np.integer) and np.issubdtype(column_data.dtype, np.floating):
+, except for this change:
```suggestion
            if not np.can_cast(column_data, headers.dtypes[column]):
```
To avoid column subsetting.

2022-12-15 22:27 UTC, anton-br commented on seismicpro/tests/survey/asserters.py
> +EXTERNAL_HEADERS = {HDR_TRACE_POS}
done

2022-12-15 22:28 UTC, anton-br commented on seismicpro/gather/gather.py
> +        """Save given headers from `self` to `self.survey`.
done

2022-12-15 22:28 UTC, anton-br commented on seismicpro/tests/survey/test_init.py
> +                                     # bar disabled, survey wasn't validated
done

2022-12-15 22:29 UTC, anton-br commented on seismicpro/tests/survey/asserters.py
>      assert np.array_equal(loaded_headers["TRACE_SEQUENCE_FILE"].values, np.arange(1, n_traces + 1))
this won't work this way because you sorting headers when creating `loaded_headers`. I added this check before, directly checking headers in `survey.headers`

2022-12-20 06:09 UTC, alexanderkuvaev requested changes

2022-12-20 11:48 UTC, anton-br commented on seismicpro/tests/test_gather.py
> +def gather_with_cols(segy_path):
moved

2022-12-20 11:48 UTC, anton-br commented on seismicpro/tests/survey/test_reindex.py
> +        survey_headers = (set(survey.headers.index.names) | set(survey.headers.columns)) - {HDR_TRACE_POS}
done

2022-12-21 07:55 UTC, alexanderkuvaev approved these changes

2022-12-21 14:02 UTC, nikita-klsh approved these changes

2022-12-21 14:02 UTC, nikita-klsh commented on seismicpro/gather/gather.py
> +            Column names in `self.headers` that will be added to `self.survey` headers.
```suggestion
            Column names from `self.headers` that will be saved to `self.survey` headers.
```

2022-12-28 16:19 UTC, dpodvyaznikov approved these changes

2022-12-28 16:19 UTC, merged