Update RVF plotting
gazprom-neft/SeismicPro pull request #118
Opened 2022-11-18 10:57 UTC by alexanderkuvaev

`RefractorVelocityField.plot_fit` now handles non-fit fields and is thus renamed to `plot`.

2022-12-01 13:13 UTC, nikita-klsh requested changes

2022-12-01 13:13 UTC, nikita-klsh commented on seismicpro/refractor_velocity/interactive_plot.py
> +        max_time = max(rv.piecewise_times[-1] for rv in field.items)
Currently we are not properly estimating `rv.picewise_times`, e.g. not accounting `max_offset`

```
field_plot = FieldPlot(field)
print(field.items[0].times.max())
> 850
print(field_plot.y_lim)
> [0,  650]
```
![image](https://user-images.githubusercontent.com/8656643/205061816-c9c01a79-f8d0-4ed8-b301-07e2632b389d.png)

2022-12-12 16:23 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/interactive_plot.py
> +        max_time = max(rv.piecewise_times[-1] for rv in field.items)
Fixed

2022-12-16 12:41 UTC, nikita-klsh approved these changes

2022-12-16 13:16 UTC, merged