Sort gather by multiple headers
gazprom-neft/SeismicPro pull request #120
Opened 2022-12-08 14:16 UTC by nikita-klsh

`gather.sort(by)` now can work with multiple headers

The `gather.sort_by` attribute is latter is used in `gather.plot` to infer axis ticks. 
In case `gather` is sorted by two headers, add minor ticks to handle minor header, e.g.

`gather.sort(['SourceWaterDepth', 'GroupWaterDepth']).plot()`
![image](https://user-images.githubusercontent.com/8656643/206468670-3494150b-ba40-4a9e-898b-773b8f196ed2.png)

2022-12-15 09:35 UTC, alexanderkuvaev requested changes

2022-12-15 09:35 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +        order = np.lexsort(self[to_list(by)].T[::-1])
```suggestion
        order = np.lexsort(self[to_list(by)[::-1]].T)
```
For me such order is more clear, but up to you

2022-12-15 09:35 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +            if (np.lexsort(new_self.headers[to_list(new_self.sort_by)].values.T[::-1]) != np.arange(len(data))).any():
`__getitem__` was supposed to be as fast as possible, but here a lexsort over all headers is called. Check if we can simply this by setting `sort_by` to `None` if `indices[0]` is not monotonically increasing.

2022-12-15 09:35 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
>          if self.sort_by == by:
Now you should do nothing if `self.sort_by` starts with `by`

2022-12-15 09:35 UTC, alexanderkuvaev commented on seismicpro/utils/plot_utils.py
> -    label = label[0].upper() + label[1:]
We still have an old bug: default value for label is an empty string and here we take the first element of it, which fails. Please fix it in your code below

2022-12-15 09:35 UTC, alexanderkuvaev commented on seismicpro/utils/plot_utils.py
> +    if len(label) > 1:
Please add a check that `len(labels)` equals `tick_labels.shape[1]` if it's 2d

2022-12-15 14:05 UTC, alexanderkuvaev requested changes

2022-12-15 14:05 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +            major_labels, minor_labels = self._get_y_ticks(tick_src), None
`_get_x_ticks` and `_get_y_ticks` are supposed to be alike, but the first one returns both major and minor tick labels, while the latter returns only mahor ticks. I'd split `_set_ticks` method into two: `_set_x_ticks` and `_set_y_ticks` which incorporate  the code of `_get_x_ticks` and `_get_y_ticks` respectively. This will make the code cleaner and remove this strange `if`.

2022-12-23 12:50 UTC, anton-br commented on seismicpro/utils/plot_utils.py
> +    axis_label = '\n'.join([UNITS.get(ix_label, '') for ix_label in to_list(label)])
this won't work:(
```suggestion
    axis_label = '\n'.join([ix_label + UNITS.get(ix_label, '') for ix_label in to_list(label)])
```

2022-12-27 11:12 UTC, anton-br approved these changes
Anyway, consider expand tests for gahter.sort by adding single parameter with multiple headers.

I suggest add smth like this in test/gather_test.py:
```
@pytest.mark.parametrize('by', ('offset', ['offset', 'FieldRecord']))
def test_gather_sort(gather, by):
    """test_gather_sort"""
    gather.sort(by=by)
```

2022-12-27 11:40 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +        if new_self.sort_by is not None:
You don't need the outer `if`

2022-12-27 11:40 UTC, alexanderkuvaev commented on seismicpro/utils/plot_utils.py
>      UNITS = {  # pylint: disable=invalid-name
This dict becomes extremely complicated: now keys like "Relative velocity margin" are present here. Can we remove this units logic at all and move it in the outer calling function?

2022-12-27 13:53 UTC, nikita-klsh commented on seismicpro/gather/gather.py
> +        if new_self.sort_by is not None:
Tho it can be removed, but then unnecessary computations would be done in case gather was not sorted.

I would stick with master logic where it could be remove aswell, but it presents.

2022-12-27 13:53 UTC, nikita-klsh commented on seismicpro/gather/gather.py
> +    def _plot_seismogram(self, ax, title, x_ticker, y_ticker, x_tick_src=None, y_tick_src='Time', colorbar=False,
Fixed, thx

2022-12-27 13:59 UTC, nikita-klsh commented
> Anyway, consider expand tests for gahter.sort by adding single parameter with multiple headers.
> 
> I suggest add smth like this in test/gather_test.py:
> 
> ```
> @pytest.mark.parametrize('by', ('offset', ['offset', 'FieldRecord']))
> def test_gather_sort(gather, by):
>     """test_gather_sort"""
>     gather.sort(by=by)
> ```
Added

2022-12-27 14:40 UTC, nikita-klsh commented on seismicpro/utils/plot_utils.py
>      UNITS = {  # pylint: disable=invalid-name
If only the presence of non physical unit among physical ones looks redundant, we can remove only him.

The pros of having such dict: all the units logic happens in one place. For example, if once we would have foots for distance, feels like it would be easier to catch up.

2023-01-09 12:43 UTC, a-arefina commented on seismicpro/gather/gather.py
> +        by = to_list(by)
Maybe check add some checks on `by`? Ex., `len(by) > 0` & each element is `str`

2023-01-09 12:43 UTC, a-arefina commented on seismicpro/gather/gather.py
> +        data = self.data.ravel() if x_tick_src == "Amplitude" else self[x_tick_src]
what about allowing both lower case and title case by adding `x_tick_src = x_tick_src.title()` ?

2023-01-19 09:20 UTC, alexanderkuvaev requested changes

2023-01-19 09:20 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +        if new_self.sort_by is not None:
Fine, thx

2023-01-19 09:20 UTC, alexanderkuvaev commented on seismicpro/utils/plot_utils.py
>      UNITS = {  # pylint: disable=invalid-name
I don't like that a function that should only set ticks also alters the passed parameters (`label` in this case). Such an approach would make even harder to handle other units like distances in feet because only outer object such as a `Gather` knows about it.

I'd do the following:
1. Remove this extra units processing logic and set `label` as it was passed,
2. Restore `Semblance`/`RefractorVelocity`/... plots back to `master` version which processed units on their own,
3. Move units processing logic inside `_set_x_ticks` and `_set_y_ticks` of a `Gather` class

This will also allow to un-capitalize default arguments of all `Gather._plot*` methods as suggested by @a-arefina

2023-01-19 16:43 UTC, alexanderkuvaev requested changes

2023-01-19 16:43 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +            major_labels =  self.samples
`tick_src` is `"time"` here, `", ms"` is added later. Moreover, `.title` should have capitalized it to `"Time, Ms"`. And remove extra space after =.

2023-01-20 11:26 UTC, alexanderkuvaev requested changes

2023-01-20 11:26 UTC, alexanderkuvaev commented on seismicpro/utils/plot_utils.py
> +    axis_label = '\n'.join(to_list(label))
Let's move this line to the only place it is currently used: `Gather._set_x_ticks`

2023-01-20 12:30 UTC, alexanderkuvaev approved these changes

2023-01-20 12:40 UTC, merged