Refractor velocity field qc
gazprom-neft/SeismicPro pull request #121
Opened 2022-12-12 14:59 UTC by AnnaAltynova

added First breaks outliers and a new Divergence point (any naming suggestions are highly welcome) metrics to qc method. More metrics are in progress

2022-12-13 09:38 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +            survey = survey.reindex(coords_cols, inplace=False)
Later you use offsets and first breaks of "gathers" groupped by `coords_cols` of the field, not the gathers defined by survey. I'd stick to the latter as more explicit. Moreover, this reindexation may fail if the field is constructed by supergathers (most common case), but QC of a non-supergather survey is performed.

2022-12-13 09:38 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +class RefractorVelocityScatterMapPlot(ScatterMapPlot):
Don't get this class at all, neex your explanation

2022-12-13 09:38 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        return cls.calc_metric(*args, **kwargs)
Why not override `calc` directly?

2022-12-13 09:38 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +                                    if refractor_velocities is not None else None
I'd store a reference to the field here and call it inside plotter. Also, avoid backslashing wherever possible.

2022-12-13 09:38 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +            metric.append(np.mean(np.abs(gather_rv(gather_offsets) - gather_times) > threshold_times))
You use `FirstBreaksOutliers.calc` directly in the next metric, but not in this one. Why?

2022-12-13 09:38 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        super().plot_refractor_velocity(coords, ax, **kwargs)
Very strange `kwargs` popping here, should not be this way

2022-12-13 09:38 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        self.vmax = survey.headers['offset'].max() if survey is not None else None
Use `survey["offset"]` hereinafter

2022-12-13 09:38 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +            metric[idx] = DivergencePoint.calc_(times[idx], offsets[idx], refractor_velocities[idx], fb_metric,
Make this method a `classmethod` and use `cls.calc_` here. Also, better call it `_calc`, not `calc_`.

2022-12-13 09:38 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +    def calc_(times, offsets, rv, fb_metric, threshold_times, offset_step):
Looks too complex, I'll take a look at it later

2022-12-13 09:40 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +                   for metric in metrics]
I'd swap the iteration order: first gathers then metrics. This will allow for a meaningfull progress bar support and convenient parallelization later.

2023-01-27 10:59 UTC, alexanderkuvaev requested changes

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +import time
You don't use it. Also, all standard lib imports should be placed first

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +from numba.typed import Dict
Remove unused imports

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +
Single empty line between class methods

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +            metric = metrics[i]
Looks line `enumerate`

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +            if not isinstance(metric, dict) and issubclass(metric, RefractorVelocityMetric):
If `issubclass(metric, RefractorVelocityMetric)` -> cast to dict. Then if not dict with proper keys -> raise

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +            metric_cls = metrics[i]['class']
Such inplace list updates during iteration over it is generally undesirable

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        metrics = REFRACTOR_VELOCITY_QC_METRICS if metrics is None else metrics
Single metric now can't be passed as a `RefractorVelocityMetric`

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        self._coords_to_index = coords_to_index
Why? Also, do you still need this block if you load gather using `get_gather` anyways?

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        metrics_maps = {}
Why not a list?

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +import torch
Remove all unused imports

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        gather = self.survey.get_gather(self.field._coords_to_index[coords])
Here you belive that the `survey` is indexed by coordinates columns, which may not be the case

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        if not refractor_velocity.is_fit:
It will never be fit after interpolation

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +    max_value = 3
These should be mathematically feasible min and max values. Lots of surveys have way larger amplitudes

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        gather = self.survey.get_gather(self.field._coords_to_index[coords]).scale_standard()
Don't like that you scale the gather here, but not in `calc`

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        angles = np.angle(phases)
You at least can call angle after advanced indexing to speed this up

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        ix = (times / gather.sample_rate).astype(np.int64)
Use `times_to_indices` from `utils` everywhere in code

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        mean_cols = np.linspace(ix - corr_window, ix + corr_window, num=corr_window * 2, dtype=np.int64).T
Why `linspace`?

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        corr_window = self.corr_window if hasattr(self, 'corr_window') else 10
`getattr(self, "corr_window", 10)`. But why?

2023-01-27 10:59 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +    def calc(gather, refractor_velocity, first_breaks_col=HDR_FIRST_BREAK, threshold_times=50,
Looks too complicated

2023-02-02 10:46 UTC, alexanderkuvaev requested changes

2023-02-02 10:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +            if not isinstance(metric, dict) and issubclass(metric, RefractorVelocityMetric):
if a metric is a subclass of a `RefractorVelocityMetric` it's definetely not a dict

2023-02-02 10:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +                                                    or isinstance(metric['kwargs'], dict)):
I'd omit `kwargs` key, just store all arguments as key-value pairs directly. This will simplify this code a bit

2023-02-02 10:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        if not np.all(coords_cols == to_list(survey.indexed_by)):
Why `np.all` if you compare lists?

2023-02-02 10:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        n_gathers = len(gather_coords)
I'd move this logic inside the loading loop: calculate gather coords via
```python
gather_coords = [gather.coords for gather in gathers_chunk]
```
To further call
```python
rvs_chunk = self(gather_coords)
```
This will:
1. Check that each gather has unique coords
2. Perform proper coords cast upon field call if needed

2023-02-02 10:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +                                             first_breaks_col=first_breaks_col, **metric_kwargs).mean()
Why `mean` here? Seems not so appropriate for some metrics like first break amplitudes

2023-02-02 10:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +    def calc(gather, refractor_velocity, first_breaks_col=HDR_FIRST_BREAK, corr_window=10):
Let's rename `corr_window` to `win_size` and measure it in ms, not samples of half-window. This will unify it with other methods.

2023-02-02 10:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        mean_cols = ix.reshape(-1, 1) + np.arange(-corr_window, corr_window).reshape(1, -1)
This may produce out of bounds errors

2023-02-02 10:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        corrs /= np.sqrt((traces_centered**2).sum(axis=1) * (mean_trace_centered**2).sum(axis=1))
Take a look at `Semblance` calculation or talk to @nikita-klsh, this may be simplified

2023-02-07 12:42 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        n_gathers = len(gather_coords)
I moved field call into loop, but `gather_coords` are futher needed to fill metric maps

2023-03-27 11:46 UTC, alexanderkuvaev requested changes

2023-03-27 11:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        g.scale_maxabs()
Do we need gather scaling here?

2023-03-27 11:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        res = g.data[range(len(ix)), ix]
I'd think of linear interpolation here, it's pretty easy to implement

2023-03-27 11:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        res = np.angle(phases).reshape(-1)
Shouldn't `np.unwrap` be also used here?

2023-03-27 11:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        phases = abs(self.calc(gather=gather, refractor_velocity=refractor_velocity))
Why `abs` here? Why python abs, not numpy?

2023-03-27 11:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        g.scale_maxabs(clip=True)
You perform two scalings: first `maxabs`, then `standard`. Remove this one with copy.

2023-03-27 11:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        mean_cols = ix + np.arange(-self.win_size // g.sample_rate, self.win_size // g.sample_rate).reshape(1, -1)
Then `win_size` is doubled real window size

2023-03-27 11:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        mean_trace_centered = (mean_trace - mean_trace.mean()).reshape(1, -1)
If you also divide both `mean_trace` and `mean_trace_centered` by their `std`, you can avoid further division of `corrs`

2023-03-27 11:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +    def __init__(self, name=None, first_breaks_col=HDR_FIRST_BREAK, threshold_times=50, correct_uphole=None):
`threshold_times` is used only by two metrics, I'd remove it from the base class

2023-03-27 11:46 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        outliers = np.abs(rv_times - times) > self.threshold_times
I'd try to move it to a base class, that will be used by both this metric and `FirstBreakOutliers`. `correct_uphole` should be probably moved to `__init__` only in this class then.

2023-03-30 09:50 UTC, anton-br commented on seismicpro/refractor_velocity/metrics.py
> +    def calc(self, *args, **kwargs):
why do you use args and kwargs here, if all metrics have the same args - gather and rv? Consider use them here and in call.

2023-03-30 09:50 UTC, anton-br commented on seismicpro/refractor_velocity/metrics.py
> +        ax.axvline(x=divergence_offset, color='k', linestyle='--')
consider adding this line to legend (if legend shows for rv)

2023-03-30 15:12 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +                gather_results.append(metric_val)
fixed

2023-03-30 15:12 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        """Perform quality control of the refractor velocity field and specifically its first breaks.
fixed

2023-03-30 15:15 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        * The first break outliers metric,
done

2023-03-30 15:16 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        * The divergence point metric for first breaks.
check

2023-03-30 15:20 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        metrics = REFRACTOR_VELOCITY_QC_METRICS if metrics is None else to_list(metrics)
fixed, thanks

2023-03-30 15:22 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +                                         rvs_chunk)
it does fit!

2023-03-30 16:32 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +                    chunk_coords = gather_coords[i * chunk_size : (i + 1) * chunk_size]
fixed

2023-03-30 16:33 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        gather_coords = survey[coords_cols][gather_change_ix]
done

2023-03-30 16:33 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        n_gathers = len(gather_coords)
ok

2023-03-30 16:42 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +                                .construct_map(coords=gather_coords, index=index, index_cols=index_cols,
done

2023-04-03 08:49 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    def __init__(self, name=None, first_breaks_col=HDR_FIRST_BREAK, threshold_times=50, correct_uphole=None):
done

2023-04-03 09:38 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        gather = self.survey.get_gather(index).copy()
potentially fixed

2023-04-03 09:39 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +                gather[self.name] = metric_values
added, thnx

2023-04-03 09:40 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +            refractor_velocity.times += gather["SourceUpholeTime"]
then self.correct_uphole will be False if user hasn't set it to True explicitly

2023-04-03 09:40 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    correct_uphole : bool, optional
None =)

2023-04-03 10:03 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    target : float in range (-pi, pi] or str from {'max', 'min', 'transition'}.
added

2023-04-03 10:17 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        res = g.data[range(len(ix)), ix]
done

2023-04-03 10:24 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        g.scale_maxabs(clip=True)
fixed

2023-04-03 10:26 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        mean_cols = ix + np.arange(-self.win_size // g.sample_rate, self.win_size // g.sample_rate).reshape(1, -1)
changed docs

2023-04-03 12:04 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        outliers = np.abs(rv_times - times) > self.threshold_times
`correct_uphole` is also needed in `plot_refractor_velocity` view

2023-04-03 12:14 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        ax.axvline(x=divergence_offset, color='k', linestyle='--')
not sure about the legend, added info into title

2023-04-12 11:12 UTC, alexanderkuvaev requested changes

2023-04-12 11:12 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +            self.correct_uphole = self.survey.is_uphole and self.field.is_uphole_corrected
`self.survey.is_uphole` may be `True` if only `SourceDepth` is loaded. You have to explicitly check for `SourceUpholeTime` here.

2023-04-12 11:12 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        refractor_velocity.max_offset = gather["offset"].max()
I'd memorize `max_offset` in `bind_context` as `survey["offset"].max()` and pass it directly to `refractor_velocity.plot`

2023-04-12 11:12 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +                                              else gather.survey.is_uphole and refractor_velocity.is_uphole_corrected)
Again, use `"SourceUpholeTime" in gather.available_headers`

2023-04-12 11:12 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +class FirstBreaksOutliers(RefractorVelocityMetric):
Seems like `FirstBreaksOutliers` should be removed from `gather.metrics` module. Otherwise they'll conflict in package `__init__`

2023-04-12 11:12 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +                                    q_min=0, q_max=1, tracewise=True, clip=True, eps=1e-10)
You don't need clip if you use 0 and 1 quantiles

2023-04-12 11:12 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        res = np.empty_like(ix, dtype=np.float32)
```suggestion
        res = np.empty_like(ix, dtype=gather_data.dtype)
```

2023-04-12 11:12 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        ix = gather_times / sample_rate
Check for out of bounds errors

2023-04-12 11:12 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +    win_size : int, optional, defaults to 40
It's now `window_size`

2023-04-17 11:08 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +        return quantiles
1. actually `get_quantile` won't fail since I use `q.size` which is 1 for `ndim==0` case. so the docstring is lying about 1d =)
2. agree with that

2023-04-17 12:45 UTC, AnnaAltynova commented on seismicpro/batch.py
> +    def evaluate_field(self, field, src, dst):
done

2023-04-17 12:49 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +            std = np.asarray(self.survey.std).reshape(1, 1)
fine with me

2023-04-17 12:55 UTC, AnnaAltynova commented on seismicpro/gather/utils/normalization.py
> +            std = np.sqrt(np.sum(((data - mean.reshape(-1, 1)) ** 2) / trace_len, axis=1)).reshape(-1, 1)
thanks

2023-04-17 13:01 UTC, AnnaAltynova commented on seismicpro/gather/utils/normalization.py
> +        min_value, max_value = quantiles[0, 0], quantiles[0, 1]
sorry, my bad

2023-04-18 11:46 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +            self.correct_uphole = self.survey.is_uphole and self.field.is_uphole_corrected
thanks

2023-04-18 11:47 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +            gather = gather.copy().sort(by=sort_by)
not really

2023-04-18 11:49 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        refractor_velocity.max_offset = gather["offset"].max()
done

2023-04-18 11:51 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +                                              else gather.survey.is_uphole and refractor_velocity.is_uphole_corrected)
check

2023-04-18 11:51 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +                                    q_min=0, q_max=1, tracewise=True, clip=True, eps=1e-10)
ok

2023-04-18 12:05 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        ix = gather_times / sample_rate
done

2023-04-18 12:06 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        res = np.empty_like(ix, dtype=np.float32)
gotcha

2023-04-18 12:07 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    win_size : int, optional, defaults to 40
it is

2023-04-18 12:14 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        """Perform quality control of the refractor velocity field and specifically first breaks.
like it, thanks

2023-04-18 13:42 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        metrics : RefractorVelocityMetric or list of RefractorVelocityMetric, optional
done

2023-04-18 13:44 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +                                              values=metric_values) for metric, metric_values in zip(metrics_instances, zip(*results))]
nope

2023-04-20 14:13 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +    def qc(self, survey=None, metrics=None, bar=True, chunk_size=250, n_workers=None):
done

2023-04-26 14:32 UTC, alexanderkuvaev requested changes

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +            self.correct_uphole = ("SourceUpholeTime" in self.survey.available_headers
Why do you expect `survey` to be undefined? In this case this line will fail

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        self, coords, ax, index, sort_by=None, mask=True, top_header=True, **kwargs):
```suggestion
    def plot_gather(self, coords, ax, index, sort_by=None, mask=True, top_header=True, **kwargs):
```

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        and mark trases with metric greater than threshold. Threshold is either aquired from `kwargs` if given,
```suggestion
        and mark traces with metric greater than threshold. Threshold is either aquired from `kwargs` if given,
```

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +            refractor_velocity.times += gather["SourceUpholeTime"]
This may update gather headers, I'd force a copy to make it safe
```suggestion
            refractor_velocity.times = refractor_velocity.times + gather["SourceUpholeTime"]
```

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +    views = ("plot_gather", "plot_refractor_velocity")
Looks like you also have to redefine `get_views` to properly pass plot args such as `sort_by`

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +            coords, ax, index, threshold_times=threshold_times, **kwargs)
```suggestion
        return super().plot_refractor_velocity(coords, ax, index, threshold_times=threshold_times, **kwargs)
```

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        res = self._calc(gather.data.copy(), gather[first_breaks_col], gather.sample_rate)
```suggestion
        res = self._calc(gather.data, gather[first_breaks_col], gather.sample_interval)
```
And let's move `copy` inside the method

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        ix = gather_times / sample_rate
```suggestion
        ix = (picking_times - start_time) / sample_interval
```
`start_time` is `gather.times[0]`

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +            raise IndexError("First breaks are out of bounds")
Not sure if raising an error is ok here, maybe clip?

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        Target phase value in the moment of first break, see `np.angle`.
How is `np.angle` supposed to help me?

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        ix = (gather[first_breaks_col] / gather.sample_rate).astype(np.int64)
```suggestion
        ix = (gather[first_breaks_col] - gather.times[0]) // gather.sample_interval
```

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +            raise IndexError("First breaks are out of bounds")
Same as above

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +            gather = gather.copy().sort(by=sort_by)
Do you need this copy?

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        res = self._calc(gather[first_breaks_col], gather.data, self.window_size, gather.sample_rate)
```suggestion
        res = self._calc(gather[first_breaks_col], gather.data, self.window_size, gather.sample_interval)
```

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        ix = (times / sample_rate).astype(np.int64).reshape(-1, 1)
```suggestion
        ix = ((times - start_time) // sample_interval).reshape(-1, 1)
```

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        mean_cols = ix + np.arange(-window_size // sample_rate, window_size // sample_rate).reshape(1, -1)
```suggestion
        mean_cols = ix + np.arange(-window_size // (2 * sample_interval), window_size // (2 * sample_interval)).reshape(1, -1)
```

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        mean_hodograph = traces_windows.mean(axis=0)
Move this code of window generation to a separate fuction: it's called twice

2023-04-26 14:32 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        div_idx = split_idxs[np.argmax(outliers_fractions) - 1]
Discussed in person that this implementation may behave strangely, think of it

2023-04-27 14:17 UTC, AnnaAltynova commented on seismicpro/batch.py
> +        Parameters
oops

2023-04-27 14:18 UTC, AnnaAltynova commented on seismicpro/batch.py
> +        src : str
done

2023-04-27 14:20 UTC, AnnaAltynova commented on seismicpro/batch.py
> +            The batch unchanged.
thanks

2023-04-27 14:23 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +        if q.size == 1:
fixed, thanks

2023-04-27 14:26 UTC, AnnaAltynova commented on seismicpro/gather/utils/normalization.py
> +    """Compute the `q`-th quantile of the data along the axis.
depending on `tracewise` -)
removed these words

2023-04-27 14:52 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +            raise IndexError("First breaks are out of bounds")
fixed

2023-04-27 14:57 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        Target phase value in the moment of first break, see `np.angle`.
fixed

2023-04-27 14:58 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +            gather = gather.copy().sort(by=sort_by)
not really =)

2023-04-27 16:08 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        mean_hodograph = traces_windows.mean(axis=0)
done

2023-05-02 10:32 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        div_idx = split_idxs[np.argmax(outliers_fractions) - 1]
changed logic so that metric looks for the largest diff in outliers between windows

2023-05-02 10:32 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        index = None if coords_cols == index_cols else survey.indices
ok

2023-05-02 12:06 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    views = ("plot_gather", "plot_refractor_velocity")
done

2023-05-16 13:42 UTC, anton-br commented on seismicpro/refractor_velocity/metrics.py
> +        ax.axvline(x=divergence_offset, color="k", linestyle="--")
can we add this line to legend?

2023-05-17 16:41 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +        q : float or np.ndarray of floats
good point, thx

2023-05-17 16:47 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +            quantiles = quantiles[0]
why not?

2023-05-18 10:12 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
>      def get_quantile(self, q, tracewise=False, use_global=False):
moved `tracewise=False` cases to `Gather` lvl of computation. thanks!

2023-05-18 10:13 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        metrics : instance or subclass of RefractorVelocityMetric of list of them, optional.
thanks

2023-05-18 10:15 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +            Defaults to those defined in `~metrics.REFRACTOR_VELOCITY_QC_METRICS`.
added

2023-05-18 10:16 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +                raise ValueError("Survey must be passed if the field is not linked with a survey.")
thnx

2023-05-18 10:16 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        # index = None if coords_cols == index_cols else survey.indices
done

2023-05-18 10:18 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +from ..metrics import Metric
it's different utils

2023-05-18 10:18 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        and mark traces with metric greater than threshold. Threshold is either aquired from `kwargs` if given,
thanks

2023-05-18 10:19 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    threshold_times: float, optional, defaults to 50.
good question... next question!

2023-05-18 10:21 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        Parameters
I'm not sure if it needs to be written

2023-05-18 10:22 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +            # warnings.warn("First breaks are out of bounds", RuntimeWarning)
ok

2023-05-18 10:22 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +            ix = np.clip(ix, 0, gather_data.shape[1] - 1)
makes sence

2023-05-18 10:23 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    def __init__(self, target="max", **kwargs):
to stimulate users to read parent` kwargs =)))

2023-05-18 10:25 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        first_breaks_col : str, optional, defaults to :const:`~const.HDR_FIRST_BREAK`
thnx

2023-05-18 10:27 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        kwargs["top_header"] = signed_deltas if top_header else None
done

2023-05-18 10:28 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +                         gather.sample_interval, gather.times[0])
done

2023-05-18 10:29 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    def _make_windows(times, data, window_size, sample_interval, start_time):
didn't get the point, they have different kwargs

2023-05-18 10:30 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        traces_windows = np.empty((n_traces, trace_len), dtype=np.float32)
it's used twice

2023-05-18 10:32 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    vmin = 0
since we want to see any negative correlation as red

2023-05-18 10:32 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        ax.set_yticks(ticks=np.arange(self.window_size)[::5],labels=np.arange(self.window_size)[::5])
thx

2023-05-18 10:33 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        ax.axvline(x=divergence_offset, color="k", linestyle="--")
unfortunately we cannot

2023-05-18 11:26 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        By default, the following metrics are calculated:
added

2023-05-18 11:39 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        ax.axvline(x=divergence_offset, color="k", linestyle="--")
added

2023-05-18 15:51 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    def plot_gather(self, coords, ax, index, sort_by=None, mask=True, top_header=True, **kwargs):
done

2023-05-18 15:51 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    def plot_mean_hodograph(self, coords, ax, index, **kwargs):
added

2023-05-18 15:55 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        and mark traces with metric greater than threshold. Threshold is either aquired from `kwargs` if given,
corrected

2023-05-18 16:08 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        plot_on_click_kwargs[0].update(gather_plot_kwargs)
reversed updates order

2023-05-19 10:52 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        """Return plotters of the metric views and add kwargs for `gather_plot` to an interactive map plotter."""
ok

2023-05-19 10:54 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        gather_plot_kwargs = {kwarg: kwargs.pop(kwarg) for kwarg in ["sort_by", "mask", "top_header"]
discussed in person that only `sort_by` and `threshold` should be left outside `plot_on_click_kwargs`

2023-05-19 10:54 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +                mask_kwargs.update({"masks": metric_values * invert_mask,
ok

2023-05-19 13:35 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +            Column name from `survey.headers` where times of first break are stored.
thanks

2023-05-19 13:37 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    """Mean amplitude of the signal in the moment of first break after maxabs scaling."""
yep, but should we repeat class name in the description?

2023-05-19 13:38 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        res = self._calc(gather.data, gather[first_breaks_col], gather.sample_interval, gather.times[0])
thnx

2023-05-19 13:38 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        return res
done

2023-05-19 13:40 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        mean_cols = np.clip(mean_cols, 0, data.shape[1] - 1).astype(np.int64)
fixed

2023-05-19 13:47 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +REFRACTOR_VELOCITY_QC_METRICS = [FirstBreaksOutliers, FirstBreaksAmplitudes, FirstBreaksPhases,
done

2023-05-19 13:48 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +REFRACTOR_VELOCITY_QC_METRICS = [FirstBreaksOutliers, FirstBreaksAmplitudes, FirstBreaksPhases,
done

2023-05-19 13:49 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        traces_windows_centered = (traces_windows - mean_amplitudes) / std_amplitudes
fixed

2023-05-19 13:49 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +            std_amplitudes[i] = np.sqrt((np.sum((traces_windows[i] - mean_amplitudes[i])**2) / trace_len))
fixed

2023-05-19 13:51 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        mean_hodograph = np.empty((1, trace_len), dtype=traces_windows.dtype)
we need to broadcast in `corrs`

2023-05-19 13:52 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        g.scale_maxabs(clip=True)
ok

2023-05-19 13:56 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        mean_hodograph = traces_windows.mean(axis=0)
it'll be jnitted method with three lines, do we want it?

2023-05-19 13:56 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        ax.set_yticks(ticks=np.arange(self.window_size)[::5],labels=np.arange(self.window_size)[::5])
fixed

2023-05-19 14:16 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        return np.sort(gather['offset'])[diverged_outliers.argmax()]
fixed logic

2023-05-19 14:16 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        gather.plot(event_headers=event_headers, ax=ax, masks=masks, top_header=top_header, **kwargs)
changed

2023-05-19 14:34 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +class DivergencePoint(RefractorVelocityMetric):
added tolerance parameter

2023-05-19 15:48 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        metrics_instances = [metric.provide_context(**context) for metric in metrics_instances]
created `set_defaults` func

2023-05-19 16:17 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        return traces_windows
done

2023-05-22 16:27 UTC, alexanderkuvaev requested changes

2023-05-22 16:27 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +    def plot_gather(self, coords, ax, index, sort_by=None, threshold=None, mask=True, top_header=True, **kwargs):
If `calc` returns absolute differences this method can be removed completely

2023-05-22 16:27 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +            mean_hodograph[:, i] = np.sum(traces_windows[:, i]) / (n_traces)
Just `mean`

2023-05-22 16:27 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +            corrs[i] = np.sum(traces_windows_scaled[i] * mean_hodograph_scaled) / n_samples
Again `mean`

2023-05-22 16:27 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +            std_amplitudes[i] = np.std(traces_windows[i])
Probably scaling amplitudes inside the loop will be faster

2023-05-22 16:27 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +            res[:, i] = get_hodograph(data, offsets, times + dt, sample_interval, fill_value=np.nan, interpolate=True)
1. the signature has changed, fix on your side
2. You can obtain nans here, and you use `mean` and `std` in `calc`. Either change them to nan- analogues, or change the default value here.

2023-05-22 16:27 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        for i, dt in enumerate(range(-window_size // 2, ceil(window_size / 2), sample_interval)):
Avoid possible floating step in range, iterate as `for i in range(n_samples)` and calculate `dt` by `i`

2023-05-22 16:27 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        gather.scale_maxabs(clip=True)
Why does it appear here, but not in `calc`?

2023-05-22 16:27 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        if np.mean(outliers) < self.tol or self.step >= len(offsets) - len(offsets) % self.step:
Don't get the second check: you compare samples with meters

2023-05-22 16:27 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        outliers = np.abs(rv_times - times) > threshold_times
Outliers are already calculated

2023-05-22 16:27 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        split_idxs = np.arange(step, len(offsets) - len(offsets) % step, step)
samples - meters again

2023-05-25 09:45 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +        if q.ndim == 0:
fixed

2023-05-25 10:04 UTC, AnnaAltynova commented on seismicpro/gather/utils/normalization.py
> +        for i in range(n_traces):
checked, it is not

2023-05-25 10:09 UTC, AnnaAltynova commented on seismicpro/gather/utils/normalization.py
> +            std[i] = np.sqrt((np.sum((data[i] - mean[i])**2) / trace_len))
done

2023-05-25 10:24 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        """Process metric evaluation context."""
done

2023-05-25 11:03 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    def __init__(self, threshold_times=50, **kwargs):
fixed

2023-05-25 11:25 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        return get_hodograph(gather_data, offsets, picking_times, sample_interval, interpolate=True, fill_value=0)
synched, thanks

2023-05-25 13:40 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    def plot_gather(self, coords, ax, index, sort_by=None, threshold=None, mask=True, top_header=True, **kwargs):
added `binarize` method to calc masks

2023-05-25 13:45 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        for i, dt in enumerate(range(-window_size // 2, ceil(window_size / 2), sample_interval)):
fixed

2023-05-25 13:50 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +            res[:, i] = get_hodograph(data, offsets, times + dt, sample_interval, fill_value=np.nan, interpolate=True)
fixed

2023-05-25 13:50 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +            mean_hodograph[:, i] = np.sum(traces_windows[:, i]) / (n_traces)
thanks

2023-05-25 13:52 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +            std_amplitudes[i] = np.std(traces_windows[i])
done

2023-05-25 13:53 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +            corrs[i] = np.sum(traces_windows_scaled[i] * mean_hodograph_scaled) / n_samples
thanks

2023-05-25 14:51 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        gather.scale_maxabs(clip=True)
shouldn't be here too, thanks

2023-05-25 14:53 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        outliers = np.abs(rv_times - times) > threshold_times
agree

2023-05-26 10:04 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        if np.mean(outliers) < self.tol or self.step >= len(offsets) - len(offsets) % self.step:
fixed

2023-05-26 10:04 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    def plot_gather(self, coords, ax, index, sort_by=None, threshold=None, mask=True, top_header=False, **kwargs):
fixed

2023-05-26 10:05 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +    def _calc_metrics(metrics, survey, field, gather_indices_chunk, coords_chunk):
done

2023-05-27 10:04 UTC, alexanderkuvaev requested changes

2023-05-29 10:15 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +            std = np.atleast_2d(np.array(self.survey.std))
fixed

2023-05-29 10:17 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +            If not provided, must be set before the metric call via `set_defaults`.
fixed

2023-05-29 10:21 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    vmax = 0.5
removed

2023-05-29 10:51 UTC, AnnaAltynova commented on seismicpro/batch.py
> +        dst : src
fixed

2023-05-29 11:14 UTC, alexanderkuvaev reviewed
Now it's time to rebenchmark everything

2023-05-29 11:14 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        gather.data = traces_windows
Not sure, but some further methods may fail since `data` and `samples` are not synchronized now. I'd create a new `Gather` instance here.

2023-05-29 19:37 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        gather.data = traces_windows
creating a new `gather` implies importing `Gather` in `metrics.py`, but this results in circular imports.
recalculated samples in existing gather instead.

2023-06-01 09:56 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    def __call__(self, gather, refractor_velocity):
since we want signed deviance from target to be displayed in `top_header`

2023-06-01 13:06 UTC, anton-br commented on seismicpro/refractor_velocity/metrics.py
> +    Default views are `plot_gather` and `plot_refracted_velocity`.
```suggestion
    Default views are `plot_gather` and `plot_refractor_velocity`. 
```

2023-06-01 13:06 UTC, anton-br commented on seismicpro/refractor_velocity/metrics.py
> +    `plot_gather` is parametrized for plotting metric values on top and above the gather plot.
what about describe `plot_refractor_velocity`?

2023-06-09 09:31 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        metrics : instance or subclass of :class:`~metrics.RefractorVelocityMetric` of list of them, optional.
thanks

2023-06-09 11:19 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +
done

2023-06-09 11:24 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +            quantiles = normalization.get_quantile(self.data, q=np.atleast_1d(q))
done

2023-06-09 11:24 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +        # Use np.atleast_2d(array).T to make the array 2-dimensional by adding dummy trailing axes
thanks

2023-06-09 11:25 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +            min_value, max_value = normalization.get_quantile(self.data,[q_min, q_max])
thanks

2023-06-09 11:28 UTC, AnnaAltynova commented on seismicpro/gather/utils/normalization.py
> +def get_gather_stats(data):
renamed to `get_stats`

2023-06-09 11:31 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        threshold : int or float, optional, defaults to None
thanks

2023-06-09 12:10 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    def get_views(self, sort_by=None, threshold=None, **kwargs):
ok

2023-06-09 12:10 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        split_idxs = np.unique(np.searchsorted(sorted_offsets,
I'm afraid to touch it

2023-06-09 12:11 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    Default views are `plot_gather` and `plot_refracted_velocity`.
thanks

2023-06-09 12:14 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    `plot_gather` is parametrized for plotting metric values on top and above the gather plot.
added reference to `RV.plot`

2023-06-22 15:42 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +            min_value, max_value = normalization.get_tracewise_quantile(self.data, [q_min, q_max])
good point, thanks

2023-06-22 15:45 UTC, AnnaAltynova commented on seismicpro/gather/utils/normalization.py
> +    values = np.empty((n_quantiles, n_traces), dtype=np.float64)
since we want to preserve `(n_traces, n_quantiles)` return shape as it was previously

2023-06-23 10:43 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        return get_hodograph(gather_data, offsets, sample_interval, delay, picking_times, fill_value=0)
fixed

2023-06-23 10:45 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    window_size : int
thanks

2023-06-23 10:46 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    name = "first_breaks_outliers"
removed

2023-06-23 10:58 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        n_samples = ceil(self.window_size / gather.sample_interval)
done

2023-06-23 11:01 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        fb_angles = np.arctan2(hilbert, windows[:, half_n_samples])
ok

2023-06-23 11:04 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    window_size : int
done

2023-06-23 11:08 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        data = scale_standard(gather.data, mean, std, 1e-10)
yes, where abs value of the fb amplitude is small (e.g. on faraway offsets) phase isn't distinct enough for this algorithm to catch

2023-06-23 11:13 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        gather.plot(mode="wiggle", ax=ax, **kwargs)
the it'll be updated to `mode` from `kwargs` during unpacking

2023-06-23 11:19 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        set_ticks(ax, axis="y", label="Time, ms", num=num_y_ticks,
removed x label, but y here is with bounds different from `plot_gather_window`

2023-06-23 11:37 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +        is_geographic = tuple(coords_cols) in GEOGRAPHIC_COORDS
seems like they are

2023-06-23 11:51 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +            hilbert[i] = np.dot(windows[i], filt[::-1])
done, thanks

2023-06-29 11:19 UTC, alexanderkuvaev approved these changes

2023-06-29 11:19 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +    def _calc(gather_data, offsets, picking_times, sample_interval, delay):
Please match the order of arguments as in `get_hodograph`

2023-06-29 11:19 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        data = scale_standard(gather.data, mean, std, 1e-10)
Very strange, you divide a convolved signal sample by an original sample to get an amplitude. This should be invariant to scaling. Mean subtraction may affect, but the trace is generally centered around 0, and you use the whole trace stats, not the window ones.

Please, double-check.

2023-06-29 11:19 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        return np.ascontiguousarray(filt[::-1])
It has `float64` dtype here, probably you want `float32`

2023-06-29 11:19 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        gather.data = traces_windows
New gather attributes may be added here and we'll definitely forget to fix it here. Circular import is ok.

2023-06-29 11:19 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +class DivergencePoint(RefractorVelocityMetric):
I'd remove it from the PR if its not fixed

2023-07-06 14:16 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        Parameters
done

2023-07-06 15:02 UTC, AnnaAltynova commented on seismicpro/gather/utils/normalization.py
> +    """ Calculate mean and standard deviation.
fixed

2023-07-06 15:03 UTC, AnnaAltynova commented on seismicpro/gather/utils/normalization.py
> +    max_value += eps
ok

2023-07-06 15:09 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +    def _calc(gather_data, offsets, picking_times, sample_interval, delay):
sure

2023-07-06 15:12 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        return np.ascontiguousarray(filt[::-1])
thanks

2023-07-06 15:36 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        gather.data = traces_windows
didn't get your point, `Gather` imports `rvf`, `rvf` imports `rv.metrics`, `rv.metrics` imports `Gather`, that causes an `ImportError`, how is that ok?

2023-07-06 16:14 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        data = scale_standard(gather.data, mean, std, 1e-10)
removing scaling from calc I get this:
![image](https://github.com/gazprom-neft/SeismicPro/assets/92299943/54610976-9339-41d3-8629-3af94ab293bc)

2023-07-10 09:48 UTC, alexanderkuvaev commented on seismicpro/refractor_velocity/metrics.py
> +        data = scale_standard(gather.data, mean, std, 1e-10)
And thats ok if mean trace amplitude differs from 0. I'd remove scaling or at least make trace centering explicit.

2023-07-27 14:27 UTC, nikita-klsh approved these changes

2023-07-28 15:04 UTC, anton-br approved these changes

2023-08-01 13:27 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/refractor_velocity_field.py
> +
ok

2023-08-01 13:30 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +        metric.fill(div_offset)
thanks

2023-08-01 13:36 UTC, AnnaAltynova commented on seismicpro/refractor_velocity/metrics.py
> +                                     n_samples, gather.sample_interval, gather.delay)
`n_samples` is also needed here in line 321

2023-08-11 10:28 UTC, merged