Add mask to gather plot
gazprom-neft/SeismicPro pull request #125
Opened 2023-01-27 13:37 UTC by anton-br

This pull request provided a new parameter for gather plot - `mask`. It is a 2d array that will be placed above the main plot. 

Moreover, I've moved constant `EPS=1e-10` that was used in normalization methods to `const.py`.

Usage example:
```
gather = survey.sample_gather()
mask = np.zeros(gather.shape)
mask[100: 200, 100: 200] = 1
gather.plot(mask=mask)
```
![image](https://user-images.githubusercontent.com/19351782/215099451-f0a84df4-c99e-40bd-9766-ab1bd2a0a905.png)

or
```
gather.plot(mode='wiggle', mask=mask)
```
![image](https://user-images.githubusercontent.com/19351782/215099393-68bd1293-52b1-4d9e-b5e4-5213ef6a676c.png)

2023-02-02 16:06 UTC, alexanderkuvaev requested changes

2023-02-06 09:24 UTC, anton-br commented on seismicpro/gather/gather.py
> +            img = ax.imshow(mask.T, **kwargs)
Yes does, but I would still prefer to move it above anyway, seems better to have `add_colorbar` and `_finalize_plot` at the end of plot function.

2023-02-06 09:24 UTC, anton-br commented on seismicpro/gather/gather.py
> +            kwargs.update({"mask": mask})
thx

2023-02-06 09:25 UTC, anton-br commented on seismicpro/gather/gather.py
> +                               (np.diff(ixs[:, 1], prepend=ixs[0, 1]) != 1)).ravel()
done

2023-02-06 09:25 UTC, anton-br commented on seismicpro/gather/gather.py
> +            verts = np.zeros((len(start_ix)*5, 2))
deleted

2023-02-06 10:15 UTC, anton-br commented on seismicpro/gather/gather.py
> +        or `wiggle` mode via `mask` parameter. Any values greater than 0.5 are trated as a mask and will be plotted in
done

2023-02-06 10:16 UTC, anton-br commented on seismicpro/gather/gather.py
> +        Any positive definite array matching the size of the gather can be drawn above the main plot in `seismogram`
rewrote

2023-02-06 10:16 UTC, anton-br commented on seismicpro/gather/gather.py
> +        red with small transparancy. Note that `mask` works only with `seismogram` and `wiggle` mods.
fixed

2023-02-06 10:17 UTC, anton-br commented on seismicpro/gather/gather.py
> +        mask : 2d array with same shape as self.shape or 1d array with length == self.n_traces or Gather, optional,
added

2023-02-06 10:18 UTC, anton-br commented on seismicpro/gather/gather.py
> +            """Returns two arrays with indexes of the beginning and end of continuous subsequences in the array"""
done

2023-02-06 10:42 UTC, anton-br commented on seismicpro/gather/gather.py
> +            verts = np.insert(verts, np.arange(len(verts), step=4)+4, [0, 0], axis=0)
done

2023-02-06 10:44 UTC, anton-br commented on seismicpro/gather/gather.py
> +            down_verts = mask_ix[end_ix].reshape(-1, 1, 2) + np.array([[0.5, -0.5], [-0.5, -0.5]])
let's listen to the others opinions and discuss :)

2023-02-06 15:34 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +            mask = np.array(mask)
now, if `mask` is int for example, we get strange behavior. Maybe we should process such cases meaningfully or just add type-shape check?

2023-02-06 15:36 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +            kwargs["mask"] = np.broadcast_to(np.where(mask < 0.5, np.nan, mask), self.shape)
if we have a header with some tracewise metric, it woud be nice to set threshold for mask here(instead of 0.5)

2023-02-06 15:39 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +            mask_patch = PathPatch(Path(verts, codes), color='r', lw=0, alpha=alpha*0.6)
can we configure mask color and transparency with kwargs?

2023-02-06 15:43 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +            down_verts = mask_ix[end_ix].reshape(-1, 1, 2) + np.array([[0.5, -0.5], [-0.5, -0.5]])
will we not get a significant overlap between masks basing indents on amps? I'm cool with constant mask width as it is now.

2023-02-07 12:57 UTC, nikita-klsh commented on seismicpro/gather/gather.py
> +            img = ax.imshow(mask.T, **kwargs)
You may miss starting and final samples
```
gather = gather[:, -50:]
gather.plot(mask=np.ones_like(gather.data), mode='wiggle')
```
![image](https://user-images.githubusercontent.com/8656643/217250909-926312a3-76cf-4d7e-a4b7-ad7c92802d3e.png)

2023-02-08 12:37 UTC, anton-br commented on seismicpro/gather/gather.py
> +            mask = np.array(mask)
it will still works if you pass mask=1, don't get the question

2023-02-08 12:38 UTC, anton-br commented on seismicpro/gather/gather.py
> +            kwargs["mask"] = np.broadcast_to(np.where(mask < 0.5, np.nan, mask), self.shape)
added

2023-02-08 12:38 UTC, anton-br commented on seismicpro/gather/gather.py
> +            mask_patch = PathPatch(Path(verts, codes), color='r', lw=0, alpha=alpha*0.6)
added

2023-02-08 12:39 UTC, anton-br commented on seismicpro/gather/gather.py
> +            img = ax.imshow(mask.T, **kwargs)
added

2023-02-08 12:39 UTC, anton-br commented on seismicpro/gather/gather.py
> +            img = ax.imshow(mask.T, **kwargs)
1. Rewritten kwargs logic
2. yeah, thanks, it was wrong polygons creation

2023-02-08 12:48 UTC, anton-br commented on seismicpro/gather/gather.py
> +            If `str`, a header name to take mask from.
extend docs

2023-02-08 12:48 UTC, anton-br commented on seismicpro/gather/gather.py
> +        mask : 2d array with same shape as self.shape or 1d array with length == self.n_traces or Gather or str,
added

2023-02-08 14:23 UTC, alexanderkuvaev requested changes

2023-02-08 14:23 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +        than 0.5 are treated as a mask and will be plotted in red with small transparency.
Its defined by `threshold` now

2023-02-08 14:23 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +    def plot(self, mode="seismogram", mask=None, *, threshold=0.5, title=None, x_ticker=None, y_ticker=None, ax=None,
Now masking logic becomes overcomplicated:
1. Some of the `kwargs` suddenly appear in concrete plotting methods and not described in the main docs (such as `mask_alpha` and `mask_cmap`)
2. Some of them can be passed to one plotting mode, but not in another (`mask_cmap` - `mask_color`)
3. Some custom threshold logic is performed using a parameter, which is passed separately from `mask`. Other parameters use dict-like notation to group related args.

The main question is: does anyone really want to use all this?

2023-02-10 12:54 UTC, alexanderkuvaev requested changes

2023-02-10 12:54 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +    def plot(self, mode="seismogram", mask=None, *, title=None, x_ticker=None, y_ticker=None, ax=None, **kwargs):
Probably `maskS` to match `event_headerS`. And I'd make it keyword-only.
```suggestion
    def plot(self, mode="seismogram", *, masks=None, title=None, x_ticker=None, y_ticker=None, ax=None, **kwargs):
```

2023-02-10 12:54 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +
```suggestion
        Some areas of a gather may be highlighted in color by passing optional `masks` argument.
```
And join it to the next paragraph. No need to describe available options here, you do it below.

2023-02-10 12:54 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +                - `alpha`: mask transparency.
Let's add `label` here

2023-02-10 12:54 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +                if label is not None:
Please add a comment that it's only to be visible on the legend

2023-02-10 12:54 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +                kwargs = {"alpha": alpha*0.6, "color": "r", "lw": 0}
Let's call it `default_mask_kwargs` to match the name in `_plot_seismogram`

2023-02-10 12:54 UTC, alexanderkuvaev commented on seismicpro/batch.py
> +                        unpacked_args[arg_name] = getattr(self, arg_val)[i] if hasattr(self, arg_val) else arg_val
It won't work if `masks` were passed as a `dict` with `masks` key

2023-02-10 16:57 UTC, anton-br commented on seismicpro/gather/gather.py
> +    def plot(self, mode="seismogram", mask=None, *, title=None, x_ticker=None, y_ticker=None, ax=None, **kwargs):
done

2023-02-10 16:57 UTC, anton-br commented on seismicpro/gather/gather.py
> +
done

2023-02-10 16:59 UTC, anton-br commented on seismicpro/gather/gather.py
> +                kwargs = {"alpha": alpha*0.6, "color": "r", "lw": 0}
renamed

2023-02-13 09:59 UTC, alexanderkuvaev requested changes

2023-02-13 14:31 UTC, anton-br commented on seismicpro/gather/gather.py
> +            kwargs.update({"masks": self._process_masks(masks)})
moved `_process_masks` into `_plot_seismogram` and `_plot_wiggle`

2023-02-13 14:31 UTC, anton-br commented on seismicpro/batch.py
> +                        unpacked_args[arg_name] = getattr(self, arg_val)[i] if hasattr(self, arg_val) else arg_val
added the case

2023-02-13 14:32 UTC, anton-br commented on seismicpro/gather/gather.py
> +                if label is not None:
added

2023-02-14 13:39 UTC, anton-br commented on seismicpro/batch.py
> +        """Replace all names of batch attributes in `args` with batch attributes itself. """
done

2023-02-14 13:39 UTC, anton-br commented on seismicpro/batch.py
> +                    if isinstance(arg_val, dict):
added

2023-02-15 09:06 UTC, alexanderkuvaev approved these changes

2023-02-16 12:28 UTC, nikita-klsh commented on seismicpro/gather/gather.py
> +                    continue
If this is empty mask check, consider
```suggestion
                if np.isnan(mask).all():
                    continue
```
Works properly in case `mask = [-1, np.nan, 1]`

2023-02-16 12:28 UTC, nikita-klsh commented on seismicpro/gather/gather.py
> +                cmap = ListedColormap(mask_kwargs.pop("color"))
Would be nice in case `gather.plot(masks={'masks': [mask1, mask2]})` sample different colors for mask1 and mask2, like its done in `event_headers`. 

Also would be nice to infer legends labels from headers names. So the final usecase could be like
```
survey.qc()
survey.sample_gather().plot(masks={"masks": ["spikes", "dead", "cliplen", ....]}
```

2023-02-16 12:28 UTC, nikita-klsh commented on seismicpro/gather/gather.py
> +                    ax.add_patch(Polygon([[0, 0]], color=cmap(1), label=label, alpha=mask_kwargs["alpha"]))
Please add comment that this fake artist exists only for legend
```suggestion
                if label is not None:
                    # Invisible artist not being plotted. Serves as the legend handler for ax.imshow bellow
                    ax.add_patch(Polygon([[0, 0]], color=cmap(1), label=label, alpha=mask_kwargs["alpha"]))
```

2023-02-16 12:38 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +                    continue
@anton-br If you deside fixing this consider also moving this if to `_process_masks`

2023-02-16 16:24 UTC, anton-br commented on seismicpro/gather/gather.py
> +                cmap = ListedColormap(mask_kwargs.pop("color"))
added

2023-02-16 16:34 UTC, alexanderkuvaev requested changes

2023-02-16 16:34 UTC, alexanderkuvaev commented on seismicpro/batch.py
> +        """Replace all names of batch components in `args` with corresponding batch items. """
```suggestion
        """Replace all names of batch components in `args` with corresponding values from `batch_item`. """
```
Just to clarify after renaming `batch_item`

2023-02-16 16:34 UTC, alexanderkuvaev commented on seismicpro/batch.py
> +    def _unpack_args(batch_item, args):
```suggestion
    def _unpack_args(args, batch_item):
```
More clear as for me

2023-02-16 16:34 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +                # Note that the label will only be visible on the legend
I'd remove this comment, the new one below looks better

2023-02-16 16:34 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +                # Invisible artist is not being plotted. Serves as the legend handler for ax.imshow bellow.
```suggestion
                # Add an invisible artist to display mask label on the legend since imshow does not support it
```

2023-02-16 16:34 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +        for ix, mask_dict in enumerate(masks_list):
```suggestion
        for ix, (mask_dict, default_color) in enumerate(zip(masks_list, colors_iterator)):
```
And remove next below

2023-02-16 16:34 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +            mask_dict["label"] = mask_dict.get("label", f"mask_{ix+1}")
```suggestion
            mask_dict["label"] = mask_dict.get("label", f"Mask {ix+1}")
```
It will only be on a legend, I'd make it more human-readable

2023-02-16 16:34 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +            mask_dict["color"] = mask_dict.get("color", next(colors_iterator))
```suggestion
            mask_dict["color"] = mask_dict.get("color", default_color)
```

2023-02-16 16:34 UTC, alexanderkuvaev commented on seismicpro/gather/gather.py
> +            yield mask_dict
```suggestion
        return [mask_dict for mask_dict in masks_list if not np.isnan(mask_dict["masks"]).all()]
```
Not sure if I'd like this method to be a generator

2023-02-16 16:58 UTC, alexanderkuvaev approved these changes

2023-02-16 17:12 UTC, merged