Tracewise qc
gazprom-neft/SeismicPro pull request #130
Opened 2023-03-09 16:21 UTC by anton-br

* Introduce tracewise QC metrics,
* Add methods to compute them from Survey - `qc_tracewise` and create metric map for each computed metric `construct_qc_maps`,
* Since `dead_trace` is one of the tracewise metric, the way to remove them has changed,
* Introduce new method in survey - `filter_by_metric` that removing traces from survey based on tracewise metric values,
* `mark_dead_traces` removed,
* Small fixes in survey stats, plot, info and ect.

Any suggestions on naming are welcome!

2023-03-20 10:29 UTC, alexanderkuvaev requested changes

2023-03-20 10:29 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +            coords_cols = to_list(coords_cols)
This can be done once before the loop anong with `get_headers`

2023-03-20 10:29 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        bin_fn = np.greater_equal if self.is_lower_better else np.less_equal
Handle case when `is_lower_better` is `None`

2023-03-20 10:29 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        res = np.abs(traces[:, 2:] + traces[:, :-2] - 2*traces[:, 1:-1]) / 3
Why divided by 3?

2023-03-20 10:29 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +                if j < arr.shape[1]:
What if all samples are muted?

2023-03-20 10:29 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        return (res_plus + res_minus).astype(np.float32)
Don't get why + here, let's discuss.

2023-03-20 10:29 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +    def __init__(self, offsets=None, times=None, name=None):
Let's make `times` and `offsets` obligatory arguments

2023-03-20 11:55 UTC, anton-br commented on seismicpro/gather/gather.py
> +                header_values=self[top_header]
fixed, thx

2023-03-20 11:55 UTC, anton-br commented on seismicpro/survey/survey.py
> +        # TODO: what to do here?
okay

2023-03-20 11:55 UTC, anton-br commented on seismicpro/survey/survey.py
> +        # TODO: do we need deep_all_traces?
okay

2023-03-20 11:56 UTC, anton-br commented on seismicpro/survey/survey.py
> +        if header_name is None:
I added check for this case, is it what you mean?

2023-03-20 11:56 UTC, anton-br commented on seismicpro/survey/survey.py
> +        return mmaps[0] if (len(mmaps) == 1 and squeeze_output) else mmaps
done

2023-03-20 11:57 UTC, anton-br commented on seismicpro/survey/survey.py
> +                continue
added raise

2023-03-20 11:57 UTC, anton-br commented on seismicpro/survey/survey.py
> +            coords_cols = to_list(coords_cols)
moved

2023-03-20 15:28 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        agg_fn = np.nanmax if self.is_lower_better else np.nanmin
done

2023-03-21 08:34 UTC, anton-br commented on seismicpro/survey/survey.py
> +            metric_mmap = metric.construct_map(coords, values, index=index, agg=agg, bin_size=bin_size, survey=self)
tried, have a look

2023-03-21 09:01 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        return (np.max(gather.data, axis=1) - np.min(gather.data, axis=1) < 1e-10).astype(np.float32)
changed to `is_close`

2023-03-21 16:34 UTC, alexanderkuvaev requested changes

2023-03-21 16:34 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +            if header_name not in self.headers:
```suggestion
            header_name = DeadTrace.name
            if header_name not in self.headers:
```

2023-03-21 16:34 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +        def calc_metrics(i, chunk_size):
No need to pass `chunk_size` explicitly

2023-03-21 16:34 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +        executor_class = ForPoolExecutor if n_workers == 1 else ThreadPoolExecutor
Initing a thread is cheap, `ThreadPoolExecutor` should be fine in both cases

2023-03-21 16:34 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +        with tqdm(total=n_chunks, desc="Chunks processed", disable=not bar) as pbar:
Traces, not chunks

2023-03-21 16:34 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +                    future.add_done_callback(lambda fut: pbar.update(int(len(fut.result()) / len(metrics))))
```suggestion
                    future.add_done_callback(lambda fut: pbar.update(len(fut.result()[0])))
```

2023-03-21 16:34 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +            self.headers[metric.header_cols] = np.concatenate(metric_vals)[orig_idx]
seems like it can be done using `stack` - `concatenate` - advanced indexing

2023-03-21 16:34 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +                                               bin_size=bin_size)
```suggestion
            columns = set(index_cols + coords_cols + to_list(metric.header_cols))
            metric_mmap = metric.construct_map(coords, self.get_headers(metric.header_cols), index=index, agg=agg,
                                               bin_size=bin_size)
```
And calculate `coords` and `index` just after `coords_cols` and `index_cols` outside the loop

2023-03-24 21:46 UTC, alexanderkuvaev requested changes

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +                metric_list = [self.qc_metrics[name.strip()] for name in metric_name.split("/")]
Check that:
- only 2 metrics are used
- both of them are of the `BaseWindowMetric` type
- both of them exist in `qc_metrics`

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +    is_lower_better = None
I'd remove these from the base class

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        super().__init__(name=name)
Remove

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +    `get_mask` method, and optionnaly `preprocess`."""
Lots of typos like "optionnaly", please double-check all the docs

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        raise NotImplementedError
I'd remove it from the base class. Also why `parallel` here?

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        return (mask < threshold[0]) | (mask > threshold[1])
In case of a single threshold you consider metric value equal to threshold as bad

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        res = np.zeros_like(traces, dtype=np.float32)
it's already `_like`, don't specify `dtype`

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        res = np.empty(traces.shape[0], dtype=np.float32)
```suggestion
        res = np.empty_like(traces.shape[0])
```

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        res = np.empty(traces.shape[0])
```suggestion
        res = np.empty_like(traces.shape[0])
```

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        res = np.empty(traces.shape[0])
```suggestion
        res = np.empty_like(traces.shape[0])
```

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        return self.name + f"with {self.threshold} clips in a row"
Let's change `self.name` to something more human-readable

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        mins = np.zeros_like(traces, dtype=np.int32)
Why not `float32` here if you later cast type anyway?

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +class DeadTrace(TracewiseMetric):
add `description `

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +    def construct_map(self, coords, values, index, **kwargs):
preserve args order as in the base class

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        cols_on = list(coords.columns.union(index.columns))
get them from the map object, `coords` may not be a `DataFrame`

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        sort_by = "offset" if sort_by is None else sort_by
Probably a gather should be sorted by offset for all these metrics

2023-03-24 21:46 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        name = f"{deivider_metric.name} and {divisible_metric.name} ratio" if name is None else name
```suggestion
        name = f"{numerator.name} to {denominator.name}" if name is None else name
```

2023-03-27 07:33 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        return self.compute_indicators_length(indicators, 1, gather.data.shape).astype(np.float32)
rewrote completely

2023-03-27 07:34 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        return (res_plus + res_minus).astype(np.float32)
discussed in person

2023-03-27 09:51 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        super().__init__(name=name)
thx

2023-03-27 09:52 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        return (mask < threshold[0]) | (mask > threshold[1])
change to `<=` and `>=`

2023-03-27 09:53 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        res = np.zeros_like(traces, dtype=np.float32)
fixed

2023-03-27 09:53 UTC, anton-br commented on seismicpro/survey/metrics.py
> +class DeadTrace(TracewiseMetric):
add only here for now

2023-03-27 09:54 UTC, anton-br commented on seismicpro/survey/metrics.py
> +    def construct_map(self, coords, values, index, **kwargs):
fix signature

2023-03-27 09:55 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        sort_by = "offset" if sort_by is None else sort_by
now all window based metrics always will be sorted by offset

2023-03-27 15:15 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        return f"Traces with max abs to std ratio bigger than {self.threshold}"
```suggestion
        return f"Traces with max abs to std ratio greater than {self.threshold}"
```

2023-03-27 15:15 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        return f"Traces with inverce CV bigger than {self.threshold}"
```suggestion
        return f"Traces with inverse CV greater than {self.threshold}"
```
But I'd call it "mean divided by std" like in the next metric to be more clear

2023-03-27 15:27 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        # We need to copy gather since some metrics changes gather in get_mask, but we want to plot gather unchanged
None of `get_mask`s now change gather data

2023-03-27 15:29 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        sum_df[self.name] = np.sqrt(sum_df[self.name+"_x"] / sum_df[self.name+"_y"])
You wanted to rename these columns

2023-03-27 15:31 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +                                     calculate_immediately=calculate_immediately)
```suggestion
        return super().construct_map(sum_df[nums_map.coords_cols], sum_df[self.name], index=sum_df[nums_map.index_cols], agg=agg, bin_size=bin_size,
                                     calculate_immediately=calculate_immediately)
```

2023-03-27 15:32 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        name = f"{numerator.name} and {denominator.name} ratio" if name is None else name
```suggestion
        name = f"{numerator.name} to {denominator.name} ratio" if name is None else name
```

2023-03-27 15:33 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        ratio_df = mmaps_1.index_data.merge(mmaps_2.index_data, on=cols_on)
```suggestion
        ratio_df = mmaps_1.index_data.merge(mmaps_2.index_data, on= mmaps_1.index_cols)
```

2023-03-27 15:36 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        second_bound = np.clip(first_bound + (win_size * np.sign(shift)), 0, samples[-1])
Not sure if the window should be centered around shifted offsebt-traveltime curve

2023-03-28 07:54 UTC, anton-br commented on seismicpro/survey/survey.py
> +            self.headers[metric.header_cols] = np.concatenate(metric_vals)[orig_idx]
rewrote compeletely

2023-03-28 08:52 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        # We need to copy gather since some metrics changes gather in get_mask, but we want to plot gather unchanged
`spikes` in `numba_get_mask` still changes

2023-03-28 09:11 UTC, anton-br commented on seismicpro/survey/survey.py
> +                    metric_value = metric.compute_rms(*self[metric.header_cols].T)
Done

2023-03-28 09:11 UTC, anton-br commented on seismicpro/survey/survey.py
> +                metric_value = self.headers[metric.header_cols]
Done

2023-03-28 09:11 UTC, anton-br commented on seismicpro/survey/survey.py
> +                metric_msg += f"\n\t{metric.description+':':<55}{sum(metric.binarize(metric_value))}"
Done

2023-03-28 09:11 UTC, anton-br commented on seismicpro/survey/survey.py
> +        orig_idx = idx_sort.argsort(kind='stable')
Done

2023-03-28 09:11 UTC, anton-br commented on seismicpro/survey/survey.py
> +            metric_names = list(self.qc_metrics.keys())
Done

2023-03-28 09:11 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        return f"Traces with max abs to std ratio bigger than {self.threshold}"
Done

2023-03-28 09:11 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        return f"Traces with inverce CV bigger than {self.threshold}"
Done

2023-03-28 09:12 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        return f"Traces with more than {self.threshold} clips in a row"
Done

2023-03-28 09:12 UTC, anton-br commented on seismicpro/survey/metrics.py
> +                                     calculate_immediately=calculate_immediately)
Done

2023-03-28 09:12 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        name = f"{numerator.name} and {denominator.name} ratio" if name is None else name
Done

2023-03-28 09:12 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        ratio_df = mmaps_1.index_data.merge(mmaps_2.index_data, on=cols_on)
Done

2023-03-28 09:12 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        return super().construct_map(coords, values, coords_cols=coords_cols, index=index, index_cols=index_cols,
deleted

2023-03-28 11:57 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        second_bound = np.clip(first_bound + (win_size * np.sign(shift)), 0, samples[-1])
rewritten

2023-03-28 11:57 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        sum_df = sum_square_map.index_data.merge(nums_map.index_data, on=cols_on)
done

2023-03-28 12:03 UTC, anton-br commented on seismicpro/survey/utils.py
> +@njit(nogil=True)
moved to general_utils.py

2023-04-03 13:54 UTC, alexanderkuvaev requested changes

2023-04-03 13:54 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +                max_counter = _update_counters(trace[j], i, j, max_val, max_counter, maxes)
Don't pass `i` and `j` here, pass `maxes[i, j - max_counter : j]` as a `container`. Will make the signature less magic

2023-04-03 13:54 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        def _update_counters(trace, i, j, value, counter, container):
It's not a `trace` but a `sample`

2023-04-03 13:54 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +    """Calcualte the number of consecutive identical amplitudes.
Still typos in docs, use Code Spell Checker extension

2023-04-03 13:54 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +                    traces[i, :] = 0
Instead of copying trace data and filling these nans you could calculate the metric from `j` to the end of the trace

2023-04-03 13:54 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +    def __init__(self, muter, name=None, nan_ratio=0.95):
Add `nan_ratio` to `__repr__`

2023-04-03 13:54 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        """Compute QC indicator in parallel."""
It's not parallel

2023-04-03 13:54 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +            end_ix = end_ixs[i]
`zip`?

2023-04-03 13:54 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        return super().construct_map(sum_df[coords.columns], sum_df[self.name], index=sum_df[index.columns], agg=agg,
```suggestion
        return super().construct_map(sum_df[nums_map.coords_cols], sum_df[self.name], index=sum_df[nums_map.index_cols], agg=agg,
```

2023-04-03 13:54 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        coords = ratio_df[coords.columns]
```suggestion
        coords = ratio_df[mmaps_1.coords_cols]
```

2023-04-03 13:54 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        index = ratio_df[index.columns]
```suggestion
        index = ratio_df[mmaps_1.index_cols]
```

2023-04-03 13:54 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +    def __init__(self, numerator, denominator, name=None):
Add `__repr__ `

2023-04-03 13:54 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        self.denominator.add_mask_on_plot(ax=ax, gather=gather, color="magenta", legend="denominator window")
Use metric names for legend here

2023-04-03 13:54 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        # Include the next index to mimic the behavior of traditional software
```suggestion
        # Include the next index to mimic the behavior of conventional software
```

2023-04-03 13:54 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        window_size = int(times_to_indices(np.array([window_size]), samples, round=True)[0])
You can't treat window size like this. First calculate window bounds in milliseconds and then transform them into indices.

2023-04-04 10:14 UTC, anton-br commented on seismicpro/tests/survey/test_stats.py
> +"""Test Survey collect_stats method"""
removed from here and added some simple tests for tracewise qc, have a look

2023-04-04 10:14 UTC, anton-br commented on seismicpro/tests/survey/test_init.py
> +        assert not survey.qc_metrics and isinstance(survey.qc_metrics, dict)
fixed

2023-04-04 12:20 UTC, anton-br commented on seismicpro/survey/survey.py
> +        Number of possible bad traces found by tracewise QC:
rewritten

2023-04-04 12:20 UTC, anton-br commented on seismicpro/survey/survey.py
> +            min_mask = metric.binarize(metric_value, threshold)
renamed to `bin_mask`

2023-04-04 12:21 UTC, anton-br commented on seismicpro/survey/survey.py
> +        if not self.qc_metrics:
done

2023-04-04 12:21 UTC, anton-br commented on seismicpro/survey/survey.py
> +        """"Filter traces using metric with name `metric_name` and passed `threshold`.
add link to metric.binarize in theshold description

2023-04-04 12:25 UTC, anton-br commented on seismicpro/survey/survey.py
> +                header_cols = metric.header_cols
add comment why this line cannot be removed

2023-04-04 12:25 UTC, anton-br commented on seismicpro/survey/survey.py
> +    def construct_qc_maps(self, by, metric_names=None, id_cols=None, drop_duplicates=False, agg=None, bin_size=None):
deleted

2023-04-04 12:25 UTC, anton-br commented on seismicpro/survey/survey.py
> +            metrics.append(metric.provide_context(survey=self))
deleted

2023-04-04 12:25 UTC, anton-br commented on seismicpro/survey/metrics.py
> +    `get_mask` or `numba_get_mask` methods, and optionally `preprocess` and `description`."""
rewritten

2023-04-04 12:25 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        """Compute QC indicator in parallel."""
fixed

2023-04-04 12:26 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        For a provided gather returns either a samplewise qc indicator with the same shape as `gather` or a tracewize
rewritten

2023-04-04 12:26 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        nan_ixs = np.isnan(mask)
done

2023-04-04 12:30 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        def _update_counters(trace, i, j, value, counter, container):
renamed

2023-04-04 12:31 UTC, anton-br commented on seismicpro/survey/metrics.py
> +    """Calcualte the number of consecutive identical amplitudes.
fixed, hope

2023-04-04 12:31 UTC, anton-br commented on seismicpro/survey/metrics.py
> +    def __init__(self, muter, name=None, nan_ratio=0.95):
added

2023-04-04 12:31 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        """Compute QC indicator in parallel."""
rewritten

2023-04-04 12:32 UTC, anton-br commented on seismicpro/survey/metrics.py
> +            end_ix = end_ixs[i]
Rewritten

2023-04-04 12:32 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        return super().construct_map(sum_df[coords.columns], sum_df[self.name], index=sum_df[index.columns], agg=agg,
done

2023-04-04 12:32 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        coords = ratio_df[coords.columns]
done

2023-04-04 12:32 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        index = ratio_df[index.columns]
done

2023-04-04 12:33 UTC, anton-br commented on seismicpro/survey/metrics.py
> +    def __init__(self, numerator, denominator, name=None):
added

2023-04-04 12:36 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        self.denominator.add_mask_on_plot(ax=ax, gather=gather, color="magenta", legend="denominator window")
changed

2023-04-04 12:36 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        # Include the next index to mimic the behavior of traditional software
fixed

2023-04-04 12:36 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        window_size = int(times_to_indices(np.array([window_size]), samples, round=True)[0])
rewritten

2023-04-06 15:26 UTC, nikita-klsh commented on seismicpro/survey/metrics.py
> +    def header_cols(self):
`SurveyAttribute` metric does not save anything to survey

2023-04-06 15:26 UTC, nikita-klsh commented on seismicpro/survey/metrics.py
> +    """Base class for tracewise metrics with additional plotters and aggregations. Child classes should redefine
```suggestion
    """Base class for tracewise metrics with plotters and aggregations. Child classes should redefine
```

2023-04-06 15:26 UTC, nikita-klsh commented on seismicpro/survey/metrics.py
> +        """Compute qc metric by applying `self.preprocess`, `self.get_mask` and `self.aggregate` to provided gather."""
You describe code in words
```suggestion
        """Compute qc metric. """
```

2023-04-07 08:07 UTC, anton-br commented on seismicpro/survey/survey.py
> +        return self
Seems inappropriate here for me. In this case, method calculate_stats also should output such summary as well.

2023-04-07 08:12 UTC, anton-br commented on seismicpro/survey/survey.py
> +        self.qc_metrics = {}
added

2023-04-07 08:16 UTC, anton-br commented on seismicpro/survey/survey.py
> +        """"Filter traces using metric with name `metric_name` and passed `threshold`.
fixed thx

2023-04-07 08:17 UTC, anton-br commented on seismicpro/survey/survey.py
> +            Whether to remove traces inplace or return a new survey instance.
this is a default description of `inplace` in the survey. Consider to be consistent here and leave is as this, or change it everywhere.

2023-04-07 08:18 UTC, anton-br commented on seismicpro/survey/survey.py
> +        threshold : int, optional, defaults to None
extended, thx

2023-04-07 08:34 UTC, anton-br commented on seismicpro/survey/survey.py
> +        Calculates :class:`~survey.metrics.DeadTrace` if `header_name` is not passed.
it can be caluclated before, but in you don't pass `header_name`, dead traces will be recalculated

2023-04-07 08:39 UTC, anton-br commented on seismicpro/survey/survey.py
> +        column with name `metrics.header_cols`. The only exception is for the metrics that cannot be calculated
we don't have arg with `metric` name. I'd rather leave is as this. `for` deleted, thx

2023-04-07 08:40 UTC, anton-br commented on seismicpro/survey/survey.py
> +        For each trace, the metric is calculated independently and the result is stored in the `self.headers` in a
moved

2023-04-07 08:49 UTC, anton-br commented on seismicpro/survey/survey.py
> +            Number of traces loaded on each iteration.
rewritten

2023-04-07 08:56 UTC, anton-br commented on seismicpro/survey/survey.py
> +            Gather type to aggregate header values over.
fixed, thx

2023-04-07 09:48 UTC, anton-br commented on seismicpro/survey/survey.py
> +            The name(s) of metrics to build metrics maps. If None, maps for all metrics that were calculated for this
rewritten

2023-04-07 09:48 UTC, anton-br commented on seismicpro/survey/survey.py
> +            Calculated metrics maps. Has the same shape as `metric_names`.
rewritten

2023-04-07 09:49 UTC, anton-br commented on seismicpro/survey/survey.py
> +        squeeze_output = isinstance(metric_names, str)
renamed

2023-04-07 09:49 UTC, anton-br commented on seismicpro/survey/survey.py
> +            metric_mmap = self._construct_map(self.get_headers(metric.header_cols), metric=metric, by=by,
renaemd

2023-04-07 11:41 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        """Compute qc metric by applying `self.preprocess`, `self.get_mask` and `self.aggregate` to provided gather."""
discussed in person, left as this

2023-04-07 11:43 UTC, anton-br commented on seismicpro/survey/metrics.py
> +    top_ax_y_scale = "linear"
discussed in person, left as this

2023-04-07 11:43 UTC, anton-br commented on seismicpro/survey/metrics.py
> +    """Base class for tracewise metrics with additional plotters and aggregations. Child classes should redefine
fixed, thx

2023-04-07 11:53 UTC, anton-br commented on seismicpro/survey/metrics.py
> +    def header_cols(self):
fix docs

2023-04-07 12:05 UTC, anton-br commented on seismicpro/survey/metrics.py
> +* Optionally redefine `plot` method which will be used to plot gather with tracewise metric on top on click on a metric
rewritten

2023-04-07 12:06 UTC, anton-br commented on seismicpro/survey/metrics.py
> +  that were passed to `calc` during metric calculation. By default it plots gather with tracewise metric on top.
I've rewrite this block compeletely

2023-04-07 12:09 UTC, anton-br commented on seismicpro/survey/metrics.py
> +  muting or scaling. This gather will later used in `get_mask` and showed on the left side of the interactive plot.
corrected, thx

2023-04-07 12:09 UTC, anton-br commented on seismicpro/survey/metrics.py
> +  while the `get_numba_mask` method must accept only the gather's data.
extended

2023-04-07 12:09 UTC, anton-br commented on seismicpro/survey/metrics.py
> +    def binarize(self, mask, threshold=None):
discussed in person. It is not, because threshold might be changed in metric instance.

2023-04-07 12:11 UTC, anton-br commented on seismicpro/survey/metrics.py
> +automatically provides metrics with all required context for interactive plotting.
rewritten

2023-04-07 12:11 UTC, anton-br commented on seismicpro/survey/survey.py
> +                metric = self.qc_metrics[metric_name]
done

2023-04-07 12:16 UTC, anton-br commented on seismicpro/survey/survey.py
> +    def construct_qc_maps(self, by, metric_names=None, id_cols=None, agg=None, bin_size=None):
unified

2023-04-07 12:16 UTC, anton-br commented on seismicpro/survey/survey.py
> +    def qc_tracewise(self, metrics=None, chunk_size=1000, n_workers=None, bar=True, overwrite=False):
it is ok for me, let's discuss

2023-04-07 12:16 UTC, anton-br commented on seismicpro/survey/survey.py
> +            Whether to remove traces inplace or return a new survey instance.
rewritten

2023-04-07 12:24 UTC, anton-br commented on seismicpro/gather/gather.py
> +            elif isinstance(top_header, np.ndarray) and top_header.shape == (self.n_traces, ):
updated

2023-04-07 12:24 UTC, anton-br commented on seismicpro/gather/gather.py
> +            else:
added list and tuple as possible options for `top_header`

2023-04-07 12:24 UTC, anton-br commented on seismicpro/survey/survey.py
> +        the names of two metrics in the `metric_names` separated by `\`.
fixed, thx

2023-04-10 11:42 UTC, anton-br commented on seismicpro/survey/survey.py
> +                metric_msg += f"\n\t{metric.description+':':<55}{metric.binarize(metric_value).sum()}"
added

2023-04-10 11:42 UTC, anton-br commented on seismicpro/survey/survey.py
> +                    continue
rewrite info section compeletely

2023-04-10 11:42 UTC, anton-br commented on seismicpro/survey/survey.py
> +                metric_msg += f"\n\t{metric.description+':':<55}{metric.binarize(metric_value).sum()}"
fixed

2023-04-10 11:46 UTC, anton-br commented on seismicpro/survey/survey.py
> +        return self
added for `survey.qc` and `survey.collect_stats`

2023-04-10 12:06 UTC, anton-br commented on seismicpro/survey/metrics.py
> +    name = "dead_trace"
now all metric names coinside with class name by default

2023-04-19 16:24 UTC, alexanderkuvaev requested changes

2023-04-19 16:24 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        pass
No need to pass

2023-04-19 16:24 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +    indices for each trace in provided gather.
```suggestion
    """Base class for tracewise metrics that compute RMS amplitude in a window for each trace.
```

2023-04-19 16:24 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +    value of `self.denominator` metric for each gather independently.
depends on `tracewise`

2023-04-19 16:24 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +            mmaps_1.index_data.drop(columns=mmaps_1.coords_cols, inplace=True)
Don't drop, select cols

2023-04-19 16:24 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        return f"Traces within a window by offsets {self.offsets} and times {self.times} with RMS {bundle}"
Rewrite

2023-04-19 16:24 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +                                   self._get_time_ixs, self.compute_stats_by_ixs)
```suggestion
                                     self._get_time_ixs, self.compute_stats_by_ixs)
```

2023-04-19 16:24 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +    """Compute traces RMS for provided window by offsets and times.
```suggestion
    """Compute traces RMS in a rectangular window defined by provided ranges of offsets and times.
```

2023-04-19 16:24 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +    Only the traces that contain at least single amplitude in the provided window are considered, otherwise the metric
```suggestion
    Only traces that contain at least one sample in the provided window are considered, otherwise the metric
```

2023-04-19 16:24 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +                                   fbp_times=fbp_times, times_to_indices=times_to_indices)
```suggestion
                                     window_size=self.window_size, shift=self.shift, samples=gather.samples,
                                     fbp_times=fbp_times, times_to_indices=times_to_indices)
```

2023-04-19 16:24 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +        * Detection of constant traces,
```suggestion
        The following metrics are calculated for each trace by default:
        * A boolean indicator of a dead trace,
```

2023-04-19 16:24 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +        * Number of consecutive identical amplitudes.
```suggestion
        * The maximum number of consecutive identical amplitudes.
```

2023-04-19 16:24 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +        * Length of consecutive amplitudes equals either to trace's minimum or maximum amplitude,
```suggestion
        * The maximum number of consecutive values clipped with either minimum or maximum trace amplitude,
```

2023-04-19 16:24 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +        """Perform quality control of the traces in the survey. The quality control procedure is performed in parallel
Move the second sentence to the paragraph after the bullet list below.

2023-04-26 15:58 UTC, anton-br commented on seismicpro/survey/survey.py
> +        >>> tracewise_qc_map = survey.construct_qc_maps(metric_names={"metric": "signal_rms", "agg_tracewise":True},
renamed

2023-04-26 15:59 UTC, anton-br commented on seismicpro/survey/survey.py
> +        the names of two metrics in the `metric_names` separated by `/`.
added

2023-04-26 15:59 UTC, anton-br commented on seismicpro/metrics/metric.py
>      name : str, optional
removed

2023-04-26 15:59 UTC, anton-br commented on seismicpro/metrics/metric.py
>      metrics = [metric() if isinstance(metric, type) else metric for metric in metrics]
fixed

2023-04-26 16:00 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        """Columnwise `mask` aggregation depending on `self.is_lower_better` to select the worst values."""
`columnwise` changed to `row-wise`

2023-04-26 16:01 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        def _update_counters(sample, counter, container, value):
reordered

2023-04-26 16:01 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        """Compute njitted QC indicator."""
deleted

2023-04-26 16:02 UTC, anton-br commented on seismicpro/survey/metrics.py
> +            if np.isnan(traces[i]).sum() > nan_ratio*len(traces[i]):
changed

2023-04-27 12:56 UTC, anton-br commented on seismicpro/survey/survey.py
> +        Storage for tracewise metrics results with metric's name as a key and metric's instance as a value.
rewritten

2023-04-27 12:58 UTC, anton-br commented on seismicpro/survey/survey.py
> +    def remove_dead_traces(self, header_name=None, chunk_size=1000, inplace=False, bar=True):
added

2023-04-27 12:59 UTC, anton-br commented on seismicpro/survey/survey.py
> +        Construct a map of the ratio of metrics with name `signal_rms` and the metric with name `noise_rms`:
fixed, i hope

2023-04-27 13:06 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        mask = self.get_values(gather)
changed `mask` to `values` everywhere

2023-04-28 08:50 UTC, anton-br commented on seismicpro/survey/metrics.py
> +            sum_square_map.index_data.drop(columns=sum_square_map.coords_cols, inplace=True)
rewritten

2023-04-28 11:26 UTC, anton-br commented on seismicpro/survey/metrics.py
> +    value of `self.denominator` metric for each gather independently.
rewritten

2023-04-28 11:27 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        return f"between {self.threshold[0]} and {self.threshold[1]}"
I renamed function and simplified code inside. Do not want to duplicate the same logic in every description, thus moved this to base class.

2023-04-28 11:28 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        return f"Traces within a window by offsets {self.offsets} and times {self.times} with RMS {bundle}"
rewritten

2023-04-28 11:28 UTC, anton-br commented on seismicpro/survey/metrics.py
> +automatically provides metrics with all required context for interactive plotting.
rewritten

2023-05-02 14:59 UTC, AnnaAltynova commented on seismicpro/gather/gather.py
> +            else:
do we really need these `isinstance` cases or simple `header_values = self[top_header] if isinstance(top_header, str) else top_header` will go?

2023-05-02 15:29 UTC, AnnaAltynova commented on seismicpro/survey/metrics.py
> +        _ = self
why?

2023-05-02 15:48 UTC, AnnaAltynova commented on seismicpro/survey/metrics.py
> +        """Row-wise `values` aggregation depending on `self.is_lower_better` to select the worst values."""
didn't get the docstring. If I'm not mistaken, it should say that the method aggregates samplewise values so that we get tracewise ones. maybe rewrite in other words

2023-05-03 08:50 UTC, AnnaAltynova commented on seismicpro/survey/metrics.py
> +        _ = coords
shouldn't it be the first line after docstring?

2023-05-03 09:01 UTC, AnnaAltynova commented on seismicpro/survey/metrics.py
> +            raise ValueError("Either `threshold` or `self.threshold` must be non None")
`non None`? 
`must be defined` maybe

2023-05-03 09:03 UTC, AnnaAltynova commented on seismicpro/survey/metrics.py
> +            raise ValueError(f"`threshold` should contain exactly 2 elements, not {len(threshold)}")
error msg is not exactly correct, `threshold` can be a single number

2023-05-03 09:27 UTC, AnnaAltynova commented on seismicpro/survey/metrics.py
> +    are not clipped or a positive integer representing the length of the clipped sequence for a particular sample
maybe say that `clipped` sample is the one close to max(trace) or min(trace)

2023-05-03 09:30 UTC, AnnaAltynova commented on seismicpro/survey/metrics.py
> +                if isclose(trace[j], trace[j-1]):
spacing

2023-05-03 10:08 UTC, AnnaAltynova commented on seismicpro/survey/metrics.py
> +            res[i, j+1: -1] = np.abs(traces[i, j+2:] + traces[i, j:-2] - 2*traces[i, j+1:-1]) / 3
spacing

2023-05-04 09:53 UTC, AnnaAltynova commented on seismicpro/survey/metrics.py
> +    def __init__(self, offsets, times, name=None):
why not allow computation with all gather offsets and times if parameters are Nones?

2023-05-04 10:11 UTC, AnnaAltynova commented on seismicpro/survey/metrics.py
> +    refractor velocity shifted by `shift`.
would it be more correct if you say `...centered around the expected times of first breaks according to a refractor velocity model...`?

2023-05-04 10:15 UTC, AnnaAltynova commented on seismicpro/survey/metrics.py
> +        fbp_times = self.refractor_velocity(gather.offsets)
is that ok that we use the same rv here for different gathers? maybe init with rvf and do `refractor_velocity = self.refractor_velocity_field(gather.coords)`?

2023-05-04 11:16 UTC, AnnaAltynova commented on seismicpro/survey/metrics.py
> +class MetricsRatio(TracewiseMetric):  # pylint: disable=abstract-method
maybe move this metric to the end of the file

2023-05-04 12:46 UTC, AnnaAltynova commented on seismicpro/survey/survey.py
> +            Metrics to calculate. If `None`, metrics lised in `DEFAULT_TRACEWISE_METRICS` are calculated.
listed

2023-05-04 12:56 UTC, AnnaAltynova approved these changes

2023-05-11 15:55 UTC, nikita-klsh reviewed
Please set `ax.legend(loc='upper right')` for `gather.plot` whereever possible, as it significantly fasten the wiggle plots

2023-05-15 10:40 UTC, anton-br commented on seismicpro/survey/metrics.py
> +            raise ValueError(f"`threshold` should contain exactly 2 elements, not {len(threshold)}")
rewritten

2023-05-15 10:40 UTC, anton-br commented on seismicpro/survey/metrics.py
> +            raise ValueError("Either `threshold` or `self.threshold` must be non None")
rewritten, thx

2023-05-15 10:40 UTC, anton-br commented on seismicpro/survey/metrics.py
> +            If array, two numbers indicate the boundaries within which the metric values are treated as `False`,
changed to `array-like`

2023-05-15 10:41 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        top_y_ax_scale : str, optional, defaults to None
added

2023-05-15 10:41 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        metric_vals = self.aggregate(metric_res)
renamed somehow, but suggestions are very welcome

2023-05-15 10:49 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        _ = self
deleted)

2023-05-15 10:49 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        """Row-wise `values` aggregation depending on `self.is_lower_better` to select the worst values."""
rewritten

2023-05-15 11:15 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        fbp_times = self.refractor_velocity(gather.offsets)
seeeeems it will require a lot of work to do, so lets do it in the next pr:)

2023-05-15 11:27 UTC, anton-br commented on seismicpro/survey/metrics.py
> +"""Implements a utility metric class for headers metric maps construction and a bunch of metrics for survey quality
no, it is not. https://www.englishforums.com/English/AUtilityVsAnUtility/hrmlw/post.htm

2023-05-15 15:13 UTC, anton-br commented on seismicpro/survey/survey.py
> +        >>> qc_map.plot(interactive=True, threshold=20, sort_by="offset")
moved

2023-05-15 15:13 UTC, anton-br commented on seismicpro/survey/survey.py
> +        amplitudes and second is the number of amplitudes in the window for each trace.
discussed in person and left as this

2023-05-15 15:14 UTC, anton-br commented on seismicpro/survey/survey.py
> +        `self.construct_qc_map`.
Discussed in person: added examples to `survey.qc`.

2023-05-15 15:14 UTC, anton-br commented on seismicpro/survey/metrics.py
> +class DeadTrace(TracewiseMetric):
deleted

2023-05-18 11:07 UTC, alexanderkuvaev requested changes

2023-05-18 11:07 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +        amplitudes and second is the number of amplitudes in the window for each trace.
```suggestion
        The metrics are calculated in parallel threads each processing no more than `chunk_size` traces. The resulting values are stored in `self.headers` under the name defined by `metric.header_cols` which usually matches the name of the metric class.

Some metrics, however, store not their values but some intermediate results which will be aggregated into the actual metric value upon `construct_qc_map` call. For example, metrics that compute window-based RMS amplitudes create two columns in `headers`: one with the sum of squared amplitudes and another with the number of amplitudes in the window for each trace. This allows constructing RMS maps aggregated by different types of gathers (e.g. sources or receivers) without metric recalculation.
```

2023-05-19 12:57 UTC, anton-br commented on seismicpro/utils/general_utils.py
> +def isclose(x, y, atol=1e-5, rtol=1e-8):
removed

2023-05-19 15:29 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        ax.plot(np.arange(gather.n_traces), indices[1], color=color)
added here and for windowrms as well

2023-05-19 15:36 UTC, anton-br commented on seismicpro/tests/survey/test_qc.py
> +        gather = Gather(survey.headers.iloc[sorted_ixs], trace_data, survey.samples, survey)
changed

2023-05-22 10:33 UTC, alexanderkuvaev requested changes

2023-05-22 10:33 UTC, alexanderkuvaev commented on seismicpro/survey/survey.py
> +            if header_name not in self.headers:
Looks like a duplicated check that can be simplified

2023-05-22 10:33 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +    def describe(self, metric_values, line_width=60, separator="\n"):
I'd remove `separator` at all

2023-05-22 10:33 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        msg = f"Traces with RMS {self._get_threshold_description()} computed in a window with a range {self.offsets}m"\
```suggestion
        msg = f"Traces with RMS {self._get_threshold_description()} computed in a window within a range {self.offsets}m"\
```

2023-05-22 10:33 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +            description = "Mean traces RMS computed in a window with a range" + separator
```suggestion
            description = "Mean traces RMS computed in a window within a range" + separator
```

2023-05-22 15:05 UTC, anton-br commented on seismicpro/survey/survey.py
> +            if header_name not in self.headers:
removed an external condition

2023-05-22 15:05 UTC, anton-br commented on seismicpro/survey/metrics.py
> +    def describe(self, metric_values, line_width=60, separator="\n"):
removed

2023-05-24 09:25 UTC, alexanderkuvaev approved these changes

2023-05-24 09:25 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +warnings.simplefilter("ignore", category=RuntimeWarning)
This will disable such warnings globally, not only in this module

2023-05-24 09:25 UTC, alexanderkuvaev commented on seismicpro/metrics/metric.py
> +        Metric name, overrides default name if given. By default name corresponds to the name of the metric class.
```suggestion
        Metric name, overrides default name if given. Defaults to the name of the metric class.
```

2023-05-24 09:25 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        times_ixs = np.clip(gather.times_to_indices(self.times, round=True), 0, len(gather.samples)-1)
```suggestion
        times_ixs = np.clip(gather.times_to_indices(self.times, round=True), 0, gather.n_times - 1)
```

2023-05-24 09:25 UTC, alexanderkuvaev commented on seismicpro/survey/metrics.py
> +        return start_ixs, end_ixs
```suggestion
        def _get_indices(fbp_times, shift, window_size, n_samples, sample_interval, delay):
        """Calculates the start and end indices of a window of size `window_size` centered around the refractor
        velocity shifted by `shift`."""
        mid_times = fbp_times + shift

        start_times = mid_times - window_size / 2
        start_ixs = (start_times - delay) / sample_interval
        start_ixs = np.clip(np.rint(start_ixs), 0, n_samples - 1).astype(np.int32)
        
        end_times = mid_times + window_size / 2
        end_ixs = (end_times - delay) / sample_interval
        end_ixs = np.clip(np.rint(end_ixs), 0, n_samples - 1).astype(np.int32)
        return start_ixs, end_ixs
```
Currently you don't handle a case of positive `delay`

2023-05-24 14:04 UTC, anton-br commented on seismicpro/survey/metrics.py
> +warnings.simplefilter("ignore", category=RuntimeWarning)
moved to metrics __call__ method to avoid global disable

2023-05-24 14:05 UTC, anton-br commented on seismicpro/survey/metrics.py
> +        return start_ixs, end_ixs
added with slightly different window_size processing.

2023-05-26 12:16 UTC, anton-br commented on seismicpro/survey/survey.py
> +        >>> survey.qc(TraceMaxAbs)
rewritten

2023-05-26 12:16 UTC, anton-br commented on seismicpro/survey/survey.py
> +            Whether to rewrite metrics that were previously calculated or raise an exception.
chagned the logic as following:
in case `overwrite=True` - overwrite
in case `overwrite=False` - remove existing metrics from calculation

2023-05-26 12:17 UTC, anton-br commented on seismicpro/survey/survey.py
> +        Define and compute three tracewise metrics:
rewritten

2023-05-26 12:17 UTC, anton-br commented on seismicpro/survey/survey.py
> +        >>> ratio_qc_map = survey.construct_qc_maps(metric_names="SignalWindowRMS/NoiseWindowRMS", by="shot")
left as this, because i prefer `ratio` more than `sn`, sorry

2023-05-26 12:18 UTC, anton-br commented on seismicpro/survey/survey.py
> +        1. Maximum absolute amplitude value divided by trace's std:
fixed

2023-05-26 12:18 UTC, anton-br commented on seismicpro/survey/survey.py
> +        Calculate signal RMS values for each trace and then aggregate them by shots:
moved

2023-05-26 12:18 UTC, anton-br commented on seismicpro/survey/survey.py
> +        >>> qc_map.plot(interactive=True, threshold=20, sort_by="offset")
added example for `plot_on_click_kwargs`

2023-05-26 12:44 UTC, nikita-klsh approved these changes

2023-05-27 09:36 UTC, merged