add load and dump headers
gazprom-neft/SeismicPro pull request #134
Opened 2023-04-19 09:30 UTC by anton-br

2023-04-26 09:38 UTC, AnnaAltynova commented on seismicpro/containers.py
> +        how = "left" if keep_all_headers else "inner"
why not just set `how` parameter? 
what if one wants `right` join?

2023-04-26 09:47 UTC, AnnaAltynova commented on seismicpro/containers.py
> +                sep = sep or ',' if format == "csv" else None
in `fwf` case `sep` here is None(if not given), but in line 359 it is explicitly set as "r'\s+'". why?

2023-04-26 09:49 UTC, AnnaAltynova commented on seismicpro/containers.py
> +            sep = ',' if sep is None else sep
seems redundant, maybe can be unified with line 345

2023-04-26 10:00 UTC, AnnaAltynova commented on seismicpro/containers.py
> +                usecols[usecols < 0] = n_cols + usecols[usecols < 0]
why not `+= n_cols` ?

2023-04-26 10:05 UTC, AnnaAltynova commented on seismicpro/containers.py
> +            Columns indices to be selected from file. Should be always passed in ascending order.
why ascending order? pandas seems not to care.
in any case, why not sort it?

2023-04-26 10:05 UTC, AnnaAltynova commented on seismicpro/containers.py
> +            usecols = usecols.tolist()
we might lose ascending order of `usecols` now

2023-04-26 10:18 UTC, AnnaAltynova commented on seismicpro/containers.py
> +            join_on_headers = list(set(headers.columns) & set(loaded_headers.columns))
maybe `list` here is not necessary

2023-04-26 10:21 UTC, AnnaAltynova commented on seismicpro/containers.py
> +        join_on_headers : str, array-like of str or None, optional, defaults to None
I would go with smth short like `join_on`  or just `on` as in pandas, but not sure

2023-04-26 10:23 UTC, AnnaAltynova commented on seismicpro/containers.py
> +            Array with column names to use as header names. If `None` and `has_header` is `True`, header names will be
`to use as trace headers`

2023-04-26 10:27 UTC, AnnaAltynova commented on seismicpro/containers.py
> +              Delimiter to use. If not provided, it will be inferred base on the `format`.
`based on`

2023-04-26 10:56 UTC, AnnaAltynova reviewed
nice

2023-04-26 11:25 UTC, anton-br commented on seismicpro/containers.py
> +        how = "left" if keep_all_headers else "inner"
Discussed in person: we never want to use "right", or any other join.

2023-04-26 11:26 UTC, anton-br commented on seismicpro/containers.py
> +                usecols[usecols < 0] = n_cols + usecols[usecols < 0]
you right, added

2023-04-26 11:47 UTC, anton-br commented on seismicpro/containers.py
> +            join_on_headers = list(set(headers.columns) & set(loaded_headers.columns))
u right, deleted.

2023-04-26 11:48 UTC, anton-br commented on seismicpro/containers.py
> +        join_on_headers : str, array-like of str or None, optional, defaults to None
renamed to `join_on`

2023-04-26 11:49 UTC, anton-br commented on seismicpro/containers.py
> +            Array with column names to use as header names. If `None` and `has_header` is `True`, header names will be
yes, it should. But this restriction is checked in `pandas` or `polars`.

2023-04-28 14:14 UTC, anton-br commented on seismicpro/survey/survey.py
>      def load_first_breaks(self, path, trace_id_cols=('FieldRecord', 'TraceNumber'), first_breaks_col=HDR_FIRST_BREAK,
I don't want to move some geological stuff there, but we can discuss this

2023-04-28 14:14 UTC, anton-br commented on seismicpro/containers.py
> +            If `format="csv"`, passed to `polars.write_csv`.
I want to save this ability at least.

2023-05-02 10:03 UTC, anton-br commented on seismicpro/containers.py
> +    def dump_headers(self, path, columns, format="fwf", sep=',', col_space=8, decimal='.', dump_col_names=False,
deleted

2023-05-02 10:03 UTC, anton-br commented on seismicpro/containers.py
> +            dump_df.to_string(path, col_space=col_space, header=dump_col_names, index=False, decimal=decimal, **kwargs)
I added float formats for both `format`s

2023-05-02 10:17 UTC, anton-br commented on seismicpro/containers.py
> +            Decimal point character. Used only for "fwf" `format`.
deligated)

2023-05-02 10:52 UTC, anton-br commented on seismicpro/containers.py
> +    def dump_headers(self, path, columns, format="fwf", sep=',', col_space=8, decimal='.', dump_col_names=False,
done here, but left in `load_headers` since it is simplified code a lot.

2023-05-02 10:53 UTC, anton-br commented on seismicpro/containers.py
> +    def get_headers(self, cols, preserve_dtype=False):
rewritten compeletely, have a look. I'll resolve other commets about `get_headers` since they outdated now.

2023-05-04 10:40 UTC, nikita-klsh reviewed
It took 10 minutes for `survey.dump_headers(path, headers=['FieldRecord', 'TraceNumber', 'FirstBreak'])` on the survey with 57kk traces and still nothing happens.
Nothing appeared on the disk, so i suppose `df.to_stiring` trying to format the whole `df` at once in the non batch manner unlike `df.to_csv`

2023-05-04 10:40 UTC, nikita-klsh commented on seismicpro/survey/survey.py
> +        return self.dump_headers(path=path, columns=columns, format=format, **kwargs)
```suggestion
        return self.dump_headers(path=path, headers=columns, format=format, **kwargs)
```

2023-05-04 14:31 UTC, anton-br commented on seismicpro/survey/survey.py
> +        return self.dump_headers(path=path, columns=columns, format=format, **kwargs)
fixed, thx

2023-05-04 14:31 UTC, anton-br commented on seismicpro/survey/survey.py
> +        return self.load_headers(path=path, headers=headers, join_on_headers=trace_id_headers, format=format,
fixed, thx

2023-05-04 14:32 UTC, anton-br commented on seismicpro/containers.py
> +        return headers_cols
rewritten comeletely, have a look.

2023-05-04 15:51 UTC, anton-br commented on seismicpro/containers.py
> +        headers : array-like of str, optional, defaults to None
renamed

2023-05-05 14:54 UTC, dpodvyaznikov commented on seismicpro/containers.py
> +        keep_all_headers : bool, optional, defaults to False
I don't like the naming. Why not
```suggestion
        how : 'inner' or 'left', optional, defaults to 'inner'
```
?

2023-05-05 14:54 UTC, dpodvyaznikov commented on seismicpro/containers.py
> +        usecols : array-like of int or None, optional, defaults to None
Why should they be always ascending? It seems that both pandas and ploars allow for non-sorted `use_cols`

2023-05-05 14:54 UTC, dpodvyaznikov commented on seismicpro/containers.py
> +                    usecols[usecols < 0] += len(row.split(usecols_sep))
Wouldn't this be simpler?
```suggestion
                    usecols = np.arange(len(row.split(usecols_sep)))[usecols]
```

2023-05-05 14:54 UTC, dpodvyaznikov commented on seismicpro/containers.py
> +            if has_header:
Maybe use ternary operator?

2023-05-05 14:54 UTC, dpodvyaznikov commented on seismicpro/containers.py
> +            loaded_headers = pd.read_csv(path, sep=r'\s+', header=header, names=headers_names, usecols=usecols,
Did you compare this way with `pd.read_fwf'?

2023-05-10 11:41 UTC, anton-br commented on seismicpro/containers.py
> +            loaded_headers = pd.read_csv(path, sep=r'\s+', header=header, names=headers_names, usecols=usecols,
yes, `read_fwf` much slower than `read_csv`

2023-05-10 13:52 UTC, anton-br commented on seismicpro/containers.py
> +                    usecols[usecols < 0] += len(row.split(usecols_sep))
added

2023-05-10 14:00 UTC, anton-br commented on seismicpro/containers.py
> +                    usecols[usecols < 0] += len(row.split(usecols_sep))
added

2023-05-10 14:01 UTC, anton-br commented on seismicpro/survey/survey.py
> +                          first_breaks_header=HDR_FIRST_BREAK, format="fwf", **kwargs):
deleted here and in `load_first_breaks`

2023-05-10 14:01 UTC, anton-br commented on seismicpro/utils/general_utils.py
> +    """Extract columns from `cols` from the `df` DataFrame columns or index as a new instance of `pd.DataFrame`."""
extended docs

2023-05-10 14:04 UTC, anton-br commented on seismicpro/containers.py
> +    def load_headers(self, path, headers_names=None, join_on=None, format="fwf", has_header=False, usecols=None,
I prefer this naming, but open to any suggestions

2023-05-17 13:46 UTC, alexanderkuvaev requested changes

2023-05-17 13:46 UTC, alexanderkuvaev commented on seismicpro/containers.py
> +    @batch_method(target="for", use_lock=True)
This lock was needed to perform proper appends to the file. Now this option is completely lost. Think of bringing it back

2023-05-17 13:46 UTC, alexanderkuvaev commented on seismicpro/tests/test_dump_load_headers.py
Simplify all these tests:
1. Remove magic `dump_load_headers` function completely.
2. Start with simple `DataFrame`s with different types of columns and test that consequent call of `dump_dataframe` and `read_dataframe` returns the same df up to `dtype` bitness.
3. Create a fixture that returns a container (gather/survey with optionally added columns) and a list of headers to dump. Check that `dump_headers` - `read_dataframe` returns the same `headers`.
4. Test `load_headers` in the same manner

2023-05-18 11:27 UTC, anton-br commented on seismicpro/containers.py
> +        headers = pl.from_pandas(self.headers.reset_index())  # pylint: disable=access-member-before-definition
Your suggection is much faster, rewritten

2023-05-18 13:48 UTC, anton-br commented on seismicpro/containers.py
> +    def load_headers(self, path, headers_names=None, join_on=None, format="fwf", has_header=False, usecols=None,
reordered, but a little in different way. I want to preserve args order between `load_headers` and `dump_headers`, thus `format` arg cannot be placed before `headers_names`. Also, I think that `format` will be used less frequently than `join_on`. Thus I've placed it after `how`.

2023-05-18 15:24 UTC, anton-br commented on seismicpro/containers.py
> +    @batch_method(target="for", use_lock=True)
added `append` argument that allows to append headers to the file

2023-05-18 15:24 UTC, anton-br commented on seismicpro/containers.py
> +            Decimal point character. If not provided, it will be inferred from the file. Used only for "fwf" `format`.
deleted

2023-05-18 15:24 UTC, anton-br commented on seismicpro/containers.py
> +        casts = [loaded_headers[column].cast(headers[column].dtype) for column in to_list(join_on)]
fixed

2023-05-18 15:24 UTC, anton-br commented on seismicpro/containers.py
> +        joined_headers = headers.join(loaded_headers, on=join_on, how=how, suffix="_loaded")
rewritten

2023-05-18 15:24 UTC, anton-br commented on seismicpro/containers.py
> +        self._post_filter(headers["TRACE_SEQUENCE_FILE"].is_in(joined_headers["TRACE_SEQUENCE_FILE"]).to_numpy())
rewritten

2023-05-18 15:43 UTC, anton-br commented on seismicpro/containers.py
> +        joined_headers = headers.join(loaded_headers, on=join_on, how=how, suffix="_loaded")
Rewritten this part, but in a slightly different way. For me, adding `lazy` didn't change anything. At least, I didn't notice.

2023-05-24 11:26 UTC, alexanderkuvaev commented on seismicpro/containers.py
> +            Whether to keep headers for traces that were missed in the loaded file.
remove line

2023-05-24 11:26 UTC, alexanderkuvaev commented on seismicpro/containers.py
> +            as new `self.headers`. If "left", all traces will be kept in `self.headers`. For traces that were missed in
```suggestion
            as new `self.headers`. If "left", all traces will be kept in `self.headers`. For traces that were missing in
```

2023-05-24 11:26 UTC, alexanderkuvaev commented on seismicpro/containers.py
> +    def load_headers(self, path, headers_names=None, has_header=False, usecols=None, join_on=None, how="inner",
Unify order of args as in file_utils

2023-05-24 11:26 UTC, alexanderkuvaev commented on seismicpro/containers.py
> +    def dump_headers(self, path, headers_names, dump_headers_names=False, format="fwf", append=False,
Unify order of args as in file_utils

2023-05-24 12:23 UTC, anton-br commented on seismicpro/survey/survey.py
> +        traces_pos = np.sort(get_cols(headers, "TRACE_SEQUENCE_FILE").to_numpy() - 1)
added

2023-05-24 12:23 UTC, anton-br commented on seismicpro/utils/file_utils.py
> +def dump_dataframe(file, df, has_header=False, format="fwf", float_precision=2, decimal=".", min_width=None, **kwargs):
done

2023-05-24 12:23 UTC, anton-br commented on seismicpro/utils/file_utils.py
> +    elif format == "csv":
added

2023-05-24 12:23 UTC, anton-br commented on seismicpro/utils/file_utils.py
> +def _dump_to_fwf(path, df, has_header, float_precision, decimal, min_width=None):
reordered

2023-05-24 12:24 UTC, anton-br commented on seismicpro/utils/file_utils.py
> +def load_dataframe(path, columns=None, has_header=False, usecols=None, format="fwf", sep=',', skiprows=0, decimal=None,
reordered

2023-05-24 12:24 UTC, anton-br commented on seismicpro/containers.py
> +    def load_headers(self, path, headers_names=None, has_header=False, usecols=None, join_on=None, how="inner",
unified

2023-05-24 12:24 UTC, anton-br commented on seismicpro/containers.py
> +    def dump_headers(self, path, headers_names, dump_headers_names=False, format="fwf", append=False,
unified

2023-05-25 09:42 UTC, anton-br commented on seismicpro/tests/test_dump_load_headers.py
rewritten

2023-05-25 10:51 UTC, alexanderkuvaev approved these changes

2023-05-26 11:58 UTC, AnnaAltynova commented on seismicpro/containers.py
> +        trace_id_headers : str or tuple of str, defaults to ('FieldRecord', 'TraceNumber')
why is it not `trace_id_cols` as before?

2023-05-26 12:12 UTC, AnnaAltynova commented on seismicpro/containers.py
> +        append : bool, optional, defaults to False
`False` append by default is not an expected behaviour, e.g. when dumping first breaks in a pipeline

2023-05-26 13:23 UTC, anton-br commented on seismicpro/containers.py
> +        trace_id_headers : str or tuple of str, defaults to ('FieldRecord', 'TraceNumber')
TLDR: now we want to use `header` not `column` when talking about headers columns

2023-05-26 13:56 UTC, anton-br commented on seismicpro/containers.py
> +        first_breaks_header : str, optional, defaults to 'FirstBreak'
thx, renamed everywhere

2023-05-26 13:59 UTC, anton-br commented on seismicpro/containers.py
> +        append : bool, optional, defaults to False
For me, append `False` is exactly expected behavior and the main way how to use the function. For dumping fb in a pipeline you should use a flag, yes. But I don't want to unexpectedly append to file when I want to rewrite it.

2023-05-27 09:28 UTC, alexanderkuvaev commented on seismicpro/containers.py
> +        append : bool, optional, defaults to False
I'd definitely keep `False` as a default

2023-05-29 12:56 UTC, dpodvyaznikov approved these changes

2023-05-29 13:04 UTC, nikita-klsh approved these changes

2023-05-29 13:27 UTC, merged