Metrics
gazprom-neft/SeismicPro pull request #33
Opened 2020-09-24 15:12 UTC by anton-br

This pull request is adding a oppotunity to cunstruct a metrics map. It allows to use `gather_metrics` from batchblow.

2020-09-29 14:38 UTC, a-arefina commented on seismicpro/src/seismic_metrics.py
> +    ]
where do you use this?

2020-09-29 14:38 UTC, a-arefina commented on seismicpro/src/seismic_metrics.py
> +        call_aggr_bins = call_aggr_bins(None, **aggr_bins_kwargs) if aggr_bins_kwargs is not None else call_aggr_bins
the choice expression returns call_aggr_bins result in one branch and call_aggr_bins itself in the other

did you want to use partial function?


I would move this selection inside NumbaNumpy. For example, all its class methods could return callables

2020-09-29 14:38 UTC, a-arefina commented on seismicpro/src/seismic_metrics.py
> +                if mask.sum() > 0:
np.any ?

2020-09-29 14:38 UTC, a-arefina commented on seismicpro/src/seismic_metrics.py
> +        call_aggr_bins = getattr(NumbaNumpy, aggr_bins)
aggr_bins - what about renaming to aggr_bins_fn ?

2020-09-29 14:38 UTC, a-arefina commented on seismicpro/src/seismic_metrics.py
> +                        (coords_y - range_y[j] >= 0) & (coords_y - range_y[j] < bin_size_y))
I feel that there are more clear and readable ways to define mask (are slices ok here?), but I believe that you made all this complicated mask creation for the sake of efficiency.

2020-09-29 14:45 UTC, a-arefina commented on tutorials/metrics_map_pipeline.ipynb
> +{
<p>1) Please remove unuse imports like <code>sns</code></p><p>2) I couldn't find <code>SemblanceMetrics</code> . did you commit it?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/33/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2020-09-29 14:45 UTC, a-arefina commented on tutorials/metrics_map_pipeline.ipynb
> +{
<p>I'd like to have a more convenient way to define <code>coords</code> in gather_metrics</p><p> </p><p>BTW, did you check this with a larger batch size?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/33/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='2'/>

2020-09-29 14:45 UTC, a-arefina commented on tutorials/metrics_map_pipeline.ipynb
> +{
<p>I couldn't understand how <code>'map'</code>  is transformed to <code>construct_map</code>  , i.e. how do you add <code>construct_</code>  to the method name</p><p> </p><p>All in all, one would need a good explanatory notebook for this feature, so please add more comments</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/33/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='4'/>

2020-09-29 14:47 UTC, a-arefina reviewed
I feel that tests will be super-helpful in writing a better structured code

2020-10-07 20:10 UTC, nikita-klsh commented on seismicpro/src/plot_utils.py
> +                    extent=extent_coords, **kwargs)
feels like if we do not specify `extent` at all, it anyway does the same calculations under the hood

2020-10-12 12:28 UTC, nikita-klsh commented
Is such kind of padding expected?

```
x, y, m = np.random.randint(1, 101, (3, 10000)) # x and y take value 1 to 100
res = construct_metrics_map(x, y, m, (10, 10), NumbaNumpy.mean) # bin size = 10x10
plt.imshow(res)
```
![image](https://user-images.githubusercontent.com/8656643/95746374-59271900-0c9f-11eb-9439-935fb21e1dfa.png)

2020-10-12 13:13 UTC, anton-br commented
> Is such kind of padding expected?
> 
> ```
> x, y, m = np.random.randint(1, 101, (3, 10000)) # x and y take value 1 to 100
> res = construct_metrics_map(x, y, m, (10, 10), NumbaNumpy.mean) # bin size = 10x10
> plt.imshow(res)
> ```
> 
> ![image](https://user-images.githubusercontent.com/8656643/95746374-59271900-0c9f-11eb-9439-935fb21e1dfa.png)

no, it isn't expected, thanks

2020-10-15 08:39 UTC, a-arefina commented on seismicpro/src/seismic_metrics.py
> +            if len(metrics[0].shape) > 1:
In this branch `metrics[0]` can be `tuple, list, set`, but none of those have `shape` attribute

2020-10-15 08:39 UTC, a-arefina commented on seismicpro/src/seismic_metrics.py
> +                raise ValueError('Construct map does not work with 3d metrics yet.')
what about 2d?

2020-10-15 08:39 UTC, a-arefina commented on seismicpro/src/seismic_metrics.py
>          coords_x = np.array(maps_list_transposed[0], dtype=np.float32)
It might be more convenient to use self.coords and seld.metrics without packing them into self.maps_list and then unpacking again

You can extend both of them in `self.extend`

2020-10-15 08:39 UTC, a-arefina commented on seismicpro/src/seismic_metrics.py
> +        shapes = []
What about `shapes` being a (range_x, range_y) array? It might be mere convenient.

2020-10-15 08:54 UTC, anton-br commented on seismicpro/src/seismic_metrics.py
> +        shapes = []
this thing shouldn't be here, ill remove it completely because numba can't work with list

2020-10-15 08:56 UTC, anton-br commented on seismicpro/src/seismic_metrics.py
> +            if len(metrics[0].shape) > 1:
thanks, i'll change it

2020-10-15 08:58 UTC, anton-br commented on seismicpro/src/seismic_metrics.py
> +                raise ValueError('Construct map does not work with 3d metrics yet.')
here, 2d means that for each coordinates we have an array with metrics. Because when you will calcualte metircs in bin, you will receive 2d array.
And yes, metrics works with 2d arrays now

2020-10-15 09:53 UTC, anton-br commented on seismicpro/src/plot_utils.py
> +                    extent=extent_coords, **kwargs)
no it is not, because metrics map has indices from 0 to `metrics_map.shape` but we want to write our coordinates by axis

2020-10-15 14:21 UTC, anton-br commented on seismicpro/src/seismic_metrics.py
> +    return njit(lambda array: _absquantile(array, q=q))
yes, i do, because you can't simply pass arguments to numba function..

2020-10-15 14:24 UTC, anton-br commented on seismicpro/src/seismic_metrics.py
> +        call_aggr_bins = call_aggr_bins(None, **aggr_bins_kwargs) if aggr_bins_kwargs is not None else call_aggr_bins
here i want to create a callable that one can call without arguments. It means that in the case if `call_aggr_bins` has arguments, we will add them here and the `call_aggr_bins` should return another callable that can be used without arguments

2020-10-15 14:25 UTC, anton-br commented on tutorials/metrics_map_pipeline.ipynb
> +{
i will delete this notebook complitly

2020-10-15 14:32 UTC, nikita-klsh commented on seismicpro/src/seismic_metrics.py
> +class NumbaNumpy:
There is [jitclass](https://numba.pydata.org/numba-doc/dev/user/jitclass.html#jitclass) decorator that decorates each method of the class with `njit` decorator. It might simplify things here

2020-10-16 11:10 UTC, nikita-klsh commented on seismicpro/src/seismic_metrics.py
> +        extent_coords = [coords_x.min(), coords_x.max(), coords_y.min(), coords_y.max()]
This list is only used in the plot function, so it can be created directly there

2020-10-16 11:12 UTC, anton-br commented on seismicpro/src/seismic_metrics.py
> +                        (coords_y - range_y[j] >= 0) & (coords_y - range_y[j] < bin_size_y))
unfortunatelly, it seems that you can't choose aggregation in bins (or i just missed it)

2020-10-19 08:41 UTC, a-arefina commented on seismicpro/src/plot_utils.py
> +    aspect = kwargs.get('aspect', 'auto')
```suggestion
    origin = kwargs.pop('origin', 'lower')
    aspect = kwargs.pop('aspect', 'auto')
```

2020-10-21 13:41 UTC, anton-br commented
Consider to add `no-name-in-module` and `import-error` into pylintrc because i don't know how to fix these errors.

2020-10-21 14:37 UTC, a-arefina commented on seismicpro/src/seismic_metrics.py
> +    nanstd = njit(lambda array: np.nanstd(array))
```suggestion
    nanstd = njit(np.nanstd)
```
Can this be?

2020-10-21 14:37 UTC, a-arefina commented on seismicpro/src/seismic_metrics.py
> +    return njit(lambda array: _absquantile(array, q=q))
```suggestion
    return njit(lambda arr: _absquantile(arr, q=q))
```

2020-10-21 14:37 UTC, a-arefina commented on seismicpro/src/seismic_metrics.py
> +    quantile = quantile
```suggestion
    def quantile(q): return  njit(lambda array: np.quantile(array, q=q))
```

And don't pass `None` to `call_agg_bins` when creating it with kwargs

2020-10-21 14:37 UTC, a-arefina commented on seismicpro/src/seismic_metrics.py
> +            call_agg_bins = call_agg_bins(None, **agg_bins_kwargs) if agg_bins_kwargs is not None else call_agg_bins
```suggestion
            call_agg_bins = call_agg_bins(**agg_bins_kwargs) if agg_bins_kwargs else call_agg_bins
```
see comment to line 134
if `agg_bins_kwargs` is an empty dict, you shouldn't pass it to `call_agg_bins`, should you?

2020-10-22 13:14 UTC, anton-br commented on seismicpro/src/seismic_metrics.py
> +    nanstd = njit(lambda array: np.nanstd(array))
no, it can't. This way you'll create a callable with full list of arguments from np.nanstd function while numba works only with the first one. I receive the error `CALL_FUNCTION_EX with **kwargs not supported`.

2020-10-22 13:31 UTC, anton-br commented on seismicpro/src/seismic_metrics.py
> +    quantile = quantile
thank for the tip

2020-10-23 11:00 UTC, nikita-klsh commented on pylintrc
> +        no-name-in-module, import-error
Why not to do this locally in the file?

2020-10-23 11:22 UTC, anton-br commented on pylintrc
> +        no-name-in-module, import-error
Do we really need these varnings? why?

2020-10-23 11:34 UTC, nikita-klsh commented on pylintrc
> +        no-name-in-module, import-error
Then we block a bunch of checks for the whole repository. And if we push the really bad piece of code, pylint will skip it silently.

Since it is the false warning,  you can add `pylint: disable` locally. Then maybe in the next release  pylint  will fix the case and throws the message that `pylint: disable` here is unnecessary. Then we remove it.

2020-10-23 12:33 UTC, anton-br commented on pylintrc
> +        no-name-in-module, import-error
no i mean do we really need these two varnings in our repository

2020-10-23 13:09 UTC, nikita-klsh commented on pylintrc
> +        no-name-in-module, import-error
Why you do not want to detect the imports of unexisting modules?

2020-10-23 13:12 UTC, anton-br commented on pylintrc
> +        no-name-in-module, import-error
because you will receive the error message from python in this case

2020-10-23 13:20 UTC, nikita-klsh commented on pylintrc
> +        no-name-in-module, import-error
If you execute code before pushing :)

2020-10-26 12:13 UTC, nikita-klsh commented
Please add the base class to `__init__.py`

2020-11-03 09:28 UTC, nikita-klsh commented on seismicpro/src/seismic_metrics.py
> +                                                         agg_bins_fn=self.call_agg_bins))
It's very nice that we now can pass list of metrics to `construct map`.

However, for each metric we recalculating point-bin distribution over and over again, which is the same across metrics, only the aggregation function differs. 

Could you move this part out of metrics loop?

2020-11-11 13:57 UTC, anton-br commented
i've tried to change our implemetation to https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binned_statistic_2d.html. But scipy works much slower for huge data.
![image](https://user-images.githubusercontent.com/19351782/98820211-f14f2400-243e-11eb-8cb5-5b437bd32ead.png)

2020-11-16 12:57 UTC, alexandrkuvaev requested changes

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +        self.metrics_names = list(kwargs.keys())
Here you are hoping for the same returned metrics names order in `items` and `keys`, while generally it's not true.

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +        # Create attributes with metrics.
What if we iterate over a dataset with a batch size more than 1 and want to pass an array for each pair of coordinates?

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +        self.coords = list(coords)
Validate, that lengths of metrics match the length of `coords`. Better do it in the above loop.

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +        names of existing metrics.
existing?

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +        self._agg_fn_dict = {'mean': np.nanmean,
Unify `agg` and `aggr`, I like `agg` more. Moreover, this dict is unused and should be deleted.

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +            setattr(self, name, metrics_attr)
Why not one-line it as you did with `coords`?

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +        metrics_name : str
`metric_name` then.

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +        """ All optained coordinates, are splitted into bins of the specified `bin_size`. Resulted map
Grammar! optained! splitted!

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +        are included in the bin, it's value is None. Otherwise, the value of this bin is calculated based
Please, pass all your docstrings through Grammarly.

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +        on the aggregation function `agg_func`.
agg or aggr? Unify everywhere.

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +            If True, metrics will be plotted
If `False`?

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +        """
No `Returns` section.

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +                               and kwargs to :func:`matplotlib.pyplot.imshow`.)
Delete.

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +        metrics = np.array(list(getattr(self, metrics_name)))
But metric value is already stored as a list, isn't it?

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +            raise ValueError('Given metrics is empty.')
Remove as you add this check in `__init__`.

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +            len_of_copy = [len(metrics_array) for metrics_array in metrics]
You'll never have a list of lists as a metric value due to your wrong `__init__` and `extend` implementation.

Currently, metrics passed as a list should not work correctly: after `extend` you will obtain a single list with all metric values for all the coordinates specified.

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +        if isinstance(bin_size, int):
If it's float?

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +            self.aggr_func = aggr_func
Don't get these lines. What if you first call this method with `mean` aggregation, then `max` and then `mean` again?

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +            # Avoid the situation when we have only one coordinate for x or y dimension.
What's wrong with this case?

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +            plot_metrics_map(metrics_map=metric_map, extent=extent, **plot_kwargs)
Unify metric and metrics.

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +        elif callable(aggr_func):
Why no use of `agg_func_kwargs` in this case?

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +        are included in the bin, it's value is None. Otherwise, the value of this bin is calculated based
Not `None` but `np.nan`

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +                if mask.sum() > 0:
yep

2020-11-16 12:57 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +class NumbaNumpy:
I'll think of what we can do to avoid this class, looks scary.

2020-11-17 11:14 UTC, anton-br commented on seismicpro/src/seismic_metrics.py
> +        self._agg_fn_dict = {'mean': np.nanmean,
agree with first part. This dict is used to aggregate resulted metrucs map, see https://github.com/analysiscenter/batchflow/blob/master/batchflow/models/metrics/base.py.

2020-11-17 11:18 UTC, anton-br commented on seismicpro/src/seismic_metrics.py
> +        self.metrics_names = list(kwargs.keys())
i don't care about the names order here. I used metrics_names only to `extend`  metrics' values.

2020-11-17 11:44 UTC, anton-br commented on seismicpro/src/seismic_metrics.py
> +            setattr(self, name, metrics_attr)
Because you have to update all metrics from `metrics_names`. I don't know how to do it in one-line. Please help me with this line if you know how to do it.

2020-11-23 12:18 UTC, anton-br commented on seismicpro/src/seismic_metrics.py
> +        All given kwargs are considered quality values. The key value is any name,
I rewrote this block a bit, take a look.

2020-11-24 12:35 UTC, dpodvyaznikov commented on seismicpro/src/seismic_metrics.py
> +        All given kwargs are considered quality values. The key value is any name,
Way better, imo :+1:

2020-11-27 20:22 UTC, alexandrkuvaev requested changes

2020-11-27 20:22 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +            Quality values.
Let's replace quality with something more concise

2020-11-27 20:22 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +            : two-dimensional array
Call it some way. Or is it a `SeismicPro` docsting convention?

2020-11-27 20:22 UTC, alexandrkuvaev commented on seismicpro/src/utils.py
> +def create_args(call, skip_first=False, **kwargs):
Maybe move it to `seismic_metrics.py`, now it's used only there and, hopefully, so be it.

2020-11-27 20:22 UTC, alexandrkuvaev commented on seismicpro/src/utils.py
> +        If True, created tuple won't contain value for frist argument.
```suggestion
        If True, created tuple won't contain value for the first argument.
```

2020-11-27 20:22 UTC, alexandrkuvaev commented on seismicpro/src/utils.py
> +        if False, created tuple will contain value for first argument.
```suggestion
        if False, created tuple will contain value for the first argument.
```

2020-11-27 20:22 UTC, alexandrkuvaev commented on seismicpro/src/utils.py
> +    skip_first : bool
Not clear what this argument is responsible for

2020-11-27 20:22 UTC, alexandrkuvaev commented on seismicpro/src/utils.py
> +    args = list(np.zeros(len(params.keys()) - skip_first))
```suggestion
    args = [kwargs.get(name, param.default) for name, param in params.items()]
```
Let's do this with the following checks empty parameters and `skip_first` flag. Should be much readable.

2020-12-01 14:05 UTC, anton-br commented on seismicpro/src/plot_utils.py
> +    save_to : str, optional
others plotters have `save_to` argument, but we can discuss it

2020-12-01 19:42 UTC, dpodvyaznikov commented on seismicpro/src/plot_utils.py
> +    x_ticks : int, optional
Technically `x_ticks` and `y_ticks` are optional since they have a default - `None`, but practically this function would fail if one does not provide meaningful value for them.

2020-12-01 19:42 UTC, dpodvyaznikov commented on seismicpro/src/plot_utils.py
> +    x_ticks : int
If parameter has a default value, it is an optional parameter.

2020-12-04 07:53 UTC, dpodvyaznikov approved these changes

2020-12-04 11:02 UTC, alexandrkuvaev requested changes

2020-12-04 11:02 UTC, alexandrkuvaev commented on seismicpro/src/seismic_metrics.py
> +        """ Constructing tuple with positional arguments to callable ``call`` based on
Explicitly specify, that you omit the first arg

2020-12-04 12:26 UTC, alexandrkuvaev approved these changes

2020-12-04 12:26 UTC, merged