Fix bug in meta
gazprom-neft/SeismicPro pull request #37
Opened 2020-11-09 12:04 UTC by anton-br

If you create component by hands it wound't have a meta at all. Old `copy_meta` always is tried to find new component in meta and fails if the component is not contained in the meta dict.

2020-11-10 14:43 UTC, nikita-klsh commented on seismicpro/src/seismic_batch.py
> +            if self.meta.get(t_comp):
I believe the condition `if t_comp in self.meta` is equivalent but more explicit

2020-11-10 14:43 UTC, nikita-klsh commented on seismicpro/src/seismic_batch.py
> +    def add_components(self, components, init=None):
I would suggest reusing the existing code.   
Let the `batch.add_components` initialize the component. And `seismic_batch.add_components` only initialize the meta.

``` 
super().add_components(components, init) 
self.meta[components] = {}
```

2020-11-10 14:43 UTC, nikita-klsh commented on seismicpro/src/seismic_batch.py
> +    def update_component(self, component, value):
Why do we need this when there is `pipeline.update()`?

2020-11-10 14:43 UTC, nikita-klsh commented on seismicpro/src/seismic_batch.py
> +        self.update_component(dst, np.array(energy + [None])[:-1]) # array implicitly converted to object dtype
Why do you use `update` instead of `add` here?
It looks more like the component is created here, not updated

2020-11-10 15:02 UTC, anton-br commented on seismicpro/src/seismic_batch.py
> +            if self.meta.get(t_comp):
no, because meta for t_comp can be empty and my condition will catch this case while your not.

2020-11-10 15:05 UTC, anton-br commented on seismicpro/src/seismic_batch.py
> +        self.update_component(dst, np.array(energy + [None])[:-1]) # array implicitly converted to object dtype
because sometimes we want to create component in pipeline. In this case, `add_component` will return an error. Update component will only change the data inside the component

2020-11-11 15:35 UTC, a-arefina commented on seismicpro/src/seismic_batch.py
> +        """ Add new component or update existed one
```suggestion
        """ Add a new component or update an existing one
```

2020-11-11 15:35 UTC, a-arefina commented on seismicpro/src/seismic_batch.py
> +            if t_comp in self.meta and self.meta[t_comp] != dict():
```suggestion
            if self.meta.get(t_comp, None):
```

empty dict evaluates to false

2020-11-11 17:35 UTC, anton-br commented on seismicpro/src/seismic_batch.py
> +            if t_comp in self.meta and self.meta[t_comp] != dict():
please, decide with @nikita-klsh which approach is better..

2020-11-12 11:36 UTC, a-arefina approved these changes

2020-11-16 12:45 UTC, dpodvyaznikov approved these changes

2020-11-16 12:49 UTC, nikita-klsh approved these changes

2020-11-16 13:41 UTC, alexandrkuvaev requested changes

2020-11-16 13:41 UTC, alexandrkuvaev commented on seismicpro/src/seismic_batch.py
> +        for comp in components:
```python
for comp in np.array(components)
```
instead of these two lines?

2020-11-16 13:41 UTC, alexandrkuvaev commented on seismicpro/src/seismic_batch.py
> +    def update_component(self, component, value):
Why `add_components` returns `self`, while this method doesn't?

2020-11-17 09:02 UTC, merged