Vertical Velocity Semblance
gazprom-neft/SeismicPro pull request #38
Opened 2020-11-24 16:36 UTC by anton-br

This PR is adding:
* Veritcal Velocity Semblance
* Residual Semblance 
* Muting.

Also, i want to discuss colors of velocity law line and semblance itself.

Example of current vertical velocity semblance with line represented velocity law:
![image](https://user-images.githubusercontent.com/19351782/100123241-5701ce00-2e8b-11eb-992b-f35fc14441b3.png)

And for residual semblance:
![image](https://user-images.githubusercontent.com/19351782/100123948-16568480-2e8c-11eb-858c-a962bae88066.png)

2020-12-04 14:33 UTC, dpodvyaznikov requested changes

2020-12-04 14:33 UTC, dpodvyaznikov commented on seismicpro/src/seismic_batch.py
> +        mute_time_mx = np.array([mute_samples]*field.shape[1]).T
```suggestion
        mute_mask = (np.arange(field.shape[1]).reshape(1, -1) - mute_samples.reshape(-1, 1)) > 0
```
This way you get array of bools with shape `(mute_samples, field.shape[1])` and can proceed to line 1008
`muted_field = field * mute_mask`

2020-12-07 10:46 UTC, anton-br commented on seismicpro/src/plot_utils.py
> +        if residual:
it wouldn't touch `velocity_law`, only `x_points` has changed. It happend because we want to receive vertical line on residual semblance.

2020-12-07 11:22 UTC, anton-br commented on seismicpro/src/seismic_batch.py
> +            indent /= 1000 # to ms
i beleve you were confused by creating an indent in the form of numpy zeros. In actual version, indent is a velocity that will added to found linear regression coefficient.

2020-12-07 11:27 UTC, anton-br commented on seismicpro/src/seismic_batch.py
> +            poly = np.polyfit(data_x, data_y, deg=2)
i completely removed `interpolation` because i can't find significant difference between `regression` and `interpolation` types in our case.

2020-12-07 11:30 UTC, anton-br commented on seismicpro/src/seismic_batch.py
> +            poly = np.polyfit(data_x, data_y, deg=2)
if you think different, let me know

2020-12-07 14:28 UTC, dpodvyaznikov commented on seismicpro/src/plot_utils.py
> +        if residual:
Sorry, used word "overwrited" incorrectly.
I meant that it is worth mentioning in the docstrings that in case `residual` is `True`, `velocity_law` is ignored.

2020-12-25 16:49 UTC, alexandrkuvaev requested changes

2020-12-25 16:49 UTC, alexandrkuvaev commented on seismicpro/src/seismic_batch.py
> +            poly = np.polyfit(data_x, data_y, deg=1)
This `polyfit` will fit a linear regression, you need `interp1d`

2020-12-27 20:03 UTC, alexandrkuvaev requested changes

2020-12-27 20:03 UTC, alexandrkuvaev commented on seismicpro/src/semblance.py
> +    the upper limit in terms of velocity for calculating the residual semblance and left_boundary is a lower.
Wrong, `left_boundary` and `right_boundary` are left and right boundaries at the last timestamp respectively.

2021-01-27 20:56 UTC, alexandrkuvaev requested changes

2021-01-27 20:56 UTC, alexandrkuvaev commented on seismicpro/src/seismic_batch.py
> +            If array, is an array with elements in format [[time, velocity], ...]. The array contains a set of
Describe units for `time` and `velocity`

2021-01-27 20:56 UTC, alexandrkuvaev commented on seismicpro/src/seismic_batch.py
> +        """ Zeroing seismogram above ``muting`` or ``picking`` times.
```suggestion
        """Set seismogram values above ``muting`` or ``picking`` times to zero.
```

2021-01-27 20:56 UTC, alexandrkuvaev commented on seismicpro/src/seismic_batch.py
> +            Component's name to save muting values.
Muting times sound better for me, but not sure. Also, specify units.

2021-01-27 20:56 UTC, alexandrkuvaev commented on seismicpro/src/seismic_batch.py
> +            # the velocity represents the coefficient of linear regression: `y = x*k`, where y is offsets (in meters)
You also fit bias, update the comment

2021-01-27 20:56 UTC, alexandrkuvaev commented on seismicpro/src/seismic_batch.py
> +            Else, is a component's name with semblance.
With velocities?

2021-01-27 20:56 UTC, alexandrkuvaev commented on seismicpro/src/semblance.py
> +        The first dimention of the `_seismogram` is a trace number, second is a trace's amplitude.
The second dim is time, isn't it?

2021-01-27 20:56 UTC, alexandrkuvaev commented on seismicpro/src/semblance.py
> +            NMO corrected seismogram.
Not a seismogram but a hodograph

2021-01-27 20:56 UTC, alexandrkuvaev commented on seismicpro/src/semblance.py
> +        index : str, optional, by default ''
This method should know nothing about batch external structure

2021-01-27 20:56 UTC, alexandrkuvaev commented on seismicpro/src/semblance.py
> +        return np.max(minmax_self / (minmax_other + 1e-11))
Have you compared this formula to the one used before?

2021-01-27 20:56 UTC, alexandrkuvaev commented on seismicpro/src/semblance.py
> +    to obtain a rectangular matrix of size (time_length, max(right_boundary - left_boundary)), where `left_boundary`
You don't need `max` here if you're talking only about the last timestamp

2021-01-27 20:56 UTC, alexandrkuvaev commented on seismicpro/src/semblance.py
> +        The number of velocities in an array `_velocities`.
```suggestion
        The number of velocities to compute semblance for.
```

2021-01-29 15:14 UTC, dpodvyaznikov requested changes

2021-01-29 15:14 UTC, dpodvyaznikov commented on seismicpro/src/semblance.py
> +    _deviation : float, optional, default 0.2
relative_margin

2021-01-29 15:14 UTC, dpodvyaznikov commented on seismicpro/src/semblance.py
> +    _deviation : float, optional, default 0.2
relative_margin
relative_bound

2021-01-29 15:14 UTC, dpodvyaznikov commented on seismicpro/src/seismic_batch.py
> +        if self.meta[src]['sorting'] != 'offset':
Maybe perform this check before creating a new `dst_muting` component or overwriting existing one?

2021-02-01 11:50 UTC, alexandrkuvaev requested changes

2021-02-01 11:50 UTC, alexandrkuvaev commented on seismicpro/src/seismic_batch.py
> +        stacking_velocities : array-like or str, optional
```suggestion
        stacking_velocities : array-like or str
```

2021-02-01 11:50 UTC, alexandrkuvaev commented on seismicpro/src/seismic_batch.py
> +            stacking velocity to construct the residual semblance.
```suggestion
            Defines a relative velocity margin from the stacking velocity to construct the residual semblance.
```
Sounds more concise.

2021-02-01 11:50 UTC, alexandrkuvaev commented on seismicpro/src/seismic_batch.py
> +            If array-like, see :func:`.semblance.Semblance.plot` for detal description.
```suggestion
            If array-like, see :func:`.semblance.Semblance.plot` for a detailed description.
```

2021-02-01 11:50 UTC, alexandrkuvaev commented on seismicpro/src/seismic_batch.py
> +        kwargs['title'] = '{} {}'.format(kwargs.get('title', ''), index)
```suggestion
        kwargs['title'] = '{} {}'.format(kwargs.get('title', ''), index).strip()
```

2021-02-01 11:50 UTC, alexandrkuvaev commented on seismicpro/src/seismic_batch.py
> +        kwargs['title'] = '{} {}'.format(kwargs.get('title', ''), index)
```suggestion
        kwargs['title'] = '{} {}'.format(kwargs.get('title', ''), index).strip()
```

2021-02-01 11:50 UTC, alexandrkuvaev commented on seismicpro/src/seismic_batch.py
> +            Else is a component's name with stacking_velocities.
If array-like, contains non-decreasing peaked stacking velocities in the following format: [[time, velocity], ...], where time is measured in milliseconds and velocity in meters/second. If `str`, contains a component's name with stacking velocities in the same format.

2021-02-01 11:50 UTC, alexandrkuvaev commented on seismicpro/src/semblance.py
> +            that recorded a trace placed in `_seismogram[i]`.
Rewrite to match class docstring

2021-02-01 11:50 UTC, alexandrkuvaev commented on seismicpro/src/semblance.py
> +        difference on raw CDP gather vertical semblance.
This is the description of the old formula, rewrite to match the new one

2021-02-01 11:50 UTC, alexandrkuvaev commented on seismicpro/src/semblance.py
> +            ixs = np.where(semblance[i])[0]
Rewrite to use precalculated `left_bounds` and `right_bounds`, since this implementation will fail in case of zero semblance values or decreasing stacking velocities.

2021-02-01 13:06 UTC, alexandrkuvaev approved these changes

2021-02-02 13:52 UTC, dpodvyaznikov approved these changes

2021-02-02 14:00 UTC, merged