SeismicPro 2.0
gazprom-neft/SeismicPro pull request #53
Opened 2021-03-31 08:21 UTC by anton-br

This draft will become a pr when the TODO list will be complete:
__Important to change:__
- [ ] Delete all empty functions.
- [ ] Velocity Cube: Fix interpolator.
- [ ] Stack pipeline: Add prefetch with mpc concurrency.
- [ ] Picking pipeline: Check the operating time with prefetch, compare with the old version.
- [ ] SU - fix the creation of attributes, add this named expression to batchflow.
- [ ] Write a proper and convenient transfer of coordinates into Semblance and Velocity Cube.
- [ ] Unify error raising for missing column or wrong sorting when calling methods. Use a decorator or a method for this.
- [ ] Make `split` from dataset work. (Just push your changes, @alexandrkuvaev)
- [ ] Delete `n_jobs` from KNN in Velocity Cube.
- [ ] Add njit to `cartessian_product` and move it to utils.
- [ ] Try to change `ubdate_cube` action to simple `update` from batchflow.
- [ ] Create `init` in seismicpro and restructure files in the repository.
- [ ] Decide what to do with the old SeismicPro version.

__Self check:__
- [ ] Check combined argument in `load`.
- [ ] Normalization
- [ ] `mask_to_pick` - `pick_to_mask`
- [ ] `aggregate_segys`
- [ ] REVISE ALL FILES.

__Bonus activities:__
- [ ] Rename variables and functions. 💅
- [ ] Add docstrings. 🙈

2021-04-13 09:25 UTC, SergeyTsimfer commented on seismicpro/src/gather.py
> +    @batch_method(target="for")
😎

2021-04-13 09:25 UTC, SergeyTsimfer commented on seismicpro/src/utils/general_utils.py
> +    trace_min, trace_max = np.inf, -np.inf
You can use `trace[0]` as starting element

2021-04-13 09:25 UTC, SergeyTsimfer commented on seismicpro/src/utils/general_utils.py
> +    for i in range(len(trace)):
change `range(len())`

2021-04-13 09:25 UTC, SergeyTsimfer commented on seismicpro/src/utils/general_utils.py
> +    picking_list = np.empty(len(mask), dtype=np.int32)
That is not a list

2021-04-13 09:25 UTC, SergeyTsimfer commented on seismicpro/src/velocity_cube.py
> +        min_i, min_x = np.min(self.coords, axis=0) - 1
As this is a possible place of connection of `Seismic Pro` and `seismiQB`, can we unify our namings?

2021-04-13 15:21 UTC, a-arefina commented on seismicpro/src/survey.py
> +    def collect_stats(self, dataset=None, n_samples=100000, quantiles=(0.01, 0.99)):
what about adding depth limits for stats collection? stats from unused depths can spoil nornalization

2021-04-13 15:21 UTC, a-arefina commented on seismicpro/src/survey.py
> +                traces_list.append(trace)
creating n_samples x trace_len empty array in advance can be more efficient

2021-04-13 15:21 UTC, a-arefina commented on seismicpro/src/survey.py
> +    def collect_stats(self, dataset=None, n_samples=100000, quantiles=(0.01, 0.99)):
n_samples -> n_quantiles_samples

2021-04-13 15:21 UTC, a-arefina commented on seismicpro/src/survey.py
> +            self.quantiles.update({q: np.quantile(traces, q) for q in quantiles})
subsequent calls of this method can create quantiles computed with different precision for different n_samples. what about recalculating existing quantiles as well as those listed in arguments?

2021-04-13 15:21 UTC, a-arefina commented on seismicpro/src/survey.py
> +        raise ValueError(f'{q}-th quantile was not calculated, call `Survey.collect_stats` first.')
```suggestion
        raise ValueError(f'{q}-th quantile was not calculated, call `Survey.collect_stats` with `quantiles={q}`.')
```

2021-04-13 15:21 UTC, a-arefina commented on seismicpro/src/survey.py
> +        raise ValueError(f'{q}-th quantile was not calculated, call `Survey.collect_stats` first.')
btw make single float be valid type for `quantiles` argument

2021-04-13 15:21 UTC, a-arefina commented on seismicpro/src/utils/general_utils.py
> +def to_list(obj):
maybe tuple?

2021-04-14 11:55 UTC, SergeyTsimfer commented on seismicpro/src/batch.py
> +    def _init_component(self, *args, dst, **kwargs):
This is copied from one library to the other. Maybe, it is time to at least give it a proper public name? like `preallocate_component`
Also, it is not used in this file, but used in the decorator. Don't forget to clarify it in the docs

2021-04-14 11:55 UTC, SergeyTsimfer commented on seismicpro/src/batch.py
> +    def load(self, src=None, fmt="sgy", components=None, combined=False, **kwargs):
Do you really intend to use the method from the parent class? Maybe, it is better to keep only the logic of seismic data loading here

2021-04-14 11:55 UTC, SergeyTsimfer commented on seismicpro/src/batch.py
> +    def _load_combined_gather(self, index, src, dst, parent_index, **kwargs):
Hard to grasp from where the `parent_index` comes:  it is either hidden behind `kwargs` in `load`, or comes from one of the decorators

2021-04-14 11:55 UTC, SergeyTsimfer commented on seismicpro/src/batch.py
> +        pos = self.index.get_pos(index)
using `get_pos` instead of `get` is not recommended:)

2021-04-14 11:55 UTC, SergeyTsimfer commented on seismicpro/src/index.py
> +        if survey_name not in self.surveys_dict:
trying to `self.surveys_dict[survey_name]` would result in pretty much the same error, if the key is absent

2021-04-14 11:55 UTC, SergeyTsimfer commented on seismicpro/src/index.py
> +    def build_from_surveys(self, surveys, mode, *args, **kwargs):
This `mode` should be visible from the outer signatures: both from `SeismicIndex` and `SeismicDataset` inits

2021-04-14 11:55 UTC, SergeyTsimfer commented on seismicpro/src/index.py
> +            _index = self.build_from_index(index, *args, **kwargs)
Is this branch ever used? This heavily relies on `args`

2021-04-14 11:55 UTC, SergeyTsimfer commented on seismicpro/src/index.py
> +    def build_index(self, index=None, surveys=None, *args, **kwargs):
Two changes, that can be made separately:
 - move more things to `build_index` itself, removing the need to trace the transition of the index from one method to the other (with every of them being named very similarly)
- explicitly return all the things, needed to create the valid `SeismicIndex`, and use them at the end

Something like that:
```python
if index is None and surveys is None:  # Create empty index
    _index = None
elif not isinstance(surveys, (list, tuple)):
    _index, _survey_dict, _headers = self.build_from_survey(surveys)
elif mode in {'m'}:
    _index, _survey_dict, _headers = SeismicIndex.merge(surveys, *args, **kwargs)
elif mode in {'c'}:
    _index, _survey_dict, _headers = SeismicIndex.concat(surveys, *args, **kwargs)

if _index is not None:
    self.surveys_dict = _survey_dict
    self.headers = _headers.loc[_index]

return _index
```

I think, that would greatly reduce the confusion from reading the initialization part of this class: one lengthy function to describe containers, from which we can create `SeismicIndex` + `merge` / `concat` with their utilities.
 No need for 123098213091 `build_**_**` methods.

2021-04-14 11:55 UTC, SergeyTsimfer commented on seismicpro/src/batch.py
> +        getattr(self, dst)[pos] = parent_index.get_gather(survey_name=src, concat_id=index,
Just to be clear and make sure, that I understand it correctly: in your index you can have multiple surveys (that is why you need `survey_name`), and each of them can be a concatenation of multiple surveys itself (that is why you need the `concat_id`), correct?

2021-04-14 11:55 UTC, SergeyTsimfer commented on seismicpro/src/batch.py
> +    def _load_gather(self, index, src, dst, **kwargs):
Really looks like you could win some readability by making a single survey a case of multiple (with n=1) concatenated surveys, both here and in `SeismicIndex`; that would move all the checks / conversions to `get_gather` of `SeismicIndex`, instead of them being all around your codebase

2021-04-14 11:55 UTC, SergeyTsimfer commented on seismicpro/src/batch.py
> +    def update_cube(self, cube, src):
Can't even imagine what this is doing. Also, you can directly do that in Pipeline

2021-04-14 11:55 UTC, SergeyTsimfer commented on seismicpro/src/batch.py
> +    def make_data(self, src, dst, concat_axis=None, stack_axis=None, expand_dims_axis=None):
Is not that supposed to work with multiple `src`? Like, `make_data(src=('amplitudes', 'frequencies'), dst='model_inputs', concat_axis=1)`?

2021-04-14 11:58 UTC, SergeyTsimfer commented on seismicpro/src/index.py
> +    def build_index(self, index=None, surveys=None, *args, **kwargs):
For the sake of unification, you can `self_build_from_survey` -> `SeismicIndex.single(...)`

2021-04-16 13:05 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    for i in range(len(trace)):
Fixed

2021-04-16 13:05 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    picking_list = np.empty(len(mask), dtype=np.int32)
Fixed

2021-04-16 13:07 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        self.headers[key] = val
Yes, since `headers` is a `DataFrame`

2021-04-16 13:10 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        return deepcopy(self)
Yes, it's implicitly called by `add_inplace_arg` decorator

2021-04-16 13:11 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        self.segy_handler = segyio.open(self.path, ignore_geometry=True)
It is automatically set by `ignore_geometry` flag

2021-04-16 16:37 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +    def update_cube(self, cube, src):
Renamed

2021-04-19 14:53 UTC, a-arefina commented on seismicpro/src/index.py
> +    def build_index(self, index=None, surveys=None, *args, **kwargs):
A small improvement of Sergey's code, without the last `_index` check:

```
if index is None and surveys is None: # Create empty index 
     return None 
elif ...

self.surveys_dict = _survey_dict 
self.headers = _headers.loc[_index] 
return _index

```

2021-04-19 14:53 UTC, a-arefina commented on seismicpro/src/index.py
> +    def build_from_survey(self, survey):
I feel a bit uneasy that building index from a single survey and from multiple surveys is implemented so differently.
Is there a way to unify these two methods?

2021-04-19 14:53 UTC, a-arefina commented on seismicpro/src/decorators.py
> +def validate_gather(required_header_cols=None, required_sorting=None):
Does this validation really need to be decorator? why not simply use it as a method in the beginning of corresponding methods?

```
    @batch_method(target="threads")
    def calculate_semblance(self, velocities, win_size=25):
        self.validate_gather(required_sorting="offset")
        return Semblance(gather=self.data, times=self.samples, offsets=self.offsets,
                         velocities=velocities, win_size=win_size,
                         inline=self.supergather_inline, crossline=self.supergather_crossline)

```

2021-04-19 20:32 UTC, SergeyTsimfer commented on seismicpro/src/gather.py
> +    def scale_standard(self, tracewise=True, use_global=False, eps=1e-10):
Please, name it `normalize` instead of `scale`: the latter word is really useful for other situations

2021-04-20 10:40 UTC, a-arefina commented on seismicpro/src/decorators.py
> +                    raise ValueError(err_msg.format(", ".join([str(t) for t in src_type_set])))
```suggestion
                    err_msg = f"All elements in {src} component must have the same type, but {", ".join(map(str, src_type_set))} found"
                    raise ValueError(err_msg)
```

2021-04-20 10:40 UTC, a-arefina commented on seismicpro/src/decorators.py
> +def create_batch_methods(*component_classes):
I dream of a good docstring, that describes all implicitely added arguments

2021-04-20 10:40 UTC, a-arefina commented on seismicpro/src/batch.py
> +    def load(self, src=None, fmt="sgy", components=None, combined=False, **kwargs):
since we cannot mix the types of loaded data here, and we are not redirecting the load to corresponding classes, what about adding separate `load_gather`, `load_muting` methods, for the sake of clarity?

2021-04-20 10:40 UTC, a-arefina commented on seismicpro/src/batch.py
> +        cube.update(getattr(self, src))
Why is this method not in VelocityCube class?

2021-04-20 10:40 UTC, a-arefina commented on seismicpro/src/utils/file_utils.py
> +    if not in_paths:
```suggestion
    if len(in_paths) == 0:
```

2021-04-20 10:40 UTC, a-arefina commented on seismicpro/src/utils/file_utils.py
> +        _ = [source_handler.mmap() for source_handler in source_handlers]
I would better avoid creating the list for side-effects only. what about a simple for-loop?

2021-04-20 10:40 UTC, a-arefina commented on seismicpro/src/named_expr.py
> +            self.__dict__[name] = value
```suggestion
            self.component = value
```
??

2021-04-20 10:49 UTC, a-arefina commented on seismicpro/src/decorators.py
> +def apply_to_each_component(*args, target="for", fetch_method_target=True):
As for now, `fetch_method_target` is set to false twice, and the default value is used only once in another decorator, so what about switching the default?

2021-04-20 16:26 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +            self.quantiles.update({q: np.quantile(traces, q) for q in quantiles})
Fixed by calculating all the q-quantiles with given precision

2021-04-20 16:27 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +    def collect_stats(self, dataset=None, n_samples=100000, quantiles=(0.01, 0.99)):
Added `has_stats` flag, which is checked by all gather normalization methods

2021-04-20 16:27 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        for i, pos in tqdm(enumerate(traces_pos), desc="Calculating statistics", total=len(traces_pos)):
Added `bar` argument to match `aggregate_segys` naming

2021-04-20 16:31 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        raise ValueError(f'{q}-th quantile was not calculated, call `Survey.collect_stats` first.')
Valid now, the error message has been changed

2021-04-23 14:42 UTC, alexandrkuvaev commented on seismicpro/src/decorators.py
> +
Simplified

2021-04-23 14:46 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +        survey_index = slice(survey_index, survey_index)
Fixed

2021-04-23 14:47 UTC, alexandrkuvaev commented on seismicpro/src/decorators.py
> +def get_class_methods(cls):
Added

2021-04-26 08:26 UTC, alexandrkuvaev commented on seismicpro/src/decorators.py
> +            src_target = target  # set default target
Renamed to `src_method_target`

2021-04-26 08:27 UTC, alexandrkuvaev commented on seismicpro/src/decorators.py
> +            if "target" in kwargs:  # fetch target from passed kwargs
Reordered and simplified

2021-04-26 08:29 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +        _ = [source_handler.mmap() for source_handler in source_handlers]
Fixed

2021-04-26 08:30 UTC, alexandrkuvaev commented on seismicpro/src/decorators.py
> +def apply_to_each_component(*args, target="for", fetch_method_target=True):
The logically correct default value is `True`, kept as is

2021-04-26 09:03 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +        cube.update(getattr(self, src))
Renamed to `velocity_cube`

2021-04-26 09:55 UTC, alexandrkuvaev commented on seismicpro/src/decorators.py
> +                    raise ValueError(err_msg.format(", ".join([str(t) for t in src_type_set])))
Done

2021-04-26 16:36 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +    def plot(self):
Added

2021-04-26 20:17 UTC, dpodvyaznikov commented on seismicpro/src/gather.py
> +    def correct_gather(self, velocity_model):
Why not `apply_nmo`?

2021-04-27 09:46 UTC, dpodvyaznikov commented on seismicpro/src/gather.py
> +    def correct_gather(self, velocity_model):
I think this method requires `@validate_gather()` for being cdp-like with unique inline / crossline. 
Otherwise `velocity_model` gets two None's from `_get_unique_header_val` and fails.

2021-04-29 10:13 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +    def load_trace(self, index, limits, trace_length):
Refactored completely

2021-04-29 10:17 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        if trace_length == 0:
`trace_length` is computed outside `load_trace` to increase performance by doing it just once for the whole gather

2021-04-29 10:18 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        if not isinstance(limits, slice):
Hopefully not, all the limits processing logic is now moved to `_process_limits` method

2021-04-29 10:18 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +    def collect_stats(self, dataset=None, n_samples=100000, quantiles=(0.01, 0.99)):
Done

2021-04-29 10:18 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +                traces_list.append(trace)
Done

2021-04-29 10:26 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        self.data = data
Current `Gather` methods make no sense without preloaded data: all headers manipulation can be performed in `Survey` directly. Moreover, `Gather` is not supposed to be created outside the corresponding `Survey`, that's why all trace loading logic is performed in `Survey`, not in `Gather`.

Suggested gather slicing will be implemented in further pull requests.

2021-04-30 14:11 UTC, alexandrkuvaev commented on seismicpro/src/index.py
> +    def build_index(self, index=None, surveys=None, *args, **kwargs):
Completely rewritten

2021-04-30 14:14 UTC, alexandrkuvaev commented on seismicpro/src/index.py
> +    def build_from_survey(self, survey):
No, since multiple surveys are first converted to indices by `from_survey` method and only then merged or concatenated

2021-04-30 14:21 UTC, alexandrkuvaev commented on seismicpro/src/index.py
> +    def build_from_surveys(self, surveys, mode, *args, **kwargs):
Done

2021-05-27 15:18 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +class Survey:
Done

2021-05-27 15:22 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +    def collect_stats(self, dataset=None, n_samples=100000, quantiles=(0.01, 0.99)):
Renamed to `n_quantile_traces`

2021-05-27 15:24 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +    def correct_gather(self, velocity_model):
Renamed to `apply_nmo`

2021-05-27 15:24 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +            return None
Completely rewritten

2021-05-27 15:27 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +    def scale_standard(self, tracewise=True, use_global=False, eps=1e-10):
Decided to keep 3 separate methods and call them `scale_*`

2021-05-31 15:48 UTC, a-arefina commented on seismicpro/src/utils/plot_utils.py
> +    set_ticks(ax=ax, img_shape=metrics_map.T.shape, ticks_range_x=ticks_range_x,
```suggestion
    set_ticks(ax=ax, img_shape=metrics_map.shape[::-1], ticks_range_x=ticks_range_x,
```

2021-05-31 15:48 UTC, a-arefina commented on seismicpro/src/velocity_cube.py
> +        index = self.nearest_interpolator.kneighbors([(inline, crossline),], return_distance=False).item()
```suggestion
        index = self.nearest_interpolator.neighbors([(inline, crossline),], return_distance=False).item()
```
couldn't find documentation on this, but such spelling is suspicious. Did you run this piece of code?

2021-05-31 15:48 UTC, a-arefina commented on seismicpro/src/velocity_cube.py
> +        if (self.times is not None) or (self.velocities is not None):
this is always true, because `self.times` is an np.array

2021-05-31 15:48 UTC, a-arefina commented on seismicpro/src/velocity_cube.py
> +    def get_coords(self):
what about a property?

2021-05-31 15:48 UTC, a-arefina commented on seismicpro/src/velocity_cube.py
> +        if any((vel.inline is None) or (vel.crossline is None) for vel in stacking_velocities):
`(vel.inline is None) or (vel.crossline is None)` - this could be a StackingVelocity method

2021-05-31 15:48 UTC, a-arefina commented on seismicpro/src/velocity_cube.py
> +        self.interpolator = VelocityInterpolator(self.stacking_velocities_dict)
what about updating self.interpolator in `update` method above to keep it concictent with self.stacking_velocities_dict?

2021-05-31 15:48 UTC, a-arefina commented on seismicpro/src/velocity_model.py
> +    times_ix = np.linspace(0, len(times) - 1, n_times).astype(np.int64)
what about int32?

2021-06-02 10:52 UTC, alexandrkuvaev commented on seismicpro/src/decorators.py
> +def validate_gather(required_header_cols=None, required_sorting=None):
Decided to make it a gather method

2021-06-02 10:54 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +    @add_inplace_arg
Made it a function

2021-06-02 10:55 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +    def correct_gather(self, velocity_model):
Fixed

2021-06-02 11:55 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +        return [[index] for index in self.indices.values.tolist()]
Even `.values` is redundant, simplified

2021-06-02 12:09 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +            'vmax': np.quantile(self.data, 0.9),
This won't make an image zero-centered if all the amplitudes have one sign, e.g. after min-max normalization. Kept as is.

2021-06-02 12:11 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +            load_headers.remove(self.TRACE_ID_HEADER)
Discussed to keep it as is since it is the intended behavior

2021-06-02 12:13 UTC, alexandrkuvaev commented on seismicpro/src/utils/plot_utils.py
> +    set_ticks(ax=ax, img_shape=metrics_map.T.shape, ticks_range_x=ticks_range_x,
Kept as is, more readable and matrix transposition is a cheap operation

2021-06-02 12:14 UTC, alexandrkuvaev commented on seismicpro/src/velocity_cube.py
> +        index = self.nearest_interpolator.kneighbors([(inline, crossline),], return_distance=False).item()
I did, it works :cry:

2021-06-02 12:18 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +    TRACE_ID_HEADER = 'TRACE_SEQUENCE_FILE'
Done

2021-06-02 19:48 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +            load_headers.remove(self.TRACE_ID_HEADER)
Done

2021-06-02 19:48 UTC, alexandrkuvaev commented on seismicpro/src/velocity_cube.py
> +        if (self.times is not None) or (self.velocities is not None):
Completely rewritten

2021-06-02 19:49 UTC, alexandrkuvaev commented on seismicpro/src/velocity_cube.py
> +    def get_coords(self):
Made it a method to match `get_coords` from `Gather` and `Semblance`

2021-06-02 19:49 UTC, alexandrkuvaev commented on seismicpro/src/velocity_cube.py
> +        if any((vel.inline is None) or (vel.crossline is None) for vel in stacking_velocities):
Done

2021-06-02 19:50 UTC, alexandrkuvaev commented on seismicpro/src/velocity_cube.py
> +        self.interpolator = VelocityInterpolator(self.stacking_velocities_dict)
Takes lots of time to perform triangulation on each iteration. Now the interpolator is automatically created on request, tracking changes in `stacking_velocities_dict`

2021-06-02 20:00 UTC, alexandrkuvaev commented on seismicpro/src/velocity_model.py
> +    times_ix = np.linspace(0, len(times) - 1, n_times).astype(np.int64)
Numba treats python int values as `int64`, that's why cast to `int32` will require manually changing types for constants in the code. Kept as is.

2021-06-15 10:08 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +            VFUNC(inline, crossline, data[::2], data[1::2])
Done

2021-06-15 13:08 UTC, anton-br commented on seismicpro/src/batch.py
> +            ValueError(f'dst must be `str` or `SU named expression`, not {type(dst)}.')
`SU` is never dead, ~so~ `SU` always lives in our hearts...

2021-06-21 13:53 UTC, alexandrkuvaev commented on seismicpro/benchmark/target_benchmark.py
> +def benchmark_method(method, dataset, targets, batch_sizes, n_iters=10, root_ppl=None, notifier_monitors=None,
Completely rewritten

2021-06-23 14:44 UTC, SergeyTsimfer commented on seismicpro/__init__.py
> +__version__ = "0.1.0"
Is time for `2.0`?

2021-06-30 10:58 UTC, anton-br commented on seismicpro/src/tests/dump_merge_test.py
> +    dumped_survey_headers = (dumped_survey.headers.reset_index()
` dumped_survey_headers = (dumped_survey.headers.reset_index`

2021-06-30 11:15 UTC, alexandrkuvaev requested changes

2021-06-30 11:15 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +    spec.format = kwargs.get('format', 5)
Add a comment about 5 here, probably should not be even popped from `kwargs`

2021-06-30 11:15 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +    spec.samples = np.arange(samples)
`sample_rate` should be definitely used during `samples` calculation

2021-06-30 11:15 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +    # and multiplied by a factor of two for a safe margin since it does not affect segy's size on disk
Why?

2021-06-30 11:15 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +    num_active_recievers = np.sum(calc_active_recievers_mask(sx, sy, reciever_coords, activation_dist))
If I understand correctly, you calculate the number of active receivers for the first shot and take it as an estimate for all other shots. Are you sure in such an approach, the first shot is located in the corner of the field and usually has fewer receivers activated?

Why not perform a fair computation?

2021-06-30 11:15 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +    # Parse headers' kwargs
Add these parameters directly to the signature

2021-06-30 11:15 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +            for FieldRecord, (sx, sy) in enumerate(source_coords):
Merge in one line, just `tqdm(enumerate(...))` without `bar.update`

2021-06-30 11:15 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +                active_recievers = reciever_coords[mask, :]
```python
active_recievers = reciever_coords[mask]
```

2021-06-30 11:15 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +                    offset = int(((sx-rx)**2 + (sy-ry)**2)**0.5) # `int` is faster
Is faster than what?

2021-06-30 11:15 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +                    trace = trace_gen(FieldRecord=FieldRecord, TraceNumber=TraceNumber, SourceX=sx, SourceY=sy,
Think of creating a headers dict above and passing it by `**headers` here. Also pass all `kwargs` to a `trace_gen`

2021-07-21 10:28 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +    def make_data(self, src, dst, concat_axis=None, stack_axis=None, expand_dims_axis=None):
No

2021-07-21 10:29 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +    def make_data(self, src, dst, concat_axis=None, stack_axis=None, expand_dims_axis=None):
Renamed

2021-07-21 10:29 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +    def split_results(self, src, dst, shapes):
Renamed

2021-07-21 10:30 UTC, alexandrkuvaev commented on seismicpro/__init__.py
> +__version__ = "0.1.0"
Done

2021-07-21 14:28 UTC, merged