Tutorials and synthetic data generator
gazprom-neft/SeismicPro pull request #59
Opened 2021-08-15 08:59 UTC by dpodvyaznikov

2021-11-03 11:30 UTC, alexandrkuvaev requested changes

2021-11-03 11:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +def trace_generator(times=np.array((10,700,1200)), reflections=np.array((6,-12,8)),
```suggestion
def generate_trace(times=np.array((10,700,1200)), reflections=np.array((6,-12,8)),
```

2021-11-03 11:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +    samples = kwargs.get('TRACE_SAMPLE_COUNT')
rename to `n_samples` to match `make_prestack_segy` naming

2021-11-03 11:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +    inline3d = kwargs.get('INLINE_3D')
inline_3d

2021-11-03 11:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +    offset = kwargs.get('offset')
+

2021-11-03 11:30 UTC, alexandrkuvaev commented on tutorials/utils.py
> +def histogram_plotter(gather_list, bins=41):
```suggestion
def plot_histogram(gather_list, bins=41):
```

2021-11-03 11:30 UTC, alexandrkuvaev commented on tutorials/utils.py
> +    for i in range(n_plots):
Use `enumerate`

2021-11-03 11:30 UTC, alexandrkuvaev commented on tutorials/utils.py
> +        ax[i].set_xlabel('values')
```suggestion
        ax[i].set_xlabel('amplitude')
```

2021-11-03 11:30 UTC, alexandrkuvaev commented on tutorials/utils.py
> +        _ = ax[i].hist(gather_list[i][0].data.ravel(), bins=bins)
Add `plt.show()` in the end of the method

2021-11-03 11:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +        Times of a reflection events measured in samples.
Note, that it is a zero-offset time

2021-11-03 11:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +    time : 1d-darray, defaults to (10, 700, 1200)
`reflection_times`? `event_times`?

2021-11-03 11:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +                    velocities=np.array((1.6,2.,2.4)), points=50, a=5, **kwargs):
Do you really need the defaults to be arrays?

2021-11-03 11:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +    reflectivity : 1d-darray, defaults to (0.5, 4, 1)
`reflection_amplitudes`?

2021-11-03 11:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +    velocity : 1d-darray, defaults to (1.6, 2., 2.4)
Also rename, no clue about what velocity you use here.

2021-11-03 11:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +        Parameter of `scipy.signal.ricker` function.
Rename and describe what these parameters actually do.

2021-11-03 11:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +    reflections = reflections * (1 + 10 / (10 + inline3d))
Definitely some kind of magic here...

2021-11-03 11:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/file_utils.py
> +    trace += np.convolve(ref_series, signal.ricker(points, a), mode='same')[:samples]
Why adding to `zeros` if you can simply `convolve`?

2021-11-03 12:23 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>refresh the memory of -&gt; brush up on</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='6'/>

2021-11-03 12:23 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>allows keeping</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='8'/>

2021-11-03 12:23 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>objects store dataframes</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='14'/>

2021-11-03 12:23 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>each having;</p><p>is indexed and contains</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='18'/>

2021-11-03 12:23 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>sources -&gt; energy sources</p><p>with same value -&gt; by the same value</p><p>below - to the end of the sentence</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='19'/>

2021-11-03 12:23 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>Unify code highlighting with backquotes</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='23'/>

2021-11-03 12:23 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>that satisfy</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='35'/>

2021-11-03 12:23 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>contain the new</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='43'/>

2021-11-03 12:23 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>allow performing</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='49'/>

2021-11-03 18:37 UTC, dpodvyaznikov commented on .github/workflows/status.yml
> +        apt update
This is no longer required

2021-11-03 18:38 UTC, dpodvyaznikov commented on seismicpro/src/utils/file_utils.py
> +    """Generates a seismic trace using reflectivity parameters and traces' headers.
```suggestion
    """Generates a seismic trace using reflectivity parameters and trace's headers.
```

2021-11-03 18:53 UTC, dpodvyaznikov commented
<p>importan - important</p>

---

 <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-11-09 08:56 UTC, dpodvyaznikov commented on seismicpro/src/utils/file_utils.py
> +    offset = kwargs.get('offset')
Offsets are mandatory in segy headers, and `make_prestack_segy` always writes them.

You might not need to offsets for trace generation, e.g., if you fill traces with random noise.

2021-11-12 10:52 UTC, dpodvyaznikov commented
Requires #64 for better plotters

2021-11-12 16:09 UTC, nikita-klsh commented on tutorials/utils.py
> +    shifted_times = ((times**2 + offset**2 / (velocities * (sample_rate / 1000))**2)**0.5).astype(int)
Looks like you can pass not a single but an array of  `offsets`, and operations are broadcasted to generate times for the whole gather. 
Consider `generate_trace` -> `generate_gather`
In  `make_prestack_segy`, where this function is used, we actually want to generate the whole gathers.
Moreover, the parameter `zero offset reflections times` makes more sense in the context of `gather`, not `trace`

2021-11-19 13:43 UTC, a-arefina commented on tutorials/utils.py
> +def plot_histogram(gathers, bins=60):
```suggestion
def plot_histograms(gathers, bins=60):
```

2021-11-19 13:43 UTC, a-arefina commented on tutorials/utils.py
> +    for i, (gather, title) in enumerate(gathers):
```suggestion
    for ax, (gather, title) in zip(axs, gathers):
```

2021-11-19 14:11 UTC, a-arefina commented
I've made some comments in reviewnb, but they were not saved :((

All in all, the tutorials are definetely more clear than they were when I looked at them before, but they still need to be checked by Grammarly - there are too many issues that make the texts less understandible :(

2022-02-15 10:08 UTC, a-arefina commented on tutorials/utils.py
> +    velocities = np.array(nmo_velocity)
add a check that they all have same lengths

2022-02-15 10:27 UTC, a-arefina commented on tutorials/1_Survey_tutorial.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    survey.collect_stats()
</pre><p>In latest master we need to call <code>mark_dead_traces</code>  prior to <code>collect_stats</code>,  otherwise a warning is raised. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='42'/>

2022-02-15 14:08 UTC, dpodvyaznikov commented on tutorials/utils.py
> +        Dict with trace header values.
This function is used by `make_prestack_segy`, and all the parameters and units are described there

2022-02-15 14:18 UTC, dpodvyaznikov commented on tutorials/utils.py
> +    offset = kwargs.get('offset')
This function should be used with `make_prestack_segy`, and its used solely to prettify visualizations in tutorials

2022-02-15 15:23 UTC, dpodvyaznikov commented
<p>IMO, it makes more sense to mention it when talking about pipelines and batch-wise processing</p>

---

 <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2022-03-31 09:37 UTC, alexandrkuvaev commented
<p>+, maybe even without ;</p>

---

 <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2022-03-31 09:39 UTC, anton-br commented on tutorials/utils.py
> +
delete empty line

2022-03-31 09:39 UTC, anton-br commented on tutorials/utils.py
> +    n_samples = kwargs.get('TRACE_SAMPLE_COUNT')
add necessary trace headers to the docs

2022-03-31 09:39 UTC, alexandrkuvaev commented
<p>should be better now: compare x axis limits of the plots.</p>

---

 <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2022-03-31 09:41 UTC, alexandrkuvaev requested changes

2022-03-31 09:41 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p><code>Survey</code> is a concise image of a SEG-Y file, thus it's useful to brush up on the format first.</p><p> </p><ul><li>"Since" is inappropriate here as for me, you've just introduced the class</li><li>"its" may be confused with the <code>Survey</code></li></ul><p> </p><p>Move bullet list below as described in the next comment.</p><p> </p><p>Also, I'd change "information about each trace" to "medatada" to not be confused with the recorded trace itself</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='6'/>

2022-03-31 09:41 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>SEG-Y files are binary an have the following data layout:</p><p>&lt;image&gt;</p><p> It consists of three main sections:</p><p>&lt;bullet list&gt;</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2022-03-31 09:41 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>Data<strong>F</strong>rame when you refer to the class everywhere in the notebook.</p><p> </p><p><code>header_index</code> is one or more trace header names that will be used to group individual traces into gathers as will be shown below. They will also be used as an index of the <code>headers</code> DataFrame. <code>header_cols</code> represent additional trace headers to load to further be available in gather processing pipelines.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='14'/>

2022-03-31 09:41 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p><code>headers</code> Dataframe indexed by <code>FieldRecord</code> and containing <code>offset</code> values for each trace. - I'd remove this sentence, duplicates what was already said.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='22'/>

2022-03-31 09:41 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p><code>samples</code> or <code>times</code> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='25'/>

2022-03-31 09:41 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>In example below <code>offset</code> is doubled and the result is stored in a new <code>offset_x2</code> column. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='35'/>

2022-03-31 09:41 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>remove</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='37'/>

2022-03-31 09:41 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>Code suggestion: I'd also raise a warning if <code>mark_dead_traces</code> was called, but <code>n_dead_traces</code> is not 0  </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='43'/>

2022-03-31 09:41 UTC, alexandrkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>Code suggestion: let's rename <code>stats_limits</code> to <code>limits</code>. <code>stats_limits</code> name was used when <code>collect_stats</code> could be called implicitly from <code>init</code> in order not to confuse these limits with <code>limits</code> of the survey. Now it looks strange: in all the methods (even) in <code>mark_dead_traces</code> we call them <code>limits</code>.</p><p> </p><p>Also the docs should be fixed a bit, now it says that <code>If not given, whole traces are used.</code> in both <code>collect_stats</code> , <code>mark_dead_traces</code> , <code>load_gather</code> , <code>get_gather</code> and <code>sample_gather</code> which is incorrect: <code>Default survey limits are used</code>.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='46'/>

2022-04-28 10:01 UTC, alexanderkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
Covered in https://github.com/gazprom-neft/SeismicPro/pull/94

2022-04-28 10:02 UTC, alexanderkuvaev commented on tutorials/1_Survey_tutorial.ipynb
> +{
Covered in https://github.com/gazprom-neft/SeismicPro/pull/94

2022-04-29 10:51 UTC, dpodvyaznikov commented on README.md
> +## Tutorials
Every other link of the README's top bar leads to a header in README, while `Tutorials` was redirecting somewhere esle.
I don't like that inconsistency, and that is why I've added this header

2022-04-29 10:51 UTC, dpodvyaznikov commented on tutorials/utils.py
> +
Done

2022-04-29 10:57 UTC, dpodvyaznikov commented on tutorials/utils.py
> +    n_samples = kwargs.get('TRACE_SAMPLE_COUNT')
Done

2022-04-29 11:05 UTC, dpodvyaznikov commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>Done</p>

2022-04-29 11:09 UTC, dpodvyaznikov commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>Done</p>

2022-04-29 11:10 UTC, dpodvyaznikov commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>Done</p>

2022-04-29 11:11 UTC, dpodvyaznikov commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>Done</p>

2022-04-29 11:22 UTC, dpodvyaznikov commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>Done</p>

2022-04-29 11:22 UTC, dpodvyaznikov commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>Done</p>

2022-04-29 11:23 UTC, dpodvyaznikov commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>Done</p>

2022-04-29 11:24 UTC, dpodvyaznikov commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>Done</p>

2022-04-29 11:24 UTC, dpodvyaznikov commented on tutorials/1_Survey_tutorial.ipynb
> +{
<p>Done</p>

2022-04-29 12:00 UTC, dpodvyaznikov commented
<p>Done</p>

---

 <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2022-04-29 13:49 UTC, dpodvyaznikov commented
<p>Done</p>

---

 <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2022-04-29 13:52 UTC, dpodvyaznikov commented
<p>It is None until <code>sort</code> is called, so quite useless until here</p>

---

 <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2022-04-29 13:57 UTC, dpodvyaznikov commented
<p>Done</p>

---

 <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2022-05-04 10:26 UTC, dpodvyaznikov commented
<p>Done</p>

---

 <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2022-05-04 10:27 UTC, dpodvyaznikov commented
<p>Done</p>

---

 <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2022-05-04 10:27 UTC, dpodvyaznikov commented
<p>Done</p>

---

 <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/59/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2022-05-04 12:09 UTC, anton-br commented on README.md
> +## Tutorials
Okay, then consider adding links to tutorials notebooks and their descriptions in this section. I think we don't need to redirect user twise.

2022-05-04 17:54 UTC, alexanderkuvaev requested changes

2022-05-04 17:54 UTC, alexanderkuvaev commented on tutorials/utils.py
> +    reflection_event_time : 1d-darray, defaults to (20, 1400, 2400)
```suggestion
    reflection_event_times : 1d np.ndarray, defaults to (20, 1400, 2400)
```
Same for other args

2022-05-04 17:54 UTC, alexanderkuvaev commented on tutorials/utils.py
> +        Overall lenght of the vector with Ricker vawelet. Equivalent of `points` parameter of `scipy.signal.ricker`.
```suggestion
        Overall lenght of the vector with Ricker wavelet. Equivalent of `points` parameter of `scipy.signal.ricker`.
```

2022-05-04 17:54 UTC, alexanderkuvaev commented on tutorials/utils.py
> +    """Generates a seismic trace using reflectivity parameters and trace's headers with Ricker impulse.
```suggestion
    """Generates a seismic trace with Ricker impulse using reflectivity parameters and trace's headers.
```
Less confusing as for me

2022-05-30 20:50 UTC, alexanderkuvaev approved these changes

2022-05-31 15:13 UTC, merged