Update batchflow and rewrite benchmark
gazprom-neft/SeismicPro pull request #61
Opened 2021-08-19 12:42 UTC by anton-br

* Update batchflow to the current master,
* Rewritten benchmark to new Research,
* Fixed tests for Windows platform.

2021-11-03 10:38 UTC, alexandrkuvaev requested changes

2021-11-03 10:38 UTC, alexandrkuvaev commented on seismicpro/benchmark/benchmark.py
> +    # pylint: disable=too-many-arguments
Is it still valid?

2021-11-03 10:38 UTC, alexandrkuvaev commented on seismicpro/benchmark/benchmark.py
>          method_pipeline = getattr(Pipeline(), self.method_name)(target=C('target'), **method_kwargs)
Probably target should follow kwargs

2021-11-03 10:38 UTC, alexandrkuvaev commented on seismicpro/benchmark/benchmark.py
> +        self.template_pipeline = (root_pipeline + method_pipeline) << dataset
Maybe just `getattr` `method_name` from root pipeline instead of summation?

2021-11-03 10:38 UTC, alexandrkuvaev commented on seismicpro/benchmark/benchmark.py
>          results_df.set_index(['target', 'batch_size'], inplace=True)
Why do you need `dtype` casting? Also why not `set_index` first and then sort it?
Anyway, I'd chain these methods in one line

2021-11-03 10:38 UTC, alexandrkuvaev commented on seismicpro/benchmark/benchmark.py
> +        for col_name, column in results.iteritems():
Can't it be simplified using `DataFrame.plot`?

2021-11-03 10:38 UTC, alexandrkuvaev commented on seismicpro/src/tests/benchmark_test.py
> +                            ('sort', dict(src='raw', by='offset'), Pipeline().load(src='raw', fmt='sgy'))))
```suggestion
                             ('sort', dict(src='raw', by='offset'), Pipeline().load(src='raw', fmt='sgy'))))
```

2021-11-03 10:38 UTC, alexandrkuvaev commented on seismicpro/src/tests/benchmark_test.py
> +    def test_that_benchmark_runs_completely(self, segy_path, method_name, method_kwargs, root_pipeline):
```suggestion
    def test_benchmark_runs(self, segy_path, method_name, method_kwargs, root_pipeline):
```
?

2021-11-03 10:38 UTC, alexandrkuvaev commented on seismicpro/src/tests/benchmark_test.py
> +    @pytest.mark.parametrize('method_name,method_kwargs,root_pipeline',
Can spaces be added after commas?

2021-11-03 14:53 UTC, dpodvyaznikov commented on seismicpro/benchmark/benchmark.py
> +            pipeline.run(C('batch_size'), n_iters=n_iters, shuffle=42, drop_last=True, notifier=False, profile=True)
Do you want to fix shuffle seed? Do you need shuffle here at all?

2021-11-03 14:53 UTC, dpodvyaznikov commented on seismicpro/benchmark/benchmark.py
>          """Plot a graph of time verus `batch_size` for every `targets`.
```suggestion
        """Plot a graph of time verus `batch_size` for every `target`.
```

2021-11-10 13:16 UTC, alexandrkuvaev approved these changes

2021-11-12 09:21 UTC, dpodvyaznikov commented on seismicpro/src/tests/benchmark_test.py
>  # 1. Add tests that check corectness of benchmark.
Wouldn't they differ on different hard \ software?

2021-11-12 09:25 UTC, merged