Add plotter
gazprom-neft/SeismicPro pull request #64
Opened 2021-10-01 15:44 UTC by anton-br

Update plotter

2021-11-12 13:44 UTC, nikita-klsh commented on seismicpro/src/gather.py
> +UNITS = {
It looks more like axis labels, not units. 
Leave fait units here, and add brackets inside plot function

2021-11-15 14:23 UTC, nikita-klsh commented on seismicpro/src/utils/plot_utils.py
> +    if num is not None:
this logic is implemented in  `matplotlib.ticker.LinearLocator`

2021-11-18 13:54 UTC, a-arefina commented on seismicpro/src/batch.py
> +                    title["label"] = label.format(src=src, index=index, **format_kwargs)
can `format_kwargs` be different for different items in a batch? If yes, please add an example to the tutorial

I think that title formatting code up to this line can be moved outside this for-loop, This can allow to simplyfy the code

2021-11-18 13:54 UTC, a-arefina commented on seismicpro/src/utils/plot_utils.py
> +def plot_arg_to_dict(arg):
the name of this function is extremely obscure

I propose to use its body as is, at least when followed by `val = result.pop('label')

2021-11-18 13:54 UTC, a-arefina commented on seismicpro/src/decorators.py
> +def plotter(figsize, args_to_unpack=None):
Please rename `figsize` parameter to reflect the fact that this is the size of a single subplot.

2021-11-19 11:52 UTC, a-arefina commented on seismicpro/src/gather.py
> +    def _parse_headers_kwargs(headers_kwargs, headers_key):
The only place where this method is used is in `_plot_headers` and `headers_key` is hard-coded there. Do you really need it as a parameter? Dropping it will simplify the code dramatically

2021-11-19 11:52 UTC, a-arefina commented on seismicpro/src/gather.py
> +        for kwargs in headers_kwargs:
please change the naming. `for smth in some_kwargs` is seen as iterating over some dictionary's keys, but `header_kwargs` is a  list here

2021-11-19 11:52 UTC, a-arefina commented on seismicpro/src/gather.py
> +        top_ax.scatter(np.arange(self.n_traces), header_values, s=5, color="black")
I do think that there is too much kwargs routing in this PR, but for super large or super small subplots the default size of scatter can be not suitable. So you also need to provide the ability to change it

2021-11-19 11:52 UTC, a-arefina commented on seismicpro/src/semblance.py
> +        ax.figure.colorbar(img, ticks=levels[1::2], ax=ax)
colorbars in Gather use divider.append_axes. Why is it not used here?

2021-11-19 11:52 UTC, a-arefina commented on seismicpro/src/semblance.py
> +             x_ticker=None, y_ticklabels=None, y_ticker=None, ax=None, grid=False,
in Geather tick_labels are inside x/y_ticker, not as separate parameters

2021-11-23 12:16 UTC, anton-br commented on seismicpro/src/gather.py
> +    def plot(self, mode="seismogram", scatter_headers=None, top_subplot_header=None, title=None,
> Why not boolean flag for wiggle mode?

Because soon we add the third mode - histogram. We don't want to create a lot's of flags here 

> Can we unify namings for scatter_headers and top_subplot_header:

Any suggestions on naming are welcome :)

2021-11-23 12:16 UTC, anton-br commented on seismicpro/src/gather.py
> +    def _plot_seismogram(self, ax, divider, colorbar=False, **kwargs):
idk, let's vote :)

2021-11-23 12:18 UTC, anton-br commented on seismicpro/src/gather.py
> +        color = ["black"] if color is None else to_list(color)
I've used it once) but I rather leave it as this, since it doesn't complicate the code too much.

2021-11-29 12:34 UTC, anton-br commented on seismicpro/src/utils/plot_utils.py
> +    elif step_ticks is not None:
not exactly. First of all, there is no proper `Formatter` for it. `IndexForatter` is already deprecated and I don't want to use `FuncFormatter`.
Secondly.
We can write this logic using `IndexLocator` and infer labels using `locator.tick_values()` but IMO we won't win neither in the number of lines, nor in clarity

2021-11-29 12:36 UTC, anton-br commented on seismicpro/src/utils/plot_utils.py
> +    num = 10 if num is None and step_ticks is None and step_labels is None else num
here you are right, I'll try to change it

2021-11-29 13:37 UTC, anton-br commented on seismicpro/src/utils/plot_utils.py
> +def save_figure(fig, path, dpi=100, bbox_inches="tight", pad_inches=0.1, **kwargs):
the main purpose is to unify the default saving process for all plotters.

2021-11-29 13:40 UTC, anton-br commented on seismicpro/src/batch.py
> +    def plot(self, src, src_kwargs=None, max_width=20, title="{src}: {index}", save_to=None, dpi=100, **common_kwargs):
What about deleting `dpi` from here and passing it if needed via dict to `save_to` parameter? It will look like: `save_to={"path": 'some_path', "dpi": 100}`

2021-11-30 13:11 UTC, anton-br commented on seismicpro/src/batch.py
> +                    title["label"] = label.format(src=src, index=index, **format_kwargs)
> can format_kwargs be different for different items in a batch?
No, you can't, except, of course `index`.
> I think that title formatting code up to this line can be moved outside this for-loop, This can allow to simplyfy the code
Yeah, I can, but it will split the logic of title processing into two parts what will affect the clarity.

2021-11-30 13:55 UTC, anton-br commented on seismicpro/src/semblance.py
> +        ax.figure.colorbar(img, ticks=levels[1::2], ax=ax)
we use divider in `Gather` to be able to plot scatter on top and colorbar simultaneously, here we don't need such construction.

2021-11-30 15:39 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        color = ["black"] if color is None else to_list(color)
I'd keep them here close to the main `plot` similar to other classes and avoid explicitly passing all required `self` attributes to the plotter

2021-11-30 15:40 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +UNITS = {
+

2021-11-30 15:42 UTC, alexandrkuvaev commented on seismicpro/src/semblance.py
> +    def plot(self, stacking_velocity=None, title="Semblance", x_ticker=None, y_ticker=None, grid=False, ax=None,
Maybe in the future, it'll require some effort to do it properly

2021-11-30 16:04 UTC, alexandrkuvaev commented on seismicpro/src/decorators.py
> +    return partial(_update_method_params, method_params=kwargs)
Currently it's not, but later may be used to pass information about `args_to_unpack` to a predefined method of `SeismicBatch` without decorating it with a batch method (e.g. force `crop` method to get `origins` from a component)

2021-11-30 16:06 UTC, alexandrkuvaev commented on seismicpro/src/decorators.py
> +                for arg_name in to_list(obj_method_params["args_to_unpack"]):
Actually yes because of `methods_to_add` selection, but I'll think of switching to a safer `get`

2021-11-30 16:14 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +                    title["label"] = label.format(src=src, index=index, **format_kwargs)
It can't be moved outside both loops since title formatting depends on both `src` and `index` we are iterating over

2021-11-30 16:19 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +from .utils import to_list, convert_times_to_mask, convert_mask_to_pick, mute_gather, set_ticks, plot_arg_to_dict
The first line imports modules, the second one - functions. I'd keep it as is

2021-11-30 16:19 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        plotters_dict[mode](ax, **kwargs)
Third one is coming: histogram of amplitudes for tutorials

2021-11-30 16:22 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +    def _parse_headers_kwargs(headers_kwargs, headers_key):
> Do you really need it as a parameter?
Currently no, but I don't want to hardcode it in two functions

> Dropping it will simplify the code dramatically
Don't understand how, it will keep it almost the same

2021-11-30 16:23 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        top_ax.scatter(np.arange(self.n_traces), header_values, s=5, color="black")
It's relative at least and we haven't seen any troubles for all the tested `figsizes`

2021-11-30 16:24 UTC, alexandrkuvaev commented on seismicpro/src/semblance.py
> +             x_ticker=None, y_ticklabels=None, y_ticker=None, ax=None, grid=False,
Because you can control them in `Gather`, but can't in `Semblance`

2021-12-02 10:54 UTC, anton-br commented on seismicpro/src/utils/plot_utils.py
> +    elif step_ticks is not None:
changed my mind and rewrote all with locators and formatters, have a look

2021-12-02 10:56 UTC, anton-br commented on seismicpro/src/utils/plot_utils.py
> +def plot_arg_to_dict(arg):
I would leave function as this but agree with naming. Any suggestions?

2021-12-02 10:58 UTC, anton-br commented on seismicpro/src/decorators.py
> +def plotter(figsize, args_to_unpack=None):
for me `figsize` is completely clear.  Let's vote tomorrow

2021-12-02 10:58 UTC, anton-br commented on seismicpro/src/gather.py
> +        top_ax.scatter(np.arange(self.n_traces), header_values, s=5, color="black")
done

2021-12-02 11:18 UTC, anton-br commented
@a-arefina @nikita-klsh I either I have taken your comments to attention or answered why I didn't do it. Please take a look and resolve comments that you are agree with

2021-12-03 10:30 UTC, alexandrkuvaev requested changes

2021-12-03 10:37 UTC, anton-br commented on seismicpro/src/utils/plot_utils.py
> +def _process_ticks(labels, num=None, step_ticks=None, step_labels=None, round_to=0, **kwargs):
basically it does. kwargs can contain some of arguments for this function such `num` or `step_ticks`.
If you want we can pop the arguments for this function beforehand

2021-12-06 13:56 UTC, a-arefina commented on seismicpro/src/decorators.py
> +    return partial(_update_method_params, method_params=kwargs)
Please please don't let a zombie in our code

One can write it if it is needed

2021-12-07 10:35 UTC, a-arefina commented on seismicpro/src/gather.py
> +        traces = np.arange(self.n_traces).reshape(-1, 1) + std * self.data / np.std(self.data)
if self.data contains zero traces, we'll have division by zero
```suggestion
        traces = np.arange(self.n_traces).reshape(-1, 1) + std * self.data / (np.std(self.data) + 1e-10)
```

2021-12-09 10:12 UTC, alexandrkuvaev requested changes

2021-12-10 07:32 UTC, alexandrkuvaev commented on seismicpro/src/utils/plot_utils.py
> +    n_labels = len(labels)
Refactored

2021-12-10 07:33 UTC, alexandrkuvaev commented on seismicpro/src/utils/plot_utils.py
> +                sub_labels = np.round(sub_labels, round_to)
Refactored

2021-12-10 07:33 UTC, alexandrkuvaev commented on seismicpro/src/utils/plot_utils.py
> +        locator = ticker.IndexLocator(step_ticks, 0)
It doesn't, decided to keep as is

2021-12-10 07:33 UTC, alexandrkuvaev commented on seismicpro/src/utils/plot_utils.py
> +        save_figure(fig, save_to, dpi=dpi, bbox_inches="tight", pad_inches=0.1)
Done

2021-12-10 07:33 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +    def plot(self, mode="seismogram", event_headers=None, header_on_top=None, title=None,
Done

2021-12-10 07:34 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        traces = np.arange(self.n_traces).reshape(-1, 1) + std * self.data / np.std(self.data)
Done

2021-12-16 19:56 UTC, alexandrkuvaev approved these changes

2021-12-17 13:08 UTC, a-arefina approved these changes

2021-12-17 13:08 UTC, a-arefina commented on seismicpro/src/gather.py
> +        - `label`: source to get tick labels from. Can be either any gather header or "index" (ordinary numbers of
ordinary -> ordinal ?

2021-12-17 13:08 UTC, a-arefina commented on seismicpro/src/decorators.py
> +    return partial(_update_method_params, method_params=kwargs)
Still willing to remove it...

2021-12-17 16:09 UTC, nikita-klsh commented on seismicpro/src/gather.py
> +        Ticks and their labels for both `x` and `y` axes can be controlled via `x_ticker` and `y_ticker` parameters
```suggestion
        Ticks and their labels for both `x` and `y` axis can be controlled via `x_ticker` and `y_ticker` parameters
```

2021-12-17 20:41 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +            ax.figure.colorbar(img, cax=cax, **colorbar)
The current order looks more clear to me

2021-12-17 20:42 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        - `label`: source to get tick labels from. Can be either any gather header or "index" (ordinary numbers of
Fixed everywhere

2021-12-17 20:43 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        color = ["black"] if color is None else to_list(color)
Fixed

2021-12-17 20:47 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +            ax.scatter(x_coords, y_coords, label=header, **kwargs)
Done

2021-12-17 20:50 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        """Set ticks and their labels for a given axis."""
Actually, you set ticks, their labels and an axis label here. Clarified

2021-12-17 21:37 UTC, merged