Gather cropping
gazprom-neft/SeismicPro pull request #65
Opened 2021-10-26 12:33 UTC by bestetc

2021-11-02 12:25 UTC, a-arefina commented on seismicpro/src/gather.py
> +from .utils import make_origin  #вылезает за 120 символов
plz no russian in code

2021-11-02 12:25 UTC, a-arefina commented on seismicpro/src/utils/general_utils.py
> +def make_origin(mode, gather_shape, crop_shape):
I guess, you have forgotten to commit the `__init__.py` from  seismicpro/src/utils with an import of this method

2021-11-02 12:34 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +def make_origin(mode, gather_shape, crop_shape):
Function `make_origin` was added to `utils/general_utils.py` and no lead to change `__init__.py`

2021-11-02 12:34 UTC, bestetc commented on seismicpro/src/gather.py
> +from .utils import make_origin  #вылезает за 120 символов
done

2021-11-02 14:41 UTC, alexandrkuvaev requested changes

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +    ):
Follow `SeismicPro` style guide

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        self.parent_shape = parent_gather.data.shape
```suggestion
        self.parent_shape = parent_gather.shape
```

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +                raise AttributeError("Gather hasn't a mask to crop.")
We've decided to transform the mask into a `Gather` instance

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +    def load_data(self):
This method does not load data, but pads it

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        # print('start load_data()')
Remove all the unnecessary code

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +            gather_data = np.pad(self.parent.data, self.to_tuple(self.gather_pad), constant_values=self.gather_fill)
Why only constant padding? Even FBP task will most likely require mirroring

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        self.gather_pad = gather_pad
Almost half of these attributes are unnecessary to store in the class

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        crops = np.full(shape=(self.origin.shape[0], *self.shape), fill_value=np.nan, dtype=float)
Why not `empty`?

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +            crops[i, :, :] = self.make_single_crop(self.origin[i], data)
remove colons

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        dx, dy = self.shape[1], self.shape[0]
See above

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        start_x, start_y = origin[1], origin[0]
Why not
```suggestion
        start_y, start_x = origin
```
?

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +            0]:  # if crop window outs from gather
Nice wrapping. Fix.

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        if start_x + dx > self.parent_shape[1] or start_y + dy > self.parent_shape[
How can it logically be true if you performed padding in `load_data`?

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +                                     (0, max(0, min(start_x, self.parent_shape[1]) + dx - self.parent_shape[1]))))
Some kind of elvish

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        result /= mask
Why only mean aggregation?

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        result = np.zeros(shape=self.parent_shape, dtype=float)
Why `zeros`?

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +    def to_tuple(self, item):  # maybe remove
Not maybe, remove

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        gather = self.copy()
Avoid copying gather data

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        gather = self.parent.copy()
Avoid copying gather data

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        self[first_breaks_col] = convert_mask_to_pick(self.data, self.sample_rate, threshold)
Think of a convenient way to pass picks to other batch components

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +            plt.imshow(self.data.T, **default_kwargs)
?

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        vmin, vmax = self.get_quantile([0.05, 0.95])
Why?

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +
Add empty line

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +        return (np.random.randint(gather_shape[0] - crop_shape[0]),
Why only one point?

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +            origin_y[-1] = gather_shape[1] - crop_shape[1]
Cover it in `arange`s above

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +        origin.append(_origins_from_str(mode, gather_shape, crop_shape))
Simplify and avoid appending

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +    @batch_method(target='for')
Have you benchmarked it?

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +    def b_crop(self, src, mode, shape, dst=None, **kwargs):
Add a flag for joint or non-joint cropping of `src` components

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +        if {len(set(getattr(self, item)[i].shape for item in list_src)) for i in range(len(self))} != set([1]):
Simplify

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +                if not isinstance(getattr(self, item)[i], Gather):
Why?

2021-11-02 14:41 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +
To

Many

Blank

Lines

2021-11-03 17:25 UTC, dpodvyaznikov requested changes
Consider switching to relative `[0, 1]` crop coordinates.

2021-11-08 09:47 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +    ):
done

2021-11-08 09:48 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +                raise AttributeError("Gather hasn't a mask to crop.")
Mask is Gather instance now. It's a some undelete legacy. Removed.

2021-11-08 09:53 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +    def load_data(self):
This method returns the data for the futher usage.
May be make_data should be better naming.

2021-11-08 09:55 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        self.parent_shape = parent_gather.data.shape
done

2021-11-08 09:59 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +            crops[i, :, :] = self.make_single_crop(self.origin[i], data)
done

2021-11-08 10:07 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        crops = np.full(shape=(self.origin.shape[0], *self.shape), fill_value=np.nan, dtype=float)
Some hardcode to be sure have some issue with deleting np.nan in the _assemble_gather() method.

2021-11-08 10:14 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        start_x, start_y = origin[1], origin[0]
good idea.

2021-11-08 10:14 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        dx, dy = self.shape[1], self.shape[0]
done

2021-11-08 10:15 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +            0]:  # if crop window outs from gather
done.

2021-11-08 10:20 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        if start_x + dx > self.parent_shape[1] or start_y + dy > self.parent_shape[
Add update `self.parent_shape` in `load_data()`

2021-11-08 10:45 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +    ):
Mark as done only when the code is committed

2021-11-08 12:38 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        result = np.zeros(shape=self.parent_shape, dtype=float)
Good decision for futher summing.

2021-11-08 12:38 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +    def to_tuple(self, item):  # maybe remove
done

2021-11-08 12:56 UTC, bestetc commented on seismicpro/src/gather.py
> +        gather = self.copy()
done

2021-11-08 12:58 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        gather = self.parent.copy()
done

2021-11-08 13:00 UTC, bestetc commented on seismicpro/src/gather.py
> +            plt.imshow(self.data.T, **default_kwargs)
A some legacy. Removed.

2021-11-08 13:02 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +
done

2021-11-08 15:03 UTC, bestetc commented on seismicpro/src/batch.py
> +                if not isinstance(getattr(self, item)[i], Gather):
If first item in the batch component is `Gather`, so any other items in this component are also `Gather`s

2021-11-08 15:27 UTC, bestetc commented on seismicpro/src/gather.py
>  from .utils import to_list, convert_times_to_mask, convert_mask_to_pick, mute_gather, normalization, correction
done

2021-11-09 09:48 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        result /= mask
Added a possibility to extend an aggregation methods.

2021-11-09 11:44 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +        origin.append(_origins_from_str(mode, gather_shape, crop_shape))
rework

2021-11-09 11:45 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +            origin_y[-1] = gather_shape[1] - crop_shape[1]
change the `arange `to `linspace`

2021-11-09 11:47 UTC, bestetc commented on seismicpro/src/gather.py
> +    @batch_method(target='for')
No, code speed optimization at the next round of a developing.

2021-11-09 12:02 UTC, bestetc commented on seismicpro/src/batch.py
> +
done

2021-11-12 11:49 UTC, alexandrkuvaev requested changes

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    if isinstance(mode, tuple) or isinstance(mode, list):
What kind of tuple/list is expected here?

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    return origin
Just return in `if`

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +        size = kwargs['n_items'] if 'n_items' in kwargs.keys() else 1
Simply get

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +        return np.array((np.random.randint(gather_shape[0] - crop_shape[0], size=size),
What if crop shape is greater than that of a gather?

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +        grid_coverage = kwargs['grid_coverage'] if 'grid_coverage' in kwargs.keys() else 1
Describe the argument, can't get it

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +                               num=int(((gather_shape[0] - crop_shape[0]) // crop_shape[0] + 2) * grid_coverage),
Simplify and correct the logic

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        kwargs = self._crop_kwargs_pop(kwargs)
kwargs should be popped during their processing

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +            if mode is None:
This check is already performed in `make_origin`

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        self.shape = shape  # rename attributes to crop_shape? self.shape = self.crops.shape
rename

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        self.origin = origin  # save origins in np.array
You've already casted them to an array

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        crops = np.full(shape=(self.origin.shape[0], *self.shape), fill_value=np.nan, dtype=float)  # may be change to np.empty
Why `full`?

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        for i in range(self.origin.shape[0]):
enumerate origins

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +            result = np.pad(result, ((0, max(0, min(start_y, shape_y) + dy - shape_y)),
You perform padding for each crop, while you could do it once in init

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +    def assemble_gather(self, input_data=None, **kwargs):
Why do you need `input_data`?

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        self.gather.data = None
You haven't restored it

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +                cut_edge = kwargs['grid_cut_edge']
?

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        result = self._aggregate(result, mask, mode=self.aggregation_mode)
Almost none aggregations can be calculated using array sum and its length

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +                one_crop = np.pad(one_crop[cut_edge[0]:(self.shape[0] - cut_edge[0]),
Too much pads everywhere

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +        for i in range(len(self)):
Why? You've already decorated it with `inbatch_parallel`

2021-11-12 11:49 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +    @inbatch_parallel(init='_init_component', target='for')
Read about `inbatch_parallel`, and refactor the method completely

2021-11-12 13:13 UTC, bestetc commented on seismicpro/src/gather.py
> +    def plot(self, figsize=(10, 7), mask=False, **kwargs):
Was needed to testing some legacy. Will removed.

2021-11-12 13:51 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +    def assemble_gather(self, input_data=None, **kwargs):
sometimes needs to assemble gather from outer data. For examples model outputs.
It could be realize in a pipeline by `update` method  and `assemble_gather ` or by the `assemble_gather `with `input_data`.

2021-11-14 09:21 UTC, dpodvyaznikov requested changes

2021-11-24 14:15 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        # print('start load_data()')
done

2021-11-24 14:17 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +            gather_data = np.pad(self.parent.data, self.to_tuple(self.gather_pad), constant_values=self.gather_fill)
rework. pls, check `_padding()`

2021-11-24 14:18 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        crops = np.full(shape=(self.origin.shape[0], *self.shape), fill_value=np.nan, dtype=float)
changes to empty

2021-11-24 14:18 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        self.gather_pad = gather_pad
The data is all you don't want to copy.

2021-11-24 14:20 UTC, bestetc commented on seismicpro/src/gather.py
> +    def _crop_kwargs_pop(self, kwargs):
kwargs are removed from current Crop realization. All needful params are indicate in a signatures.

2021-11-24 14:24 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        dy, dx = self.shape
I hope that final naming will be rectify at the final pull request phase.
Using dx, dy a little bit better that self.shape[0], self.shape[1].

2021-11-24 14:32 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +    def make_crops(self, data):
All params, what I don't want to keep in class attributes I want to passed explicitly.
All params, what I think to be usefull to keep in class attributes I want to passed with self.

2021-11-24 14:32 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        self.data = self.gather.data
done

2021-11-24 15:10 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        self.origin = origin  # save origins in np.array
Useless comment are removed.

2021-11-24 15:41 UTC, bestetc commented on seismicpro/src/batch.py
> +        origin = make_origin(mode, gather_shape=getattr(self, item)[0].shape, crop_shape=shape)
Type and shape checking was reworked.
Check it again.

2021-11-24 15:41 UTC, bestetc commented on seismicpro/src/batch.py
> +    def b_crop(self, indices, src, mode, shape, dst=None, joint=True, **kwargs):
done.

2021-11-24 15:42 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +    if isinstance(mode, tuple) or isinstance(mode, list):
tuple with two coordinate of a point 
or list of a above tuples.

2021-11-24 15:42 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +    return origin
Done.

2021-11-24 15:42 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +        size = kwargs['n_items'] if 'n_items' in kwargs.keys() else 1
Good idea. Thanks.

2021-11-24 15:42 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +        return np.array((np.random.randint(gather_shape[0] - crop_shape[0], size=size),
Fixed.

2021-11-24 15:42 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +        grid_coverage = kwargs['grid_coverage'] if 'grid_coverage' in kwargs.keys() else 1
Done

2021-11-24 15:42 UTC, bestetc commented on seismicpro/src/gather.py
> +        kwargs = self._crop_kwargs_pop(kwargs)
Kwargs are removed.

2021-11-24 15:42 UTC, bestetc commented on seismicpro/src/gather.py
> +            if mode is None:
Rework this part.

2021-11-24 15:42 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        self.shape = shape  # rename attributes to crop_shape? self.shape = self.crops.shape
Thanks.

2021-11-24 15:43 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        crops = np.full(shape=(self.origin.shape[0], *self.shape), fill_value=np.nan, dtype=float)  # may be change to np.empty
Both ideas are great. Use it in the current implementation.

2021-11-24 15:43 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +            result = np.pad(result, ((0, max(0, min(start_y, shape_y) + dy - shape_y)),
This block fully reworked.

2021-11-24 15:44 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        self.gather.data = None
This bug fixed.

2021-11-24 15:44 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +                cut_edge = kwargs['grid_cut_edge']
Removed

2021-11-24 15:44 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        result = self._aggregate(result, mask, mode=self.aggregation_mode)
Reworked

2021-11-24 15:44 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +                one_crop = np.pad(one_crop[cut_edge[0]:(self.shape[0] - cut_edge[0]),
Padding stay alive and called once for `gather.data` in a `CroppedGather ` init.

2021-11-24 15:44 UTC, bestetc commented on seismicpro/src/batch.py
> +    @inbatch_parallel(init='_init_component', target='for')
crop method in `batch.py` reworked. Pls, check it.

2021-11-24 15:44 UTC, bestetc commented on seismicpro/src/batch.py
> +            if len(cur_shape) > 1 and joint == True:
Rework

2021-11-24 15:44 UTC, bestetc commented on seismicpro/src/batch.py
> +        for item in list_src:
Checking are rework. Pls, check current implementation.

2021-11-24 15:45 UTC, bestetc commented on seismicpro/src/batch.py
> +            cur_pos = self.index.get_pos(indices)
Changed. Naming not my best facet.

2021-11-24 15:46 UTC, bestetc commented on seismicpro/src/batch.py
> +                gather = getattr(self, src_item)[cur_pos]
Yes, I have a same thought.
Now we implement crop only for gather so I was prefer to use gather name in this case.
Change to `object_item`.

2021-11-24 15:46 UTC, bestetc commented on seismicpro/src/batch.py
> +        else:
The batch part was fully refactored. Pls, see current realization.

2021-11-24 15:46 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        self.aggregation_mode = aggregation_mode
Yes, there are no reason.
Removed.

2021-11-24 15:47 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +    def _assembling(self, data, **kwargs):
kwargs removed. Thanks.

2021-11-24 21:22 UTC, alexandrkuvaev requested changes

2021-11-24 21:22 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +    @inbatch_parallel(init='_init_component', target='for')
Have you benchmarked target?

2021-11-24 21:22 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +            if len(set(src_types)) > 1:
Why not make `src_shapes` and `src_types` sets directly?

2021-11-24 21:22 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +            origins_list = [make_origins(origins, gather_shape=item_shape, crop_shape=shape,
Why generate `origins` here if they are calculated the same way automatically in `Gather.crop`?

2021-11-24 21:22 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +        for src_item, dst_item, origin_item in zip_longest(src_list, dst_list, origins_list, fillvalue=origins_list[0]):
`repeat` looks more natural here

2021-11-24 21:22 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    if isinstance(origins, tuple) or isinstance(origins, list):
Combine into a single `isinstance`

2021-11-24 21:22 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +        return np.atleast_2d(origins)  # atleast_2d
Remove unnecessary comments

2021-11-24 21:22 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    elif isinstance(origins, str):
It's just if now

2021-11-24 21:22 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    elif isinstance(origins, np.ndarray):
Why not treat this case together with `tuple` and `list`?

2021-11-24 21:22 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +        if len(origins.shape) == 2 and origins.shape[1] == 2:
`ndim`

2021-11-24 21:22 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    laying = np.linspace(0, working_len, num=int((working_len // crop_shape + eps) * grid_coverage), dtype=int)
Still don't get `grid_coverage` param(

2021-11-24 21:22 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        max_shapes = np.atleast_2d(self.origins.max(axis=0))
Why do you need 2d array here?

2021-11-24 21:22 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        return np.pad(self.gather.data, ((0, pad_shape_x), (0, pad_shape_y)), mode=pad_mode)
Is it possible to pass `kwargs` to `pad`?

2021-11-24 21:22 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +    def assemble_gather(self, input_data=None, strategy='greed', aggregation_mode='mean'):
Remove `input_data` and `strategy`

2021-11-24 21:22 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +            print('Rand aggregate matrix shape:', result.shape)
Remove all the prints from code

2021-11-26 13:45 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        max_shapes = np.atleast_2d(self.origins.max(axis=0))
if `max_shapes `is 1d array than correct broadcasting is not allowed.

2021-11-26 13:45 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        return np.pad(self.gather.data, ((0, pad_shape_x), (0, pad_shape_y)), mode=pad_mode)
possible and implemented

2021-11-26 13:45 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +    def assemble_gather(self, input_data=None, strategy='greed', aggregation_mode='mean'):
Removed. Stay mean aggregation only.

2021-11-26 13:45 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +            print('Rand aggregate matrix shape:', result.shape)
Why don't we use logging our something else?
We could stay all print as `print('Rand aggregate matrix shape:', result.shape, file=std.err)`

2021-11-26 13:45 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +    laying = np.linspace(0, working_len, num=int((working_len // crop_shape + eps) * grid_coverage), dtype=int)
bug fix here.

2021-11-26 13:45 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +        if len(origins.shape) == 2 and origins.shape[1] == 2:
yep

2021-11-26 13:45 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +    elif isinstance(origins, np.ndarray):
reworked

2021-11-26 13:45 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +    elif isinstance(origins, str):
changes

2021-11-26 13:45 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +        return np.atleast_2d(origins)  # atleast_2d
agreed

2021-11-26 13:45 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +    if isinstance(origins, tuple) or isinstance(origins, list):
done

2021-11-26 13:45 UTC, bestetc commented on seismicpro/src/batch.py
> +        for src_item, dst_item, origin_item in zip_longest(src_list, dst_list, origins_list, fillvalue=origins_list[0]):
simplify to zip

2021-11-26 13:46 UTC, bestetc commented on seismicpro/src/batch.py
> +            if len(set(src_types)) > 1:
done

2021-11-26 13:51 UTC, bestetc commented on seismicpro/src/batch.py
> +             aggregation_mode='mean', pad_mode='constant'):
cleared

2021-11-29 08:59 UTC, alexandrkuvaev requested changes

2021-11-29 08:59 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +
You don't need it anymore

2021-11-29 08:59 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +    def crop(self, idx, src, origins, crop_shape, dst=None, joint=True, n_items=1, grid_coverage=1,
I'd rename `n_items` to `n_crops`

2021-11-29 08:59 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    if isinstance(origins, (tuple, list, np.ndarray)):
Make it default behaviour if `origin` type is not `str`

2021-11-29 08:59 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    elif origins == 'grid':
```suggestion
    if origins == 'grid':
```

2021-11-29 08:59 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    else:
Omit `else`, just `raise`

2021-11-29 08:59 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        gather = self.copy()
Let's merge @anton-br PR first and then simplify all this copying

2021-11-29 08:59 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        self.n_origins = origins.shape[0]
Make `n_origins` a property

2021-11-29 08:59 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        max_shapes = np.atleast_2d(self.origins.max(axis=0))
Why do you need broadcasting here at all?

2021-11-29 08:59 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        return result / mask
If `mask` equals zero for some coords (which is possible in case of `grid_coverage` less than 1), then you get `inf` result. `nan` is more appropriate here.

2021-11-29 13:54 UTC, alexandrkuvaev requested changes

2021-11-29 13:54 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    if not isinstance(origins, str):
Check for `str` first to avoid excessive tabulation

2021-11-29 13:54 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +                               grid_coverage=grid_coverage)
Follow `SeismicPro` styleguide

2021-11-29 13:54 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        pad_shape_x, pad_shape_y = np.maximum(np.zeros(shape=2, dtype=int), temp_max)
Remove `keepdims`, avoid broadcasting, remove `zeros`

2021-11-29 13:54 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        return np.nan_to_num(result / mask, copy=False, posinf=np.nan)
Why only `posinf`? Moreover, all `nan` values will become zero. Fix.

2021-11-29 14:18 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        self.n_origins = origins.shape[0]
good

2021-11-29 14:18 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +    else:
clear

2021-11-29 14:18 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +    elif origins == 'grid':
clear

2021-11-29 14:18 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +    if isinstance(origins, (tuple, list, np.ndarray)):
done. and changes erro message in `_origins_from_str`

2021-11-29 14:18 UTC, bestetc commented on seismicpro/src/batch.py
> +    def crop(self, idx, src, origins, crop_shape, dst=None, joint=True, n_items=1, grid_coverage=1,
done

2021-11-29 14:18 UTC, bestetc commented on seismicpro/src/batch.py
> +
yep

2021-11-29 15:04 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +    if not isinstance(origins, str):
changed. Is error message is good enough now?

2021-11-30 07:12 UTC, alexandrkuvaev requested changes

2021-11-30 07:12 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        for i, origin in enumerate(self.origins):
Zip

2021-11-30 07:12 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +    @batch_method(target='for')
Benchmark it

2021-11-30 07:12 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        pad_shape_x, pad_shape_y = np.maximum((0, 0), (max_shapes + self.crop_shape - self.gather.shape))
Just 0 instead of (0, 0), and remove excessive parenthesis

2021-11-30 12:58 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        return np.nan_to_num(result / mask, copy=False, posinf=np.nan)
0 / 0 returns `np.nan`, 1 / 0 returns `np.inf`.
There are no case to retrun const / 0, so removed `np.nan_to_num`

2021-11-30 13:06 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        pad_shape_x, pad_shape_y = np.maximum(np.zeros(shape=2, dtype=int), temp_max)
Removed, avoided, removed.

2021-11-30 13:13 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        pad_shape_x, pad_shape_y = np.maximum((0, 0), (max_shapes + self.crop_shape - self.gather.shape))
And remove excessive parenthesis

2021-11-30 14:31 UTC, alexandrkuvaev requested changes

2021-11-30 14:31 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    laying = np.linspace(0, working_len, num=int((gather_shape // crop_shape + eps) * grid_coverage), dtype=int)
Incorrect if gather shape is less than crop shape

2021-11-30 14:31 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +
Remove one empty line

2021-11-30 14:31 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        self[first_breaks_col] = convert_mask_to_pick(self.data, self.sample_rate, threshold)
Up

2021-11-30 14:31 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        if any((pad_shape_x, pad_shape_y)) > 0:
Fix the check

2021-12-01 15:17 UTC, nikita-klsh commented on seismicpro/src/cropped_gather.py
> +import warnings
Do you think `CroppedGather` deserves separate module or it's enough to place it, for example, at the bottom of `gather.py`?

2021-12-02 03:43 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +import warnings
This option was discussed at beigning.
CroppedGather contains sufficiently different functionality to separate code placement.  I hope current module will be grow by a crops of other objects of the SeismicPro. And new classes will be added to this module.

2021-12-02 03:43 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +            result[origin[0]:origin[0] + self.crop_shape[0], origin[1]:origin[1] + self.crop_shape[1]] += crop
gather data padded when CroppedGather created. This padding should cover all possible crops.

2021-12-02 12:38 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        working_shape = np.maximum(self.gather.shape, data.shape[-2:])
done

2021-12-02 12:38 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        return np.pad(self.gather.data, ((0, pad_shape_x), (0, pad_shape_y)), mode=pad_mode, **kwargs)
done

2021-12-02 12:42 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +    laying = np.linspace(0, working_len, num=int((gather_shape // crop_shape + eps) * grid_coverage), dtype=int)
fixed

2021-12-02 12:42 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        pad_shape_x, pad_shape_y = np.maximum((0, 0), (max_shapes + self.crop_shape - self.gather.shape))
done

2021-12-02 12:42 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +    @batch_method(target='for')
done

2021-12-02 15:45 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +        origins = np.column_stack((np.random.randint(1 + max(0, gather_shape[0] - crop_shape[0]), size=n_crops),
I don't know how to do it correctly but why do you sample crops without padding? In your code, the traces on the boundaries will be sampled much seldom, is it okay?

2021-12-02 15:45 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +    raise NotImplementedError("Support origins of the used type don't implement now")
please change the error on ValueError and provide a list of available origins.

2021-12-02 18:07 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        crops = np.empty(shape=(self.n_origins, *self.crop_shape), dtype=float)
agreed

2021-12-03 10:01 UTC, bestetc commented on seismicpro/src/batch.py
> +            origins = make_origins(origins, crop_shape=crop_shape, gather_shape=src_shapes.pop(),
Creation of origins is possible to use not only in CroppedGather. For example other cropped structure.

2021-12-03 10:50 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        pad_shape_x, pad_shape_y = np.maximum(0, max_shapes + self.crop_shape - self.gather.shape)
Names of variables refer to `crop_shape` attribute in CroppedGather. 
Using `width` closer to context.

2021-12-03 11:08 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        return result[:self.gather.shape[0], :self.gather.shape[1]]
Change to `gather.data.dtype`. `load_gather` use np.float32 now.

2021-12-03 11:09 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +    raise NotImplementedError("Support origins of the used type don't implement now")
okay

2021-12-03 11:09 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +        origins = np.column_stack((np.random.randint(1 + max(0, gather_shape[0] - crop_shape[0]), size=n_crops),
All padding are removed in this iteration. Simple explain: all needful padding could be added by layers in neural network.

2021-12-03 11:44 UTC, bestetc commented on seismicpro/src/batch.py
> +            src_shapes.add(cur_object.shape)
agreed

2021-12-03 11:44 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +        return _origins_from_str(origins, gather_shape, crop_shape, n_crops, grid_coverage)
done

2021-12-03 12:06 UTC, bestetc commented on seismicpro/src/batch.py
> +    @inbatch_parallel(init='_init_component', target='for')
updated

2021-12-03 12:06 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        pad_shape_x, pad_shape_y = np.maximum(0, max_shapes + self.crop_shape - self.gather.shape)
done

2021-12-03 14:00 UTC, alexandrkuvaev requested changes

2021-12-03 14:00 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        result = np.zeros(shape=result_shape, dtype=np.float32)
Rename to something like `sum`

2021-12-06 11:45 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +    def _gather_pad(self, pad_mode, **kwargs):
done

2021-12-06 11:47 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        max_shapes = self.origins.max(axis=0)
I think that next line could be overload. I renamed this variable.

2021-12-06 11:47 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        assembling_data = self._mean_assemble()
good

2021-12-06 11:47 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +    def _mean_assemble(self):
good

2021-12-06 11:48 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        result = np.zeros(shape=result_shape, dtype=np.float32)
renamed to `agg_crops`

2021-12-06 11:48 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        mask = np.zeros(shape=result_shape, dtype=int)
`count_crops `looks good

2021-12-06 13:54 UTC, bestetc commented on seismicpro/src/batch.py
> +            raise ValueError('`src` and `dst` should have the same length.')
May be we need to separate the most common checking to a single func with choosing checking by a func params.

2021-12-06 14:22 UTC, alexandrkuvaev requested changes

2021-12-06 14:22 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        used_gather_shape = np.maximum(self.gather.shape, self.crop_shape + self.origins.max(axis=0))
```suggestion
        padded_gather_shape = np.maximum(self.gather.shape, self.crop_shape + self.origins.max(axis=0))
```

2021-12-06 14:22 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        agg_crops = np.zeros(shape=used_gather_shape, dtype=np.float32)
```suggestion
        crops_sum = np.zeros(shape=padded_gather_shape, dtype=np.float32)
```

2021-12-06 14:22 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        count_crops = np.zeros(shape=used_gather_shape, dtype=int)
```suggestion
        crops_count = np.zeros(shape=padded_gather_shape, dtype=np.int32)
```

2021-12-06 14:22 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
>      @batch_method(target="threads")
```suggestion
    @batch_method(target="threads", copy_src=False)
```

2021-12-06 14:22 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +                warnings.warn(f"Picking columns {first_breaks_col} is already exist and will be overwritten.")
Not sure if we need this check

2021-12-06 14:22 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +    def mask_to_pick(self, threshold=0.5, first_breaks_col="FirstBreak", save_picking_to=None):
I'd change `save_picking_to` to a more concise `save_to`. Let's vote.

2021-12-06 14:39 UTC, bestetc commented on seismicpro/src/gather.py
> +                warnings.warn(f"Picking columns {first_breaks_col} is already exist and will be overwritten.")
Do not insist.
Current case is write predicted picking to the base gather in inference pipeline.
Loading base gather and saving result placed far from one another and default `first_breaks_col` in both func are same.

2021-12-06 15:07 UTC, bestetc commented on seismicpro/src/gather.py
>      @batch_method(target="threads")
done

2021-12-06 15:56 UTC, a-arefina reviewed
haven't checked all changes, more comments might follow

2021-12-06 15:56 UTC, a-arefina commented on seismicpro/src/batch.py
> +            raise ValueError('`src` and `dst` should have the same length.')
apply_to_each_component ?

2021-12-06 15:56 UTC, a-arefina commented on seismicpro/src/batch.py
> +            origins = make_origins(origins, crop_shape=crop_shape, gather_shape=src_shapes.pop(),
If make origins works not only for gathers, `gather_shape` parameter name should be changed

2021-12-06 15:56 UTC, a-arefina commented on seismicpro/src/gather.py
> +        # corresponding index along the trace to follow the first break.
```suggestion
        # The mask shape should match the shape of `gather.data`. Each item of the mask represents the probability that  the corresponding index is greater than the index of the first break .
```

2021-12-06 15:56 UTC, a-arefina commented on seismicpro/src/gather.py
> +        #     Gather attribute to get the mask from.
irrelevant now

2021-12-06 15:56 UTC, a-arefina commented on seismicpro/src/batch.py
> +            cropped = object_item.crop(origins=origins, crop_shape=crop_shape,
if object_item is a Gather, than `make_origins` is called twice: at line 333 in this method and inside Gaether,crop method

2021-12-07 10:44 UTC, bestetc commented on seismicpro/src/batch.py
> +            cropped = object_item.crop(origins=origins, crop_shape=crop_shape,
It's a plan. We have batch method crop and gather method crop. But gather method have not information about calling. In case calling from the batch method origins might be created inside the batch method and make_origins will returns origins created inside the batch method.

2021-12-07 11:11 UTC, bestetc commented on seismicpro/src/gather.py
> +        # corresponding index along the trace to follow the first break.
my suggestions about renaming `gather_shape`:
1: component_shape, 2: item_shape, 3: data_shape

2021-12-07 12:51 UTC, bestetc commented on seismicpro/src/gather.py
> +        #     Gather attribute to get the mask from.
docs correction for all changed and new functions will be soon.
Thanks for some idea.

2021-12-07 13:52 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +            raise ValueError('`src` and `dst` should have the same length.')
`apply_to_each_component` performs independent component processing, here sometimes we need to process them jointly

2021-12-07 13:52 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        # corresponding index along the trace to follow the first break.
`data_shape`

2021-12-07 13:52 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +                warnings.warn(f"Picking columns {first_breaks_col} is already exist and will be overwritten.")
I'd remove it, in all our usecases it won't be there. Anyway you can rename it

2021-12-07 14:59 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        count_crops = np.zeros(shape=used_gather_shape, dtype=int)
np.int32 faster than int. 
np.int16 faster than np.int32. 14ms vs 24ms

2021-12-07 14:59 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        agg_crops = np.zeros(shape=used_gather_shape, dtype=np.float32)
renamed

2021-12-08 13:28 UTC, bestetc commented on seismicpro/src/gather.py
> +                warnings.warn(f"Picking columns {first_breaks_col} is already exist and will be overwritten.")
okay

2021-12-08 16:00 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +    @batch_method(target='for')
Add `copy_src=False`

2021-12-08 16:02 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    origins = np.linspace(0, max_origins, num=int((data_shape // crop_shape + eps) * grid_coverage), dtype=int)
Make it either `np.int16` or `np.int32`

2021-12-08 16:04 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +                raise TypeError('`src` should contain same type of objects when `joint` is True.')
```suggestion
                raise TypeError('If joint is True, all src components must be of the same type.')
```

2021-12-08 16:04 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +                raise ValueError("Shapes of the 'src' object are not consistent.")
```suggestion
                raise TypeError('If joint is True, all src components must have the same shape.')
```

2021-12-08 17:09 UTC, a-arefina commented on seismicpro/src/utils/general_utils.py
> +    grid_coverage: int or float, optional, default is 1.
What about using strides? It is more flexible and the code will be simplier. You can use float stride between 0 and 1 to indicate fraction of ovelapping area and convert it to an integer stride, if you whant to keep this functionality

2021-12-08 17:09 UTC, a-arefina commented on seismicpro/src/cropped_gather.py
> +        for crop, origin in zip(self.crops, self.origins):
```suggestion
        for crop, (x0, y0) in zip(self.crops, self.origins):
```

for brevity

2021-12-08 17:09 UTC, a-arefina commented on seismicpro/src/batch.py
> +            raise ValueError('`src` and `dst` should have the same length.')
What about doing joint pre-processing in the main method and then calling actual cropping decorated with apply_to_each_component ? Like we do in `load`

2021-12-09 11:00 UTC, bestetc commented on seismicpro/src/gather.py
>          self.validate(required_header_cols=first_breaks_col)
done

2021-12-09 11:17 UTC, bestetc commented on seismicpro/src/gather.py
> +        that the corresponding index is greater than the index of the first break.
There are two opinion. This and https://github.com/gazprom-neft/SeismicPro/pull/65#discussion_r763134686.
Mayve we can use following:
Each row of the mask corresponds with trace and contains cumulative distribution function of the first break point.

2021-12-09 11:19 UTC, bestetc commented on seismicpro/src/gather.py
> +            another Gather to save picking in the header column `first_breaks_col`.
good

2021-12-09 11:24 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        for i, (start_x, start_y) in enumerate(self.origins):
x_0 and y_0 looks a little better, isnt't it?

2021-12-09 11:57 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +        for crop, origin in zip(self.crops, self.origins):
good

2021-12-09 12:17 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +    grid_coverage: int or float, optional, default is 1.
Two option: keep origins in float from 0 to 1 or int. I think that int more clear.

2021-12-09 12:18 UTC, bestetc commented on seismicpro/src/cropped_gather.py
> +    def _pad_gather(self, pad_mode, **kwargs):
We can add pad_mode in kwargs. I'll commit to show how it could be.
Is this explicit enough?

2021-12-09 12:20 UTC, bestetc commented on seismicpro/src/gather.py
> +        """Convert a first break mask saved in data into times of first arrivals.
done

2021-12-09 12:20 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +    raise ValueError("Origins should be a tuple, list or np.array with a total shape is [n_origins, 2].")
done

2021-12-09 12:21 UTC, bestetc commented on seismicpro/src/utils/general_utils.py
> +        raise ValueError("Using origin type not found. Use 'random' or 'grid' values.")
done

2021-12-10 07:26 UTC, alexandrkuvaev requested changes

2021-12-10 07:26 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        that the corresponding index is greater than the index of the first break.
Don't use row, data layout is a technical detail, don't use CDF, since it's not

2021-12-10 07:26 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        save_to : Gather, optional, default to None
```suggestion
        save_to : Gather, optional, defaults to None
```

2021-12-10 07:26 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +            save_to[first_breaks_col] = self[first_breaks_col]
Check, that this line works since `self[first_breaks_col]` returns a 2d array

2021-12-10 07:26 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    origins = np.linspace(0, max_origins, num=int((data_shape // crop_shape + eps) * grid_coverage), dtype=int)
Up

2021-12-10 07:26 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +            return np.pad(self.gather.data, ((0, pad_width_x), (0, pad_width_y)), mode=kwargs.pop('pad_mode'), **kwargs)
Avoid `pop`

2021-12-10 07:26 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +            crops_sum[x_0:x_0 + self.crop_shape[0], y_0:y_0 + self.crop_shape[1]] += crop
Add `dx, dy = self.crop_shape` similar to `make_crops`

2021-12-10 07:48 UTC, a-arefina commented on seismicpro/src/cropped_gather.py
> +            crops_sum[x_0:x_0 + self.crop_shape[0], y_0:y_0 + self.crop_shape[1]] += crop
By the way, why `x_0`, not `x0` ?

2021-12-10 09:06 UTC, alexandrkuvaev requested changes

2021-12-10 09:06 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +            save_to[first_breaks_col] = self[first_breaks_col]
```suggestion
        picking_times = convert_mask_to_pick(self.data, self.sample_rate, threshold)
        self[first_breaks_col] = picking_times
        if save_to is not None:
            save_to[first_breaks_col] = picking_times
```

2021-12-10 11:30 UTC, a-arefina reviewed
Please chack all dockstrings with grammarly

2021-12-10 11:30 UTC, a-arefina commented on seismicpro/src/gather.py
> +        Each value of the mask should represent a probability of the corresponding index along the trace to follow the
I think, this description is not very clear. I've made a suggestion according to my understanding of it, but it turned out to be incorrect. Please rewrite this phrase to ensure unambiguous interpretation 

@alexandrkuvaev , your help will be much welcome

2021-12-10 11:52 UTC, dpodvyaznikov requested changes

2021-12-10 11:52 UTC, dpodvyaznikov commented on seismicpro/src/utils/general_utils.py
> +def _make_grid_origins(data_shape, crop_shape, grid_coverage):
I don't like name of `grid_coverage` parameter, especially with the default value of 1 - it seem like this is a relative thing that should be in [0,1] interval.

Options - n_overlaps, avg_pixel_coverage

2021-12-13 12:00 UTC, anton-br commented on seismicpro/src/batch.py
> +        crop_shape: tuple with 2 elements
a lot of spaces are missing:(
```suggestion
        crop_shape : tuple with 2 elements
```

2021-12-13 12:14 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +        crop_shape: tuple with 2 elements
Fixed everywhere

2021-12-13 12:14 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +def _make_grid_origins(data_shape, crop_shape, grid_coverage):
Renamed to `n_overlaps`.

2021-12-13 12:15 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        Each value of the mask should represent a probability of the corresponding index along the trace to follow the
Fixed as you suggested

2021-12-13 12:15 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +            crops_sum[x_0:x_0 + self.crop_shape[0], y_0:y_0 + self.crop_shape[1]] += crop
Renamed

2021-12-13 13:26 UTC, nikita-klsh approved these changes
Few moments regarding benchmark.ipynb:
1. time `crop` action w/o coping, e.g. src=dst=`raw`, like its done in other benchmarks
2.  should we use the same cropping startegy, i.e. `grid`, for both `crop` and `assemble` bench? so we can estimate the time of pipeline
3. do we really need a separate section for `CroppedGather`(kinda internal object) with single bench? It would simplify perception if we place `assemble` right after the `crop`.

2021-12-13 13:26 UTC, nikita-klsh commented on seismicpro/src/batch.py
> +            Defines whether to create the same origins if `origins` passed is `str`. Generally used to perform joint
```suggestion
            Defines whether to create the same origins in case multiple `src` if `origins` passed is `str`. Generally used to perform joint
```

2021-12-13 13:26 UTC, nikita-klsh commented on seismicpro/src/cropped_gather.py
> +        Crops from the gather data, stacked along the first axis. Has shape (n_origins, *(crop_shape)).
`first axis` -> `zero axis` or `first dimension`

2021-12-13 13:50 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +        Crops from the gather data, stacked along the first axis. Has shape (n_origins, *(crop_shape)).
Done

2021-12-13 13:50 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +            Defines whether to create the same origins if `origins` passed is `str`. Generally used to perform joint
Done

2021-12-13 14:09 UTC, a-arefina commented on seismicpro/src/utils/general_utils.py
> +def _make_grid_origins(data_shape, crop_shape, n_overlaps):
in 2D inferring origins from overlaps will be even more complicated

2021-12-13 14:39 UTC, dpodvyaznikov requested changes

2021-12-13 14:39 UTC, dpodvyaznikov commented on seismicpro/src/utils/general_utils.py
> +    raise ValueError("Origins should be a tuple, list or np.ndarray with a shape of [n_origins, 2].")
IDK, maybe
```suggestion
    raise ValueError("If array-like, origins must be of a shape [n_origins, 2].")
```

2021-12-13 14:39 UTC, dpodvyaznikov commented on seismicpro/src/cropped_gather.py
> +        Cropped `Gather`.
```suggestion
        `Gather` for cropping.
```

2021-12-13 14:39 UTC, dpodvyaznikov commented on seismicpro/src/cropped_gather.py
> +    def n_origins(self):
```suggestion
    def n_crops(self):
```

2021-12-13 14:46 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +            Additional keyword arguments to `crop` method of the objects being cropped.
Switch to "to pass to"

2021-12-13 14:47 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +            The batch with cropped data.
Batch was already mentioned

2021-12-13 14:48 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +            If `joint` is `True` and components of different types are present in `src`.
Done

2021-12-13 14:49 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +            If `joint` is `True` and components of different shapes are present in `src`.
Rewritten similar to types

2021-12-13 14:52 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +                raise TypeError("If joint is True, all src components must be of the same type.")
Either highlight all code-like entities with backquotes like `True` or `src`, or don't do it at all in raises as we do almost in all `SeismicPro` codebase. Decided to keep as is.

2021-12-13 14:52 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +                raise ValueError("If joint is True, all src components must have the same shape.")
Same as above

2021-12-13 14:54 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> -        self.validate(required_header_cols=first_breaks_col)
It's performed in `__getitem__`

2021-12-13 14:55 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +            directly to `np.pad`, read https://numpy.org/doc/stable/reference/generated/numpy.pad.html for more
Fixed

2021-12-13 14:56 UTC, alexandrkuvaev commented on seismicpro/src/tests/gather_test.py
> +    mask.mask_to_pick(first_breaks_col='FirstBreak', save_to=gather)
Definitely not in this PR, these lines fixed an existing test due to `mask_to_pick` and `pick_to_mask` refactoring

2021-12-13 14:56 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    raise ValueError("Origins should be a tuple, list or np.ndarray with a shape of [n_origins, 2].")
Kept @dpodvyaznikov suggestion

2021-12-13 14:57 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +            return origins
Done

2021-12-13 14:57 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +        raise ValueError(f"Origin must be either 'random' or 'grid' but {origins} was given.")
Done

2021-12-13 14:58 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    raise ValueError("Origins should be a tuple, list or np.ndarray with a shape of [n_origins, 2].")
Done

2021-12-13 15:02 UTC, alexandrkuvaev commented on seismicpro/src/cropped_gather.py
> +    def n_origins(self):
Done

2021-12-13 15:35 UTC, alexandrkuvaev approved these changes

2021-12-13 16:01 UTC, dpodvyaznikov approved these changes

2021-12-13 17:35 UTC, a-arefina commented on seismicpro/src/batch.py
> +            If `joint` is `True` and components of different shapes are present in `src`.
I meant to use different constructions, otherwise the first impression was that both sentences are identical

I don't insist on rewriting this again, though

2021-12-13 17:36 UTC, a-arefina approved these changes

2021-12-13 17:42 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +def _make_grid_origins(data_shape, crop_shape, n_overlaps):
Switched to strides

2021-12-13 17:43 UTC, merged