dump picking
gazprom-neft/SeismicPro pull request #71
Opened 2021-11-25 16:05 UTC by nikita-klsh

Add action for fbp dump. Also slightly increase fbp load functionality.

2021-11-29 08:37 UTC, alexandrkuvaev requested changes

2021-11-29 08:37 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +    def dump_first_breaks(self, path, src, trace_id_columns=('FieldRecord', 'TraceNumber'),
Why is it a `SeismicBatch` method, not a `Gather` one? Usually, you store picking as a gather header, not a separate component, at least for visualization purposes.

2021-11-29 08:37 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +        df = self.index.headers.reset_index()[list(trace_id_columns)]
This may fail in the case of survey concatenation/merging. Better use gather headers here.

2021-11-29 08:37 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +        with open(path, 'a+') as f:
Why `a+`, not `a`?

2021-11-29 08:37 UTC, alexandrkuvaev commented on seismicpro/src/batch.py
> +            f.write(df.to_string(index=False, header=False, col_space=col_space, decimal=decimal, **kwargs) + '\n')
Do you really need to redefine defaults for `col_space` and `decimal` or you can pass them as `kwargs`?

2021-12-02 13:30 UTC, nikita-klsh commented on seismicpro/src/batch.py
> +            f.write(df.to_string(index=False, header=False, col_space=col_space, decimal=decimal, **kwargs) + '\n')
These defaults are required by `flatiron` soft
With these defaults the dump file can be directly loaded to both `survey` and `flatiron` soft

2021-12-02 16:10 UTC, anton-br commented on seismicpro/src/survey.py
> +        file_columns = trace_id_columns + (first_breaks_column, )
feels bad about this line without a cast to any array-like.. for example
```suggestion
        file_columns = to_list(trace_id_columns) + [first_breaks_column]
```

2021-12-02 16:10 UTC, anton-br commented on seismicpro/src/gather.py
> +        trace_id_columns : tuple of str, defaults to ('FieldRecord', 'TraceNumber')
Also, in your code, you highly rely on the fact that it is a tuple, why? Why don't I use `TRACE_SEQUENCE_FILE` as `trace_id_columns`? It is also a unique trace identifier...

2021-12-03 15:39 UTC, nikita-klsh commented on seismicpro/src/gather.py
> +    @batch_method(target='for', use_lock=True)
this action is not within-batch thread-safe to run target=`t`
even if we make it thread-safe it will become ~for loop in terms of performance

2021-12-03 15:39 UTC, nikita-klsh commented on seismicpro/src/gather.py
> +        trace_id_columns : tuple of str, defaults to ('FieldRecord', 'TraceNumber')
Sometimes trace_id cols are coords. 
Wrapped it with `to_list` for convenience

2021-12-03 15:45 UTC, nikita-klsh commented on seismicpro/src/gather.py
> +        """ Save first break picking times to the file.
these files actually do not have a special format, the format is described by the file structure

2021-12-03 20:33 UTC, alexandrkuvaev requested changes

2021-12-03 20:33 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        first_breaks_column : str, defaults to 'FirstBreak'
The same arg in `pick_to_mask` and `mask_to_pick` is called `first_breaks_col`, I'd stick to this naming. If so, let's also rename `trace_id_columns` to `trace_id_cols`

2021-12-03 20:33 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        decimal : str, default to ','
We don't use `pandas` to create the string to dump now, so maybe we should consider renaming it to something more clear, indicating that this is a separator. Maybe `decimal_sep`.

2021-12-03 20:33 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +                f.write(string + '\n')
Won't it be faster to format all rows into a single string and then write it in a single `write`?

2021-12-03 20:33 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        with open(path, 'a') as f:  #pylint: disable=unspecified-encoding
Let's pass `encoding` directly with a default of `"UTF-8"` as we do in all other pure-python load/dump functions

2021-12-03 20:33 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +            fmt = ['{:{col_space}.0d}'] * rows.shape[1]
Precision is not allowed for integers, why not always use the format from the `else` branch?

2021-12-03 20:33 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        first_breaks_column : str, optional, defaults to 'FirstBreak'
Similar comment about variable naming

2021-12-03 20:33 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        # little insurance: if we messed with decimal, dtype still be infered
Can't you force it using a `dtype` dict in `read_csv`?

2021-12-06 12:09 UTC, anton-br commented on seismicpro/src/survey.py
> +        headers = headers.merge(first_breaks_df, on=trace_id_columns)
You have deleted one of the raises, please check that it fails with the same error

2021-12-06 12:09 UTC, anton-br commented on seismicpro/src/gather.py
> +        decimal : str, default to ','
unify default in docs with real default value

2021-12-06 12:09 UTC, anton-br commented on seismicpro/src/decorators.py
>              return action(apply_to_each_component(method))
instead `action_params[method_name] = getattr(method, 'action_params')` write `action_params[method_name] = getattr(method, 'action_params', {})`

and return `action(**action_params[method_name])(apply_to_each_component(method))`

2021-12-06 13:41 UTC, nikita-klsh commented on seismicpro/src/gather.py
> +                f.write(string + '\n')
~10% faster: 10ms vs 11 ms for 3k traces gather.
Readability and consistency tho suffer a bit (pandas itself and numpy dumps its objects in row-wise manner).

2021-12-06 13:51 UTC, nikita-klsh commented on seismicpro/src/gather.py
> +            fmt = ['{:{col_space}.0d}'] * rows.shape[1]
++ integer format is incorrect now.

We can always use `else` branch, but this requires implicit cast `rows` to `float`(`rows.dtype == int` if `fbp.dtype == int`(picking  comes from the model pipeline))

So its either complicated formatted or unnecessary cast

2021-12-06 14:27 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +                f.write(string + '\n')
The code will be even shorter and more concise than it is now

2021-12-07 13:43 UTC, alexandrkuvaev requested changes

2021-12-07 13:43 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +            fmt_for_row = ['{:{col_space}.0f}'] * (rows.shape[1] - 1) + ['{:{col_space}.2f}'] + ['\n']
```suggestion
            row_fmt = '{:{col_space}.0f}' * (rows.shape[1] - 1) + '{:{col_space}.2f}\n'
```

2021-12-07 13:43 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +            fmt_for_rows = ''.join(fmt_for_row) * len(rows)
```suggestion
            fmt = row_fmt * len(rows)
```

2021-12-07 13:43 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        trace_id_columns : tuple of str, defaults to ('FieldRecord', 'TraceNumber')
Let's call it `trace_id_cols` to match naming in `load_first_breaks` and other args

2021-12-07 13:43 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        tsf_dtype = np.int32 if len(headers) < np.iinfo(np.int32).max else np.int64
Try using `np.min_scalar_type` for `len(headers)` here

2021-12-07 13:43 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +            encoding=kwargs.get('encoding', 'UTF-8')
Add it to args directly and also pass to `read_csv`

2021-12-08 14:26 UTC, a-arefina reviewed
Most comments suggest minor fixes in docs. Please avoid abbreviations

2021-12-08 14:26 UTC, a-arefina commented on seismicpro/src/gather.py
> +        the last column stores fbp times from `first_breaks_col` header.
```suggestion
        Each row in the resulting file corresponds to the first break picking of the trace.
        For each row: all but the last columns store values from `trace_id_columns` headers,
        the last column stores first break picking times from `first_breaks_col` header.
```

2021-12-08 14:26 UTC, a-arefina commented on seismicpro/src/gather.py
> +            Columns names from `self.headers` that act as trace id. These would present in the file.
```suggestion
            Columns names from `self.headers` that act as trace id. These would be present in the file.
```

2021-12-08 14:26 UTC, a-arefina commented on seismicpro/src/gather.py
> +            Column name from `self.headers` where fbp is stored.
```suggestion
            Column name from `self.headers` where first break picking times are stored.
```

2021-12-08 14:26 UTC, a-arefina commented on seismicpro/src/gather.py
> +        # segy spec states that all headers values are integers, first break values tho can be float
```suggestion
        # SEG-Y specification states that all headers values are integers, but first break values can be float
```

2021-12-08 14:26 UTC, a-arefina commented on seismicpro/src/survey.py
> +        """Load first break picking times from the file and save them to the new column in headers.
```suggestion
        """Load first break picking times from a file and save them to a new column in headers.
```

2021-12-08 14:26 UTC, a-arefina commented on seismicpro/src/survey.py
> +            Specifies whether or not whitespace will be used as the sep. See `pd.read_csv` for more details.
```suggestion
            Specifies whether or not whitespace will be used as a delimiter. See `pd.read_csv` for more details.
```

2021-12-08 14:26 UTC, a-arefina commented on seismicpro/src/survey.py
> +    def load_first_breaks(self, path, trace_id_cols = ('FieldRecord', 'TraceNumber'), first_breaks_col='FirstBreak',
What about adding `inplace` parameter since this method can destroy headers?

2021-12-08 15:43 UTC, alexandrkuvaev requested changes

2021-12-08 15:43 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        the last column stores fbp times from `first_breaks_col` header.
Also `trace_id_columns` -> `trace_id_cols`

2021-12-08 15:43 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        Returns
Add an empty line before returns block

2021-12-08 15:43 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        delim_whitespace: bool, defaults to True
Let's change it to a `delimiter` arg with default `\s+`

2021-12-08 15:43 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +                    decimal = ',' if ',' in row else '.'
```suggestion
            with open(path, 'r', encoding=encoding) as f:
                row = f.readline()
            decimal = '.' if '.' in row else ','
```

2021-12-10 10:02 UTC, alexandrkuvaev requested changes

2021-12-10 10:02 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +            All but the last columns names in the file.
```suggestion
            Headers, whose values are stored in all but the last columns of the file.
```

2021-12-10 10:02 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +            In case None tries to infer decimal from the first line of the file.
```suggestion
            If `None`, it is inferred from the first line of the file.
```

2021-12-10 10:02 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +            Additional keyword arguments to pass to  `pd.read_csv`.
```suggestion
            Additional keyword arguments to pass to `pd.read_csv`.
```

2021-12-10 11:13 UTC, a-arefina approved these changes

2021-12-10 11:33 UTC, alexandrkuvaev requested changes

2021-12-10 11:33 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        """Load first break picking times from a file and save them to a new column in headers.
```suggestion
        """Load times of first breaks from a file and save them to a new column in headers.
```

2021-12-10 11:37 UTC, alexandrkuvaev approved these changes

2021-12-10 11:59 UTC, dpodvyaznikov requested changes

2021-12-10 11:59 UTC, dpodvyaznikov commented on seismicpro/src/gather.py
> +        the last column stores first break times from `first_breaks_col` header.
```suggestion
        Each line in the resulting file corresponds to one trace, where all columns but the last one store values from `trace_id_cols` headers and identify the trace while the last column stores first break time from `first_breaks_col` header.
```

2021-12-10 11:59 UTC, dpodvyaznikov commented on seismicpro/src/gather.py
> +        """ Save first break picking times to the file.
```suggestion
        """ Save first break picking times to a file.
```

2021-12-10 12:43 UTC, dpodvyaznikov approved these changes

2021-12-10 12:52 UTC, merged