Change sample rate in gather.getitem as needed
gazprom-neft/SeismicPro pull request #72
Opened 2021-12-07 13:03 UTC by anton-br

The pull request provides:
* hotfix for Gather.getitem when sample rate is changed
* update tests for gather.getitem

2022-01-19 21:30 UTC, alexandrkuvaev requested changes

2022-01-19 21:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    """Fill area before `muting_indices` with `fill_value`.
they are times, not indices

2022-01-19 21:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +        times[i] = samples[int_i] + (ix - int_i) * (samples[min(int_i + 1, len(samples) - 1)] - samples[int_i])
Won't work as expected for negative indices

2022-01-19 21:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    Indices outside the `samples` range are clipped within the range of the `samples`.
```suggestion
    Indices outside the `samples` range are clipped to the range of the `samples`.
```

2022-01-19 21:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    """Convert `indices` to time values measured in milliseconds.
```suggestion
    """Convert `indices` to the corresponding time values from `samples`. Times for real-valued indices are obtained using linear interpolation by the adjacent values.
```

2022-01-19 21:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +        Recording time for each trace value. Measured in milliseconds.
They may be measured in any units

2022-01-19 21:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    2. `times` values outside the `samples` range are extrapolated.
Not times, but their indices

2022-01-19 21:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    1. The `samples` array must be non-decreasing.
You don't note it in `indices_to_times`

2022-01-19 21:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +        Time values to convert to indices. Measured in milliseconds.
They may be in any units

2022-01-19 21:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +        Otherwise, the indices are interpolating between nearest samples.
```suggestion
        If `True`, round the obtained real-valued indices to the nearest integer. Values exactly halfway between two adjacent integers are rounded to the nearest even one.
```

2022-01-19 21:30 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    """Convert `times` to indices by finding the corresponding position in `samples` for each time in `times` array.
```suggestion
    """Convert `times` to their indices in the non-decreasing `samples` array. If some value of `times` is not present in `samples`, its index is linearly interpolated or extrapolated by the other indices of `samples`.
```

2022-01-20 15:48 UTC, anton-br commented on seismicpro/src/gather.py
> +        raise ValueError("`sample_rate` is not defined, since `samples` is not regular.")
done

2022-01-20 15:48 UTC, anton-br commented on seismicpro/src/gather.py
> +        binary headers are the following:
done

2022-01-20 15:48 UTC, anton-br commented on seismicpro/src/gather.py
> +        1. Sample rate, 3217-3218 bytes, named `Interval` in segyio,
done

2022-01-20 15:49 UTC, anton-br commented on seismicpro/src/gather.py
> +        They are taken from the current gather.
done

2022-01-20 15:49 UTC, anton-br commented on seismicpro/src/gather.py
> +                dump_handler.header[i].update({**dump_h, **{segyio.TraceField.TRACE_SAMPLE_COUNT: sample_rate}})
done

2022-01-20 15:49 UTC, anton-br commented on seismicpro/src/gather.py
>                                       mask_length=self.shape[1]).astype(np.int32)
done

2022-01-20 15:49 UTC, anton-br commented on seismicpro/src/survey.py
> +        self.file_sample_rate = self._infer_sample_rate() / 1000 # Convert from microseconds to milliseconds
done

2022-01-20 15:49 UTC, anton-br commented on seismicpro/src/survey.py
> +        union_sample_rate = {bin_sample_rate, trace_sample_rate} - {0}
done

2022-01-20 15:49 UTC, anton-br commented on seismicpro/src/survey.py
> +                        " both are null or have different values."
done

2022-01-20 15:49 UTC, anton-br commented on seismicpro/src/survey.py
> +    error will be raised.
done

2022-01-20 15:49 UTC, anton-br commented on seismicpro/src/utils/file_utils.py
> +            samples_params.add((tuple(sample_rate), n_samples))
done

2022-01-20 15:49 UTC, anton-br commented on seismicpro/src/utils/file_utils.py
done

2022-01-20 15:49 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +    binary mask with shape (len(times_indices), mask_length) with `False` values before calculated time index for each
done

2022-01-20 15:49 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +    >>> samples = [0, 2, 4, 6, 8, 10]
done

2022-01-20 15:50 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +       elements of the found sequences.
done

2022-01-20 15:50 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +    array([0, 2, 3])
fixed

2022-01-20 15:50 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +    """Fill area before `muting_indices` with `fill_value`.
fixed

2022-01-20 15:50 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +        times[i] = samples[int_i] + (ix - int_i) * (samples[min(int_i + 1, len(samples) - 1)] - samples[int_i])
fixed

2022-01-20 15:51 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +    Indices outside the `samples` range are clipped within the range of the `samples`.
done

2022-01-20 15:51 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +    """Convert `indices` to time values measured in milliseconds.
done

2022-01-20 15:51 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +        Recording time for each trace value. Measured in milliseconds.
deleted

2022-01-20 15:51 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +    2. `times` values outside the `samples` range are extrapolated.
delete this note since you add it into the main doc

2022-01-20 15:51 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +    1. The `samples` array must be non-decreasing.
added

2022-01-20 15:52 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +        Time values to convert to indices. Measured in milliseconds.
deleted

2022-01-20 15:52 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +        Otherwise, the indices are interpolating between nearest samples.
done

2022-01-20 15:52 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +    """Convert `times` to indices by finding the corresponding position in `samples` for each time in `times` array.
done

2022-01-21 14:52 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +        Time values to convert to indices. Measured in milliseconds.
From all the utils, where they may be arbitrary

2022-01-25 11:14 UTC, nikita-klsh commented on seismicpro/src/utils/general_utils.py
> +    return times
```suggestion
    return np.interp(indices, np.arange(len(samples)), samples)
```

2022-01-25 11:33 UTC, anton-br commented on seismicpro/src/gather.py
> +        sample_rate = np.unique(np.diff(self.samples))
No, it is not.
We have already failed with changing `sample_rate` once, so we decided to calculate it in one place.

2022-01-25 11:37 UTC, anton-br commented on seismicpro/src/gather.py
> +                dump_handler.header[i].update({**dump_h, segyio.TraceField.TRACE_SAMPLE_COUNT: sample_rate})
my fault, thank you

2022-01-25 11:39 UTC, anton-br commented on seismicpro/src/gather.py
> +        3. Extended number of samples per data trace, bytes 3269-3272, called `ExtSamples` in `segyio`.
because TRACE_SAMPLE_COUNT is not used. while TRACE_SAMPLE_INTERVAL is used to infer sample_rate.

2022-01-25 11:44 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +    binary mask with shape (len(times_indices), len(samples)) with `False` values before calculated time index for each
seems, you've looked at the old version of the code..
Also, are you sure that boolean better then binary?

2022-01-25 11:47 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +    return times
Did you time it? When I time it, my code was much faster.

2022-01-25 12:13 UTC, anton-br commented on seismicpro/src/utils/general_utils.py
> +    float_position = interpolate(times, samples, np.arange(len(samples), dtype=np.float32), left_slope, right_slope)
extrapolation will be used in `semblance` for apply_nmo. Let's tomorrow discuss about negative indices, for now I don't see any problems here.

2022-01-25 12:18 UTC, anton-br commented on seismicpro/src/survey.py
> +        # 0 means that sample rate is undefined, so it is subtracting from the set of sample rate values.
why? this comment is about why we subtract zero from the set

2022-01-25 12:20 UTC, anton-br commented on seismicpro/src/gather.py
> +        Almost all binary and textual headers are copied from the parent SEG-Y file unchanged except for the following
don't get this one :(

2022-01-25 13:50 UTC, nikita-klsh commented on seismicpro/src/gather.py
> +        sample_rate = np.unique(np.diff(self.samples))
Can you please provide the context then.

Imagine you have the pipeline
```
.action1() # break sample_rate
.action2()
.action3()
.action4() # call gather.sample_rate
```
`action1` breaks the sample rate, and you will know about this only in `action4`. And you still do not know where exactly you fail(`action1`, `action2`, `action3` or `action4`)

2022-01-25 13:50 UTC, nikita-klsh commented on seismicpro/src/survey.py
> +        # 0 means that sample rate is undefined, so it is subtracting from the set of sample rate values.
Clarify in the docs what the word well-defined means(non zero)

2022-01-25 13:50 UTC, nikita-klsh commented on seismicpro/src/utils/general_utils.py
> +    return times
~ two times slower on any scale(with fastmath mode enabled). For 1000 indices:
1. you: 4.63 µs ± 12.4 ns per loop
2. numpy: 10.8 µs ± 16.8 ns per loop

In terms of readability numpy wins much more as for me

2022-01-25 13:54 UTC, nikita-klsh commented on seismicpro/src/gather.py
>              # TODO: Check if bin headers matter
You fix the case when the sample_rate or n_samples changes. No point to mention it in the comment anymore

2022-01-25 14:38 UTC, anton-br commented on seismicpro/src/gather.py
> +        sample_rate = np.unique(np.diff(self.samples))
We have a few actions that change the sample rate and we don't want to raise an error every time. For example, if you get a subsample of the gather like this:
`g_sub = g[:, [1, 2, 5]]`
Here, `sample_rate` is not defined. You don't want to receive an error here if you want just to plot it or do whatever you want (except actions that rely on `sample_rate`).

And only if you want to calculate semblance for this subgather or convert picking to mask you will receive an error that will tell you that sample_rate is missing.

2022-01-27 09:08 UTC, alexandrkuvaev requested changes

2022-01-27 09:08 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +            # Copy binary headers from the parent SEG-Y file.
```suggestion
            # Copy the binary header from the parent SEG-Y file and update it with samples data of the gather.
```

2022-01-27 09:08 UTC, alexandrkuvaev commented on seismicpro/src/utils/general_utils.py
> +    1. The `samples` array must be increasing.
you've already mentioned, that it must be increasing. I'd remove the note

2022-01-27 10:49 UTC, alexandrkuvaev approved these changes

2022-01-27 10:49 UTC, merged