mark dead traces
gazprom-neft/SeismicPro pull request #73
Opened 2021-12-07 14:01 UTC by a-arefina

keeping dead trace indicator in headers allows convenient fitering

2021-12-07 14:10 UTC, alexandrkuvaev requested changes

2021-12-07 14:10 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        self.n_dead_traces = len(dead_indices)
Remove `self.n_dead_traces = 0` line above then

2021-12-07 14:10 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        self.headers.loc[self.headers["TRACE_SEQUENCE_FILE"].isin(dead_indices), 'DeadTrace'] = 1
You know, that `i` in the above `for` loop represents the index of the processed trace. Thus you can store it in `dead_indices` instead of `pos + 1` to use `iloc` here, which is way faster

2021-12-07 14:10 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        self.headers['DeadTrace'] = 0
Don't forget to mention this new header in docs

2021-12-07 14:11 UTC, alexandrkuvaev commented
Also think of a `remove_dead_traces` method of a `Survey`, which will run `collect_stats` if they are not present and perform filtering

2021-12-08 12:12 UTC, a-arefina commented on seismicpro/src/survey.py
> +        self.headers.loc[self.headers["TRACE_SEQUENCE_FILE"].isin(dead_indices), 'DeadTrace'] = 1
but `i` is an index in a shuffled array `praces_pos`, it has no connection with the original traces indices in headers :(

2021-12-08 13:57 UTC, a-arefina commented
> Also think of a `remove_dead_traces` method of a `Survey`, which will run `collect_stats` if they are not present and perform filtering

I've added a method for removing dead traces but there are some questions to concider

1) Do we need an option to skip quantiles calculation when running `collect_stats` for performance reasons?
2) deleting dead traces changes survey's stats. I've added a flag to recalculate it, but to do it fairly, we need to save parameters of previous calculation process (indices, n_quantile_traces, quantile_precision, stats_limits). In seismiqb they don't include dead traces in the pool for calculating stats, which removes the need for recalculation after dead traces are deleted. 
3) do we need to recalculate stats in `set_limits`? Maybe there are other methods that can chance stats?

2021-12-08 15:01 UTC, alexandrkuvaev requested changes

2021-12-08 15:01 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +            self.collect_stats()
Let's pass all the `kwargs` here

2021-12-08 15:01 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        if recollect_stats:
I'd change `collect_stats` to use only non-dead traces for stats calculation (which seems pretty reasonable) and remove this check at all

2021-12-08 15:09 UTC, alexandrkuvaev commented
> 1. Do we need an option to skip quantiles calculation when running `collect_stats` for performance reasons?

If you pass `kwargs` as I suggest above, you can do it by passing `n_quantile_traces=0`. But quantile calculation is not generally a bottleneck at least when `n_quantile_traces` is not that great.

> 2. deleting dead traces changes survey's stats. I've added a flag to recalculate it, but to do it fairly, we need to save parameters of previous calculation process (indices, n_quantile_traces, quantile_precision, stats_limits). In seismiqb they don't include dead traces in the pool for calculating stats, which removes the need for recalculation after dead traces are deleted.

I'd calculate stats only for non-dead traces.

> 3. do we need to recalculate stats in `set_limits`? Maybe there are other methods that can chance stats?

I've checked the `Survey`, the following methods can possibly change stats:
* `load_first_breaks`
* `filter`
* `set_limits`
* `generate_supergathers`
All of them change either `headers` or `limits`. One possible way to handle it is to introduce a new flag `dirty_stats`, similar to the one in `VelocityCube`, and check it every time the stats are requested, but I'd keep it as is for now since the fix is not that simple.

2021-12-09 16:12 UTC, alexandrkuvaev requested changes

2021-12-09 16:12 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +            Whether to remove data inplace or return a new survey instance, by default False
```suggestion
            Whether to remove traces inplace or return a new survey instance, by default False
```

2021-12-09 16:12 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        self.filter(lambda dt: dt == False, cols='DeadTrace', inplace=True)
```suggestion
        self.filter(lambda dt: ~dt, cols='DeadTrace', inplace=True)
```

2021-12-09 16:12 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        counter = 0
I'd rename it to something like `cur_quantile_trace_index`

2021-12-09 16:12 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        Calls `collect_stats` if `self.has_stats` flag is not set
```suggestion
        Calls `collect_stats` if `self.has_stats` flag is not set.
```

2021-12-09 18:58 UTC, a-arefina commented on seismicpro/src/survey.py
> +                           total=num_traces, disable=not bar):
```suggestion
        for i in tqdm(shuffled_indices, desc=f"Calculating statistics for survey {self.name}",
                      total=num_traces, disable=not bar):
```

2021-12-09 19:04 UTC, a-arefina commented on seismicpro/src/survey.py
> +        counter = 0
what about `quantile_traces_counter`?

2021-12-10 06:16 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        counter = 0
Up to you, much better than simply `counter` anyway)

2021-12-10 07:54 UTC, alexandrkuvaev approved these changes

2021-12-10 08:12 UTC, anton-br approved these changes

2021-12-10 08:17 UTC, dpodvyaznikov approved these changes

2021-12-10 08:20 UTC, merged