Weathering velocity
gazprom-neft/SeismicPro pull request #76
Opened 2021-12-23 13:15 UTC by bestetc

2021-12-27 21:42 UTC, alexandrkuvaev requested changes

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +    def calculate_weathering_velocity(self, picking_col='FirstBreak', n_layers=None, initial=None, bounds=None):
```suggestion
    def calculate_weathering_velocity(self, first_breaks_col='FirstBreak', n_layers=None, init=None, bounds=None):
```

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +        return WeatheringVelocity(offset=self.offsets, picking_times=self.headers.get(picking_col), n_layers=n_layers,
Use square bracket syntax instead of `get`, rename `offset` to `offsets`

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +        print(f'n_layers={n_layers}, initial={initial}, bounds={bounds}')
Remove prints

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +            self.n_layers = len(initial) // 2
Check names of keys in `initial`

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +    def _calc_params(self, params: dict):
remove type annotation

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +                result[key] = value[0] + (value[1] - value[0]) / 3
Don't combine two fundamentally different logics in a single function

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +            try:
Why do you need `try`-`except`?

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +                self.initial, self.bounds = self._precalc_by_layers(n_layers)
Where is its implementation?

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +    def _create_keys(self):
Why is it a separate method? You use it once.

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +        return ['t0'] + [f'c{i+1}' for i in range(self.n_layers - 1)][:self.n_layers - 1] + \
You first create a list via a comprehension and then immediately slice it. Why?

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +                                      bounds=self._parse_params(self.bounds), method='trf', loss='soft_l1')
pass `kwargs` here

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +        work_dict = initial if bounds is None else bounds
bounds is always `None`, you call this method only with a single positional arg

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +        return (data[:, 0], data[:, 1])
Why not just stack dict values?

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +        return self.piecewise_linear(offset, *self._fitted_args.values())
Don't rely on key order

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +            times[i] = (cross_offset[i] - cross_offset[i-1]) / velocites[i-1] + times[i-1]
Vectorize this loop

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +        return np.interp(offset, cross_offset, times)
Use our interpolator from utils

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +    def calculate_weathering_metrics(self, wv, picking_col='FirstBreak', threshold_times=50):
We definitely should rename `wv`, also rename `picking_col` to `first_breaks_col`

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +    @batch_method(target='for', args_to_unpack='wv')
Have you benchmarked it?

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +    @batch_method(target='for')
Have you benchmarked it?

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +                    )
return self

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +                crossovers = ['{:.2f}'.format(getattr(self, f'c{i + 1}', -1)) for i in range(self.n_layers - 1)]
Why -1?

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +            velocities = ['{:.2f}'.format(getattr(self, f'v{i + 1}', -1)) for i in range(self.n_layers)]
Why -1?

2021-12-27 21:42 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +            trans = mtransforms.ScaledTranslation(1 / 5, -1 / 5, scale_trans=mtransforms.Affine2D([[100, 0, 0],
Why do you need this transform if you can simply specify text coordinates in `text`?

2021-12-28 10:19 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +            times[i] = (cross_offset[i] - cross_offset[i-1]) / velocites[i-1] + times[i-1]
This loop uses a value (t0) which calculated on a previous iter. No idea how to vectorize it.

2021-12-28 10:43 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +            trans = mtransforms.ScaledTranslation(1 / 5, -1 / 5, scale_trans=mtransforms.Affine2D([[100, 0, 0],
I need to make ident from plot edges that text don't cover a plot edges.
Current implemetation contain some hardcode, becuase based on figure's dpi=100. It's matplotlib defualt.
It could be fixed with forwarding `fig` into current plotter and get dpi from `fig` and made correct ident.

2021-12-28 11:09 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +        return np.interp(offset, cross_offset, times)
42 ms vs 28 ms per gather.

2021-12-28 11:15 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +            try:
while `_precalc_by_layers `do not implemented.

2021-12-28 11:49 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +    def _create_keys(self):
Twice now.

2021-12-29 10:10 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +                self.initial, self.bounds = self._precalc_by_layers(n_layers)
done

2022-01-14 13:32 UTC, bestetc commented on seismicpro/src/gather.py
> +    @batch_method(target='for', args_to_unpack='wv')
yes. 'for' much better

2022-01-14 14:00 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +        self._fitted_args = dict(zip(self._create_keys(), fitted))
I'd call them `params` and make public

2022-01-14 14:03 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +            velocity_title += ', '.join(velocities)
Extract params from fitted params dict and then combine them into titles

2022-01-14 14:28 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +            idx = np.argwhere((self.offsets >= cross_offsets[i]) & (self.offsets < cross_offsets[i +1 ]))[:, 0]
Just create mask

2022-01-14 14:28 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +                                                      np.take(self.picking_times, idx), start_params)
Why `take`, not square brackets?

2022-01-14 14:29 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +            start_params[1] = times[i] + (slopes[i] - start_params[0]) * self.offsets_max * (i + 1) / n_layers
You don't need to fit intercept for all the regressions except for the first one

2022-01-17 11:17 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +                                                      np.take(self.picking_times, idx), start_params)
Good, square brackets faster.

2022-01-18 09:26 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +            velocity_title += ', '.join(velocities)
change to parse `self.params` with same logic.

2022-01-18 09:30 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +    def _create_keys(self, n_layers=None):
change to `_get_valid_keys`

2022-01-18 23:15 UTC, alexandrkuvaev requested changes

2022-01-18 23:15 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +                    transform=ax.transAxes)
```suggestion
            params = [self.params[key] for key in self._get_valid_keys()]
            title = f"t0: {params[0]:.2f} ms"
            if self.n_layers > 0:
                title += "\nvelocities: " + ", ".join(f"{vel:.2f}" for vel in params[self.n_layers:]) + "km/s"
            if self.n_layers > 1:
                title += "\crossover offsets: " + ", ".join(f"{cross:.2f}" for cross in params[1:self.n_layers]) + "m"
            ax.text(0.03, .94, title, fontsize=15, va="top", transform=ax.transAxes)
```

2022-01-18 23:15 UTC, alexandrkuvaev commented on seismicpro/src/weathering_velocity.py
> +            start_params[1] = times[i] + (slopes[i] - start_params[0]) * self.max_offset * (i + 1) / n_layers
Double-check it, seems wrong for `n_layers` > 2

2022-01-24 14:59 UTC, nikita-klsh commented on seismicpro/src/weathering_velocity.py
> +        return np.interp(offsets, self._piecewise_offsets, self._piecewise_times)
Consider using SP interpolator

2022-01-24 14:59 UTC, nikita-klsh commented on seismicpro/src/weathering_velocity.py
> +                                         bounds=self._stack_values(self.bounds), **minimizer_kwargs)
List for x0 or list of lists for bounds are enough for scipy. 
As far as I understand `_stack_values` are more about ordering values. Just secure the proper order of `self.init` and `self.bounds`  in `self.check_keys`

```suggestion
        model_params = optimize.minimize(self.piecewise_linear, x0=list(self.init.values()),
                                         bounds=list(self.bounds.values()), **minimizer_kwargs)
```

2022-01-26 11:33 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +            start_params[1] = times[i] + (slopes[i] - start_params[0]) * self.max_offset * (i + 1) / n_layers
rework

2022-01-26 12:16 UTC, bestetc commented on seismicpro/src/gather.py
> +    def calculate_weathering_velocity(self, first_breaks_col='FirstBreak', n_layers=None, init=None, bounds=None,
I think that all `None` by defualt is good option, It should be help a user to better understand what a model could be fitted.
Under discussion.

2022-01-26 12:58 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +        return np.interp(offsets, self._piecewise_offsets, self._piecewise_times)
At starting I checked `np.interp`, `sp.interpolate` and `seismicpro.utils.interpolation.interp1d`.
`np.interp` was faster.

2022-01-26 16:48 UTC, nikita-klsh commented on seismicpro/src/weathering_velocity.py
> +        cross_offsets = np.linspace(0, self.max_offset, num=n_layers+1)
Also consider  what to do in this case if `crossover offset = 500`

2022-01-27 09:51 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +        lin_reg = SGDRegressor(loss='huber', early_stopping=True, penalty=None, shuffle=True, epsilon=0.01,
Added normalization to `calc_by_layers` to fix it. Time to work are increase.

2022-01-27 12:29 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +        lin_reg.fit(x, y, coef_init=start_params[0], intercept_init=start_params[1])
We used `self._n_iters` to understand better `init` calculation. So I don't think to store `n_iter` for these regression is needful.

2022-01-27 12:32 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +        start_params = [2/3, min(self.picking_times)]
Separate `start_params `and `times` and `slopes` arrays add readability for this part of a code.

2022-01-27 13:10 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +            ax.plot(self._piecewise_offsets, self._piecewise_times - threshold_times, '--', color='gray')
No.
@nikita-klsh shows an expected plot below. I rework plotter to make same result.

2022-01-27 13:10 UTC, bestetc commented on seismicpro/src/gather.py
> +    def calculate_weathering_metrics(self, weathering_velocity, first_breaks_col='FirstBreak', threshold_times=50):
`threshold_times` win the vote. `time_margin` is feeling as goods choice too.

2022-01-27 13:11 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +                                       bounds=self._stack_values(self.bounds), **kwargs)
Reworked to using `scipy.minimize` with `constraints`.

2022-01-27 13:11 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +        missing_keys = set(self._get_valid_keys()) ^ set(self.bounds.keys())
Split it to two checking for make error message more informative.

2022-02-22 15:16 UTC, anton-br commented on seismicpro/src/weathering_velocity.py
> +            ax.text(0.03, .94, title, fontsize=15, va='top', transform=ax.transAxes)
don't we want to control the size from the outside?

2022-02-22 15:25 UTC, anton-br commented on seismicpro/src/gather.py
> +            weathering metric
Describe what this number means

2022-02-22 15:33 UTC, anton-br commented on seismicpro/benchmark/benchmark.ipynb
>      "| scale_maxabs | threads | [scale_maxabs](#scale_maxabs) |\n",
<p>Delete warning please</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/76/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2022-02-22 15:33 UTC, anton-br commented on seismicpro/benchmark/benchmark.ipynb
>      "| scale_maxabs | threads | [scale_maxabs](#scale_maxabs) |\n",
<p>split Benchmark creation into two lines (this line is too long)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/76/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='44'/>

2022-02-22 15:33 UTC, anton-br commented on seismicpro/benchmark/benchmark.ipynb
>      "| scale_maxabs | threads | [scale_maxabs](#scale_maxabs) |\n",
<p>fix indends in this cell</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/76/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='46'/>

2022-02-22 15:59 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +                             f"negative values {list(negative_init.values())}")
confirm

2022-02-22 16:14 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +    All passed parameters have a greater priority than any calculated parameters.
Second variant.
It could be useful when you pass all `init` keys and some of a `bounds` keys.
gather.calculate_weathering_velocity(init={'t0': 100, 'x1': 1500, 'v1': 2, 'v2': 3},
                                                                   bounds={'t0': [0, 500]})
bounds for 't0' will calculated as [50, 200] and would rewrited with passed [0, 500]

2022-02-22 16:21 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +        start_slope = 2/3  # base slope corresponding velocity is 1,5 km/s (v = 1 / slope)
I proceeded from the fact that the data on the weathering velocity plot are presented as offsets in meters and picking times in ms. Gets the dimension of m/ms or km/s.

Also, reordering - goods idea.

2022-02-22 16:25 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +        self.init = {**self._calc_init_by_layers(n_layers), **self._calc_init_by_bounds(bounds), **init}
dcos have a mentioning by initialization. 
It seems that docs are not clear If you talk about it.

2022-02-22 16:37 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +                slopes[i], times[i] = self._fit_regressor(self.offsets[mask].reshape(-1, 1) / min_picking_times,
Slope and time are used. Slope is a coefficient of linear regression.
Dividing on `min_picking_times` it's regularization to correct fit the linear regression and haven't physical meaning.

2022-02-24 10:18 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +    def _get_valid_keys(self, n_layers=None):
Saving the expected keys in the class attribute is good idea.

2022-02-24 10:27 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +    def piecewise_linear(self, *args):
Separate to the `loss_piecewise_linear` and `_update_piecelinear_args`

2022-02-24 10:33 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +        lin_reg.fit(x, y, coef_init=start_params[0], intercept_init=start_params[1])
Saved all `minimize` parameters to the `_model_params` class attribute. `_n_iters` was removed.

2022-02-24 10:48 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +                                         bounds=self._stack_values(self.bounds), **minimizer_kwargs)
add reodrdering dicts and `_stack_values()` are removed

2022-02-24 11:05 UTC, a-arefina commented on seismicpro/src/weathering_velocity.py
> +            start_time = times[i] + (slopes[i] - start_slope) * (cross_offsets[i + 1] / min_picking_times)
slopes[i] and start_times[i] are coefficient and intercept of linear regression for th i-th layer
here, you pre-compute starting intercept for the next layer assuming that the whole piecewice-linear `init` function is continious, and `start_times[i] + cross_offsets[i + 1]*slopes[i] ==start_times[i + 1] + cross_offsets[i + 1]*slopes[i+1]  `, but this equality holds only if `slopes[i+1] == start_slope`, after fitting `slopes[i+1] ` fot the next layer piecewice-linear is no more continious

in the line 249 you actually make it continious again,  discarding all itercepts, except the first one, so the fitted slopes now correspond to the implicit intercepts that come from the previous layer

Are you OK with that? if such a rough initial guess is suffucient, maybe a simplier procedure can be used to obtain it?

2022-03-03 12:10 UTC, bestetc commented on seismicpro/src/gather.py
> +            Initial value for a weathering model.
I used naming from "Computation_of_refraction_static_corrections_using_first" paper.
I have also seen the "intercept time" for `t1`, `t2` etc. Not for `t0`.

2022-03-17 16:15 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +                                               bounds=self._stack_values(self.bounds), **minimizer_kwargs)
Test it on the 5000 random gathers and 2-layers model.
There are no diff between `self._piecewise_offsets`, `self._piecewise_times` and `self.params` for `t0` and `x1`.
And calculation error up to 1e-8 for `v1` and `v2`.

2022-03-17 17:16 UTC, bestetc commented on seismicpro/src/weathering_velocity.py
> +        self._check_keys()
`bounds` have the same keys with `init` when `self._check_keys()` is called.
If keys problem found in `bounds` dict I'm sure that `init` is not good too.
Think `_check_keys` is good name.

2022-04-25 14:20 UTC, anton-br commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +        print(1 / lin_reg.coef_[0], lin_reg.intercept_, lin_reg.n_iter_)
delete plz :)

2022-05-05 09:15 UTC, dpodvyaznikov requested changes

2022-05-05 09:15 UTC, dpodvyaznikov commented on seismicpro/src/weathering_velocity/metrics.py
> +    def calc(gather, weathering_velocity, first_breaks_col=HDR_FIRST_BREAK, threshold_times=50, **kwargs):
I'd suggest to rename `threshold_time` to `threshold_ms` - this way the units become obvious
```suggestion
    def calc(gather, weathering_velocity, first_breaks_col=HDR_FIRST_BREAK, threshold_ms=50, **kwargs):
```

2022-05-05 13:33 UTC, dpodvyaznikov requested changes

2022-05-05 15:07 UTC, nikita-klsh commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +        self.n_layers = len(self.bounds) // 2
I suggest to distinguish this parts, make only the necessary validation checks and do the calculations only if the check passed

```suggestion
init = {**self._calc_init_by_bounds(bounds), **init}

if n_layers is not None:
    self.validate_excessive(init)
    self.n_layers = n_layers
    init = {**self._calc_init_by_layers(n_layers), **init}
else:
    self.validate_insufficient(init)
    self.n_layers = len(init) / 2
self.bounds = {**self._calc_bounds_by_init(), **bounds}
```

2022-05-06 08:23 UTC, nikita-klsh commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +        self._empty_layers = self._mask_empty_layers(list(self.init.values()))
```suggestion
        self._empty_layers = np.histogram(self.offsets, crossover_offsets)[0] >  0
```

2022-05-06 09:26 UTC, nikita-klsh commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +            "fun": lambda x: np.diff(np.concatenate((x[1:self.n_layers], [self.max_offset])))}
Is it ok that for parameters to optimize - `x`, say `len(x) = 6` in case 3 layers, `len(fun(x)) = 2`?

2022-05-11 07:18 UTC, bestetc commented on seismicpro/src/gather/plot_corrections.py
> +    def corrected_gather(self, event_headers=None):
No, I need to call the `corrected_gather` with different `event_headers` parameters. It's look like a method.

2022-05-11 07:36 UTC, bestetc commented on seismicpro/src/gather/gather.py
> +        if not isinstance(weathering_velocity, WeatheringVelocity):
It could be any callable that returns the expected breaking points by offset. WeatheringVelocity is already do it.

2022-05-11 07:52 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +            `v{i}`: velocity of the i-th layer. Measured in kilometers/seconds.
Weathering curve is function of picking points in milliseconds from offsets in meters. So using velocity in m/ms is naturally for this case. But m/ms is the same as km/s.
My comment don't make the units in code more consistent. But I want to fit the weathering curve in km/s. External units presentation could be the any.

2022-05-11 08:35 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +    Note: `gather.calculate_weathering_velocity` uses `from_picking` classmethod to create the WeatheringVelocity.
The most common way to calculate WeatheringVelocity is the gather method. Maybe the examples are not exhaustive and do not explain how to get a gazer.
Creating WeatheringVelocity directly from offsets and pickig times is for testing purposes and is not intended for common use.

2022-05-11 08:54 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +    Since the class uses the first break picking time to fit the detected velocities, any detected underlaying layers
Ascending velocity is constraint driven by the physical model. Sometimes the data does not follow the physical model, so I added options to turn off this constraint. It's help to explain the data better.

2022-05-11 09:26 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +            txt_kwargs = {**{'fontsize': 15, 'va': 'top'}, **txt_kwargs}
default fontsize is to small for my taste. Could be disscussed.

2022-05-11 13:11 UTC, bestetc commented on seismicpro/src/gather/gather.py
> +            data[i, start_lmo[i]:start_lmo[i] + lenght[i]] = self.data[i, start_raw[i]:start_raw[i] + lenght[i]]
1. ` data[i, :-ix] = gather.data[i, ix:]` should be crush if `ix` is 0. Slice [:-0] is interpreted as [:0].
 2. I checked with a benchmark. Your desision works faster with `threads`.
 
I combined the previous solution and your idea. Boost in 2.5 times with `threads`.

2022-05-11 13:26 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +            txt_kwargs = {**{'fontsize': 15, 'va': 'top'}, **txt_kwargs}
Default fontsize is too small, IMHO,in case we have an almost empty plot and a small amount of text.

2022-05-11 13:43 UTC, bestetc commented on seismicpro/src/weathering_velocity/metrics.py
> +    def calc(gather, weathering_velocity, first_breaks_col=HDR_FIRST_BREAK, threshold_times=50, **kwargs):
Is it a good idea to use `threshold_times` and `threshold` for the same parameter in different places?

2022-05-11 13:48 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +        bounds['t0'] = [min(0, bounds['t0'][0]), max(200, bounds['t0'][1])]
fixed

2022-05-11 13:58 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +                times[i] = start_time - start_slope * normalized_offsets.min() * (i==0)  # add first layer correction
Good point. I didn't fix this point after changing the normalization.

2022-05-11 14:35 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +        compared_params : dict, optional, defaults to None
Compare initial fit with final could be realize with:
```
wv = g.calculate_weathering_velocity(n_layers=2)
wv.plot(compared_params=wv.init)
```
I don't think that additional parametrization is needed.

2022-05-11 14:44 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +            ax.plot(compared_offsets, compared_times, '-', color='#ff7900', label='compared piecewise function')
Noted. I tried to implement this, but the plot is cluttered or code i cluttered so I left only the curve.
I need to think how make it clear.

2022-05-12 10:56 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +                                                          fit_intercept=(i==0))
1. After you fit the N linear regressions you should combine result to one piecewise linear curve. It could be hard for some case.
2. Heuristic follows to init if no data is found. In some case it comes to bad intercept for next layers. It's mean that minimize should work more and time to calculate WeatheringVelocity would be more.
3. Worse case if layer contains the some outliers only. How to avoid this?
4. Logic to combine the N linear regression to one piecewise linear function could be smarter.

2022-05-12 12:56 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +        self._valid_keys = self._get_valid_keys()
`self._valid_keys` close to `self._validate_keys()`, `self._validate_values()` naming.
Think to change docs will better.

2022-05-12 13:28 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +            times[i] = max([0, times[i]])  # move minimal time to zero
Our assumtion that the seismic record starts at one time with expose of the source.
I could remove it or make it optional. Disscused.

2022-05-12 13:43 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +        wave from the first subweathering layer.
Sometimes 'v1' is the direct wave velocity, not a first refractor velocity.
Think it's important info. But if it confusing it should be removed.

2022-05-12 13:45 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +        self._empty_layers = self._mask_empty_layers(list(self.init.values()))
nice

2022-05-12 14:04 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +            "fun": lambda x: np.diff(np.concatenate((x[1:self.n_layers], [self.max_offset])))}
The cite from constraints docs:
The constraint has the general inequality form::
        lb <= fun(x) <= ub
Here the vector of independent variables x is passed as ndarray of shape
(n,) and ``fun`` returns a vector with m components.

2022-06-06 09:32 UTC, dpodvyaznikov commented on seismicpro/src/gather/utils/correction.py
> +            gather_data[i, start_raw[i]:start_raw[i] + traces_lenght_lmo[i]]
```suggestion
        corrected_gather[i, start_lmo[i]:start_lmo[i] + traces_length_lmo[i]] = \
            gather_data[i, start_raw[i]:start_raw[i] + traces_length_lmo[i]]
```

2022-06-06 09:32 UTC, dpodvyaznikov commented on seismicpro/src/gather/utils/correction.py
> +    n_traces, trace_lenght = corrected_gather.shape
```suggestion
    n_traces, trace_length = corrected_gather.shape
```

2022-06-06 13:11 UTC, bestetc commented on seismicpro/src/gather/gather.py
> +        freeze_t0 : bool, defaults to False
I'd like to use `t0`, because `t0` is specific parameters of weathering model. Also known as intercept time.
Could be discussed.

2022-06-14 13:23 UTC, bestetc commented on seismicpro/src/gather/gather.py
> +        ascending_velocity : bool, defaults to True
"descending" and "ascending" are common names for the sort function in python.

2022-06-20 10:50 UTC, alexanderkuvaev requested changes

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +    `from_constant` - creates a WeatheringVelocity instance based on the 1-layer weathering model with zero intercept
Let's call it `from_constant_velocity` to match `StackingVelocity` class

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +        `t0`: a intercept time of the first subweathering layer. Same as double wave travel time to the first
```suggestion
        `t0`: a intercept time of the first subweathering layer. Same as two-way travel time to the first
```
To match common seismic notation

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +    Note: Gather's method `calculate_weathering_velocity` uses the `from_picking` classmethod.
I'd change it to an example:

The same can be done by just calling a `calculate_weathering_velocity` method of the gather:
`>>> ...`

This will highlight the expected creation of an instance

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +    picking_times : 1d ndarray
Usually it's called `traveltimes`, probably I'd rename it

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +        Coordinates object.
```suggestion
        Spatial coordinates at which refractor velocity is estimated.
```

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +        self.interpolator = lambda offsets: np.zeros_like(offsets, dtype=np.float32)
Let's make it `None` or non-`lambda` callable by default to make it picklable

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +    def from_picking(cls, offsets, picking_times, init=None, bounds=None, n_layers=None, acsending_velocities=True,
Remove `acsending_velocities` and `freeze_t0`

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +    def from_constant(cls, velocity, coords=None):
```suggestion
    def from_constant_velocity(cls, velocity, coords=None):
```

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +        """Get spatial coordinates of the stacking velocity.
Not a stacking :(

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +        compared_params : dict, optional, defaults to None
We've decided to pass an instance here, haven't we?

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +            compared_params=None, txt_kwargs=None, **kwargs):
```suggestion
             compared_params=None, text_kwargs=None, **kwargs):
```
`text_kwargs` are not described in the method docs

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/gather/utils/correction.py
> +def apply_lmo(gather_data, picking_estimate, delay, fill_value):
rename `picking_estimate` to `trace_delays` or something like this, no "picking" should appear here

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/gather/plot_corrections.py
> +        self.event_headers = None
`event_headers` should be inferred from `kwargs` here, not in plot

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/gather/plot_corrections.py
> +    def plot_corrected_gather(self, ax, **kwargs):
Remove this method, it's already implemented in the base class. If you need grid that much, also implement it for interactive NMO correction in the base class

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +    def plot_lmo_correction(self, min_vel=800, max_vel=6000, figsize=(6, 4.5), **kwargs):
Too much for an upper section, I'd make default limits [500, 3000]

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +    def apply_lmo(self, weathering_velocity, delay=100, fill_value=0, event_headers=None):
Match docs and signature

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +        event_headers = (set(to_list(event_headers['headers'])) if isinstance(event_headers, dict)
Why do you want to pass `event_headers` as a `dict` here?

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +        fb_estimate = times_to_indices(weathering_velocity(self.offsets), self.samples, round=True).astype(int)
Avoid picking, it's delay

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +        first_breaks_col : str, optional, defaults to HDR_FIRST_BREAK
Either keep it as it was, or make a sphinx link to `HDR_FIRST_BREAK`.

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +            raise ValueError("One of `init`, `bounds` or `n_layers` should be defined.")
This check should be inside `WeatheringVelocity` class

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/gather/metrics.py
> +    vmax = 0.05
What have we decided to do with default `vmax`?

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/gather/metrics.py
> +    name = "weathering_metrics"
It's not a weathering metric now

2022-06-20 10:50 UTC, alexanderkuvaev commented on seismicpro/src/__init__.py
> +from .weathering_velocity import WeatheringVelocity
Why not?

2022-06-20 14:36 UTC, alexanderkuvaev commented on seismicpro/src/gather/utils/correction.py
> +def apply_lmo(gather_data, picking_estimate, delay, fill_value):
I'd definitely keep it as `delay`. Probably `global_delay`, but I like it less

2022-06-20 15:15 UTC, bestetc commented on seismicpro/src/gather/metrics.py
> +    vmax = 0.05
One outlier can result in only one gather being red. By default you want to see all gathers with "not good" picking.

2022-06-21 10:15 UTC, bestetc commented on seismicpro/src/weathering_velocity/weathering_velocity.py
> +            `n_layers` : number of the weathering model layers.
Removed after discussion

2022-06-28 10:27 UTC, alexanderkuvaev requested changes

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +        return self
1. calculate float `trace_delays` by subtracting `delay` from `refractor_velocity(self.offsets)`
2. cast them to `int`. Here you'll make a single cast instead of two in your case which may lead to poorer precision
3. remove `common_delay` from `apply_lmo` signature - use only precalculated values from step 2. This will simplify further implementation of statics correction which will rely on this interface
4. Don't recast `int` delays back to `float` during headers processing, just use values from step 1. Once again, you're using precision here

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +    def calculate_refractor_velocity(self, first_breaks_col=HDR_FIRST_BREAK, init=None, bounds=None, n_layers=None,
I still prefer `n_refractors` more

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +               The headers corresponding to gather's coordinates should be preloaded or use `coords_cols=None`.
Remove

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +            Column name from `self.headers` where first breaking times are stored.
```suggestion
            Column name from `self.headers` where first break times are stored.
```

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +            Additional keyword arguments.
```suggestion
            Additional keyword arguments to be passed to :func:`~refractor_velocity.RefractorVelocity.from_first_breaks`.
```

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/gather/plot_corrections.py
> +        self.corrected_gather.plot(ax=ax, y_ticker={"step_labels": 100}, **kwargs)
Remove `y_ticker` hardcode, it can be passed in `kwargs`

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/gather/plot_corrections.py
> +        ax.grid(which='major', axis='y', color='k', linestyle='--')
Allow for grid disabling

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/gather/utils/correction.py
> +def apply_lmo(gather_data, trace_delays, common_delay, fill_value):
Read comments to `gather.apply_lmo`: I'd keep only `trace_delays` here

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/gather/utils/correction.py
> +        Estimate samples of first break picking for each traces with shape (num_traces,).
Remove "first breaks"

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +    The class could be created from `from_first_breaks`, `from_params`, and `from_constant_velocity` classmethods.
```suggestion
    An instance can be created using one of the following `classmethod`s:
```

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        * `from_params` - creates a RefractorVelocity instance and stores the given parameters of the velocity model.
```suggestion
        * `from_params` - creates a `RefractorVelocity` instance from given parameters without model fitting.
```

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +                            intercept time and given velocity. Stored parameters of the velocity model in `params`.
```suggestion
        * `from_constant` - creates a single-layer `RefractorVelocity` with zero intercept time and given velocity of the refractor.
```
Model parameters are always stored in `params`, no need to repeat it every time

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +                                the fitted parameters.
```suggestion
        * `from_first_breaks` - fits a near-surface velocity model by offsets and times of first breaks.
```

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +    Some of class attributes and classmethod's arguments have a valid key notation.
```suggestion
    Parameters of the constructed velocity model can be obtained by accessing the following attributes:
```
You often use "valid key notation" without even defining what it is. I'd remove it at all since it confuses more than helps.

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        `t0`: a intercept time of the first subweathering layer. Same as two-way travel time to the first
```suggestion
        `t0`: an intercept time of the first subweathering layer. Same as two-way travel time to the first
```

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +    >>> refractor_velocity = RefractorVelocity.from_params(params={'t0': 100, 'x1': 1500, 'v1': 2, 'v2': 3})
Do we still pass velocities in km/s?

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +    Two layers refractor model by `n_layers`:
```suggestion
    Fit a two-layer refractor velocity model:
```

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +    Two layers refractor model by `init`:
```suggestion
    Fit a two-layer refractor velocity model using initial values of its parameters:
```

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +    One layers refractor model by `bounds`:
Fit a single-layer model with bounds constraints:

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        keys and values. Have the valid key notation.
Remove "Have the valid key notation."

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        An interpolator returning expected first breaking by given offset.
```suggestion
        An interpolator returning expected arrival times by given offset.
```

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +            compare_to=None, text_kwargs=None, **kwargs):
```suggestion
             compare_to=None, text_kwargs=None, **kwargs):
```

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +            Shows the velocity model parameters on a plot.
```suggestion
            Shows the velocity model parameters on the plot.
```

2022-06-28 10:27 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +                       label=crossoffset_label if self.n_layers <= 2 else crossoffset_label + 's' if i == 0 else None)
Why there are so many magic constants popped from `kwargs`? Simplify it.

2022-06-28 10:28 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +    def plot_lmo_correction(self, min_vel=800, max_vel=6000, figsize=(6, 4.5), **kwargs):
5k is still a lot

2022-06-29 10:23 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +    Some of class attributes and classmethod's arguments have a valid key notation.
I often use "valid key notation" and explain what that means in a separate block in the class's docstring.
It may bea good idea to add "valid key notation" to the head of this block to help the users find this block.

2022-06-29 10:24 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +                       label=crossoffset_label if self.n_layers <= 2 else crossoffset_label + 's' if i == 0 else None)
This is a way to parameterize the colors of all lines and their labels. This simplifies "comare_to" and makes the plotter more flexible.
Another way is to add the "is_compared" flag and use it to select from a predefined dict with params which color and label is used in for current line.

2022-06-30 11:47 UTC, alexanderkuvaev requested changes

2022-06-30 11:47 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +    Some of class attributes and classmethod's arguments have a valid key notation.
The explanation is unclear, just apply suggestion below this block.

2022-06-30 11:47 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +              refractor. Measured in milliseconds.
```suggestion
        `t0`: two-way travel time from a shot to a receiver just above it on the surface for uphole surveys. Measured in milliseconds.
```

2022-06-30 11:47 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +                a refracted wave from the next underlaying layer. Measured in meters.
```suggestion
        `x{i}`: crossover offset: the offset where a wave refracted from the i-th layer arrives at the same time as
                a wave refracted from the next underlaying layer. Measured in meters.
```

2022-06-30 11:47 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +        velocity : float,
```suggestion
        velocity : float
```

2022-06-30 11:47 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +                                                                              if i == 0 else None)
Move all these kwargs being popped to a `plot` signature.

2022-06-30 11:47 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +            Additional keyword arguments to the plotter.
Does not clarify things at all

2022-06-30 11:47 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +    stored in class atributes with corresponding names. All passed parameters have a greater priority.
```suggestion
    The same names are used as keys in `init` and `bounds` dicts passed to `RefractorVelocity.from_first_breaks` constructor. Some keys may be omitted in one dict if it's passed in another, e.g. one can pass only bounds for `v1` without an initial value, which will be inferred automatically. Both `init` and `bounds` dicts may not be passed at all if `n_refractors` is given.

```
And remove all "valid key notation", this line + all the examples below should be enough

2022-07-06 08:36 UTC, alexanderkuvaev commented on seismicpro/benchmark/benchmark.ipynb
>      "| mute | threads | [mute](#mute) |\n",
<p>We don't have <code>get_central_cdp</code> anymore, looks like erronous merge. Fix it, please</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/76/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2022-07-06 08:36 UTC, alexanderkuvaev commented on seismicpro/benchmark/benchmark.ipynb
>      "| mute | threads | [mute](#mute) |\n",
<p>remove</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/76/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2022-07-06 08:36 UTC, alexanderkuvaev commented on seismicpro/benchmark/benchmark.ipynb
>      "| mute | threads | [mute](#mute) |\n",
<pre class="ql-syntax" spellcheck="false">Line #1.    survey.headers['FirstBreak'] = np.abs(survey.headers['offset'] / 1.5 + np.random.normal(0, 30, size=survey.headers['offset'].shape))
</pre><p>Move it to the previous cell, don't use <code>survey.headers["my_header"]</code>, just <code>survey["my_header"]</code></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/76/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='9'/>

2022-07-06 08:36 UTC, alexanderkuvaev commented on seismicpro/benchmark/benchmark.ipynb
>      "| mute | threads | [mute](#mute) |\n",
<p>Why is it stacking velocity here, while you benchmark resample?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/SeismicPro/pull/76/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='51'/>

2022-07-06 09:29 UTC, bestetc commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +            ax.scatter(self.offsets, self.fb_times, s=1, color='black', label='first breaks')
Consulted with @nikita-klsh about how this plot should look and make it.
Tell me if you need to make it parametrize it all.

2022-07-06 09:49 UTC, bestetc commented on seismicpro/src/gather/plot_corrections.py
> +            self.event_headers = None
not work if pass empty dict (don't know why).

2022-07-06 10:43 UTC, alexanderkuvaev commented on seismicpro/src/refractor_velocity/refractor_velocity.py
> +            ax.scatter(self.offsets, self.fb_times, s=1, color='black', label='first breaks')
I just need it to be without dirty hardcode

2022-07-06 10:44 UTC, alexanderkuvaev commented on seismicpro/src/gather/plot_corrections.py
> +            self.event_headers = None
`gather.plot` does not work either, so that's fine

2022-07-06 14:00 UTC, bestetc commented on seismicpro/src/gather/plot_corrections.py
> +            self.event_headers = None
fix it with
```
        event_headers = kwargs.pop("event_headers", {})
        event_headers = event_headers if event_headers else None
```

2022-07-07 10:57 UTC, alexanderkuvaev requested changes

2022-07-07 17:23 UTC, merged