Extract dead traces
gazprom-neft/SeismicPro pull request #79
Opened 2022-01-11 09:09 UTC by a-arefina

resolves #78 

this PR also introduces new custom_headers module that contains names of headers added by SP. The motivation for creating constants for such headers is that
1) Errors in string literals are easily done but they can lead to errors that can be unnoticed. Constants are controlled by IDE's, and if not, errors are detected by the interpretator,
2) It is good to have a list of custom headers for future survey dumping

Another thing to consider is whether we need to check that dead traces header is already set in `collect_stats`. This can prevent us from reading dead traces data, but will make the code more complex because we'll need to handle non-default `indices` case.

2022-01-13 13:15 UTC, nikita-klsh commented on seismicpro/src/custom_headers.py
> +""" Custom headers added by SeismicPro to those from SEG-Y file """
```suggestion
""" Custom headers optionally added by SeismicPro to those from SEG-Y file """
```

2022-01-13 13:15 UTC, nikita-klsh commented on seismicpro/src/survey.py
> +
rm blank line

2022-01-13 13:15 UTC, nikita-klsh commented on seismicpro/src/survey.py
> +        survey : Survey with a new `DeadTrace` header created.
return block style is a bit inconsistent with SP

2022-01-13 13:15 UTC, nikita-klsh commented on seismicpro/src/survey.py
> +
one blank line is enough

2022-01-13 13:15 UTC, nikita-klsh commented on seismicpro/src/survey.py
> +    def mark_dead_traces(self, bar=True):
Are there cases when we want to call `mark_dead_traces` without calling `remove_dead_traces` afterwards?

2022-01-13 14:27 UTC, a-arefina commented on seismicpro/src/survey.py
> +    def mark_dead_traces(self, bar=True):
I guess yes - when performing QC

2022-01-14 07:53 UTC, anton-br commented on seismicpro/src/survey.py
> +        for pos in tqdm(traces_pos, desc=f"Calculating statistics for survey {self.name}",
basically, you are not calculating statistics here, just marking dead traces.

2022-01-14 07:53 UTC, anton-br commented on seismicpro/src/survey.py
> +        """ Mark dead traces (those having constant amplitudes) by setting a value of a new `DeadTrace`
delete first space

2022-01-14 07:53 UTC, anton-br commented on seismicpro/src/custom_headers.py
> +""" Custom headers optionally added by SeismicPro to those from SEG-Y file """
Delete spaces on both sides of the sentence

2022-01-14 07:53 UTC, anton-br commented on seismicpro/src/survey.py
> +            self.mark_dead_traces(**kwargs)
Consider adding `bar` to function arguments. Do you really need kwargs for a single argument?

2022-01-14 07:53 UTC, anton-br commented on seismicpro/src/custom_headers.py
> +HDR_DEAD_TRACE = 'DeadTrace'
If we use constants for new columns, what about adding a constant for `TRACE_SEQUENCE_FILE` then?

2022-01-14 07:53 UTC, anton-br commented on seismicpro/src/tests/survey/test_stats.py
> +    def test_mark_dead_traces(self, stat_segy):
This pull request is mostly created to fix the case when we deleted the wrong traces on the train/test/val subsets. Consider adding a test to this case then.

2022-01-14 10:51 UTC, a-arefina commented on seismicpro/src/custom_headers.py
> +""" Custom headers optionally added by SeismicPro to those from SEG-Y file """
```suggestion
"""Custom headers optionally added by SeismicPro to those from SEG-Y file"""
```

2022-01-14 10:51 UTC, a-arefina commented on seismicpro/src/survey.py
> +        """ Mark dead traces (those having constant amplitudes) by setting a value of a new `DeadTrace`
```suggestion
        """Mark dead traces (those having constant amplitudes) by setting a value of a new `DeadTrace`
```

2022-01-14 10:51 UTC, a-arefina commented on seismicpro/src/survey.py
> +        for pos in tqdm(traces_pos, desc=f"Calculating statistics for survey {self.name}",
```suggestion
        for pos in tqdm(traces_pos, desc=f"Detecting dead traces for survey {self.name}",
```

2022-01-14 11:33 UTC, a-arefina commented on seismicpro/src/tests/survey/test_stats.py
> +    def test_mark_dead_traces(self, stat_segy):
Marking dead traces works correctly only for the whole survey. I'll think aboun this

2022-01-14 11:34 UTC, a-arefina commented on seismicpro/src/custom_headers.py
> +HDR_DEAD_TRACE = 'DeadTrace'
I agree
I'll do that if no one minds

2022-01-20 11:49 UTC, a-arefina commented on seismicpro/src/tests/survey/test_stats.py
> +    def test_mark_dead_traces(self, stat_segy):
mark_dead_traces cannot be called from train/test/validation subsets, it can be called only for a full survey, so no problem here

2022-01-21 08:53 UTC, alexandrkuvaev requested changes

2022-01-21 08:53 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +                        "Run `mark_dead_traces`to remove this warning")
```suggestion
                        "Run `mark_dead_traces` to remove this warning")
```

2022-01-21 08:53 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
>                        total=n_traces, disable=not bar):
Align the lines, please

2022-01-21 08:53 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +            traces_buf = traces_buf[:n_quantile_traces]
Do you still need to call it if traces for quantile calculation are not filtered in the loop now?

2022-01-21 08:53 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        header to `True` and stores the overall number of dead traces in the `n_dead_traces` attribute.
```suggestion
        header to `True` and store the overall number of dead traces in the `n_dead_traces` attribute.
```

2022-01-21 08:53 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +                      total=len(self.headers), disable=not bar):
Align the lines

2022-01-21 08:53 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +        self.headers.iloc[dead_indices, self.headers.columns.get_loc(HDR_DEAD_TRACE)] = True
`dead_indices` stores TSF headers, not trace indices, so you can't simply use `iloc` here: TSF may differ from an ordinal number of the trace if e.g. you filter the survey first.

2022-01-21 08:53 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
>          """ Removes dead (constant) traces from survey's data.
```suggestion
        """ Remove dead (constant) traces from survey's data.
```
I'd also change `data` to something more appropriate, since `data` may be confused with trace data, which the survey does not store

2022-01-21 10:42 UTC, a-arefina commented on seismicpro/src/custom_headers.py
> +HDR_DEAD_TRACE = 'DeadTrace'
after some discussion with @alexandrkuvaev we decided not to make constans for standard SEG-Y headers, so that constants list doesn't grow too large

2022-01-21 11:47 UTC, a-arefina commented
I've fixed all PR comments, but I'm still thinking on how to add a survey with permuted `TRACE_SEQUENCE_FILE` header to tests using as simple code as possible

2022-01-21 13:07 UTC, a-arefina commented on seismicpro/src/survey.py
> +        self.headers.iloc[dead_indices, self.headers.columns.get_loc(HDR_DEAD_TRACE)] = True
switched to iloc-ing by positional index

2022-01-21 14:17 UTC, anton-br commented on seismicpro/src/survey.py
> +    def traces_checked(self):
a would add dead traces to the property name. For now, It is not clear what was checked.
For example `is_dead_traces_marked`

2022-01-25 20:35 UTC, dpodvyaznikov approved these changes

2022-01-25 20:35 UTC, dpodvyaznikov commented on seismicpro/src/tests/survey/test_stats.py
> +        """Check that `mark_dead_traces` properly updates survey `headers` and sets `n_dead_traces` counter to 0."""
```suggestion
        """Check that `mark_dead_traces` properly updates survey `headers` and sets `n_dead_traces` counter."""
```

2022-01-25 20:35 UTC, dpodvyaznikov commented on seismicpro/src/tests/survey/test_stats.py
> +            is_dead = np.isclose(trace_data.min(axis=1), trace_data.max(axis=1))
I don't like that here we re-implement the code that we want to test.
`is_dead` is indirectly defined by constants in `stat_segy`, maybe we should derive it from them?

2022-01-26 08:38 UTC, a-arefina commented on seismicpro/src/tests/survey/test_stats.py
> +            is_dead = np.isclose(trace_data.min(axis=1), trace_data.max(axis=1))
In this test, we can get both surveys with and without dead traces. Detecting wheter a trace is dead or not is trivial, and I see no evel in re-impleneting the detection, because the more complex part is validatinig that trace indices are consistent after (possible) dead traces removal.

2022-01-27 08:51 UTC, alexandrkuvaev requested changes

2022-01-27 08:51 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +    def is_dead_traces_marked(self):
I liked the previous naming much more, but won't insist since it will be renamed in the near future anyway.
In any case, it should be called `are_dead_traces_marked` at least.

2022-01-27 08:51 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +            self.load_trace(buf=trace, index=pos, limits=self.limits, trace_length=n_samples)
Don't get why you use `self.limits` here. Either load the whole traces from the file or allow for limit specification as in `collect_stats`. If you choose the first option, mention it in docs.

2022-01-27 08:51 UTC, alexandrkuvaev commented on seismicpro/src/tests/survey/test_stats.py
> +                                       limits, n_quantile_traces, quantile_precision, stats_limits):
strange line wrapping

2022-01-27 10:46 UTC, a-arefina commented on seismicpro/src/survey.py
> +    def is_dead_traces_marked(self):
`dead_traces_marked` ?

2022-01-27 10:52 UTC, alexandrkuvaev commented on seismicpro/src/survey.py
> +    def is_dead_traces_marked(self):
+, we'll rename it as soon as @dpodvyaznikov adds more trace QC methods

2022-01-27 11:56 UTC, alexandrkuvaev approved these changes

2022-01-27 11:56 UTC, merged