Add "hist" mode in `gather.plot`
gazprom-neft/SeismicPro pull request #80
Opened 2022-01-18 13:58 UTC by dpodvyaznikov

Changes summary:
* added `'hist'` mode in `gather.plot` method to plot histograms of gather data amplitudes of gather's header values;
* changed logic of ticker location mapping to ticker labels: now it uses `np.interp1d` with `'nearest'` mode;
* refactored ticker setting methods and functions.

2022-01-21 12:02 UTC, nikita-klsh reviewed
As far as I understand, the motivation for such structure refactoring is the hist plot tickers. TBH the previous plot structure looks more clear to me. My suggestion how to unify the hist plot with other modes:

1. Hist plot becomes just another mode of `plotters_dict`
2.  Tickers inference  happens inside `plotters_dict[mode]`. Each mode knows how to infer it's own tickers(labels and title) (from headers or from `plt.hist`)
3. Method `_set_ticks` now only SETS tickers, and not infering them (inference happens on the prev. step)

2022-01-31 21:32 UTC, alexandrkuvaev requested changes

2022-01-31 21:32 UTC, alexandrkuvaev commented on seismicpro/src/utils/plot_utils.py
> +    """Pop text formatting args from `kwargs` and set them as defaults for args transformed to dickts."""
dickts :)
Also, here you use word `args` twice in a single sentence with two different meanings

2022-01-31 21:32 UTC, alexandrkuvaev commented on seismicpro/src/utils/plot_utils.py
> +                  for arg in args)
I'd probably split it into two operations: first cast each `arg` to a dict and then merge it with defaults

2022-01-31 21:32 UTC, alexandrkuvaev commented on seismicpro/src/utils/plot_utils.py
> +    ax_obj.set_label_text(label, **kwargs)
Let's group all `ax_obj` processing lines together as it was before

2022-01-31 21:32 UTC, alexandrkuvaev commented on seismicpro/src/utils/plot_utils.py
> +              step_labels=None, tick_range=None, round_to=0, **kwargs):
I'd place `tick_range` after `tick_labels`: all the following `kwargs` will generally be passed via `*_ticker`

2022-01-31 21:32 UTC, alexandrkuvaev commented on seismicpro/src/utils/plot_utils.py
> +        def formatter(label_ix, *args):
Unify `formatter` signature and move it outside if-else block next to `round_formatter`

2022-01-31 21:32 UTC, alexandrkuvaev commented on seismicpro/src/gather.py
> +            ax.fill_betweenx(y_coords, i, i + trace, where=(trace > 0), color=col, **kwargs)
Have you checked that identical `kwargs` can be passed to both `plot` and `fill_between`?

2022-02-01 16:08 UTC, anton-br commented on seismicpro/src/gather.py
> +    def _plot_histogram(self, ax, bins=50, x_tick_src="amplitude", log=False, x_ticker=None, y_ticker=None, grid=False,
don't like `src` in `x_tick_src` since it is not a batch and we don't have any src here. But cannot provide any other namings for now.

2022-02-01 16:08 UTC, anton-br commented on seismicpro/src/batch.py
> +                    src_title = as_dict(title_template, key='label')
why don't you like just `title`? We don't have other titles here

2022-02-01 23:06 UTC, dpodvyaznikov commented on seismicpro/src/gather.py
> +    def _plot_histogram(self, ax, bins=50, x_tick_src="amplitude", log=False, x_ticker=None, y_ticker=None, grid=False,
Well, `*_tick_src` identifies the source of the tick data for the axis, which makes sense.

2022-02-01 23:19 UTC, dpodvyaznikov commented on seismicpro/src/batch.py
> +                    src_title = as_dict(title_template, key='label')
Actually, we have - the one that is passed in signature and used to build `kwargs` for each `src`. It was redefined here which led to incorrect titles for plots of the second and following `src`'s.

2022-02-01 23:24 UTC, dpodvyaznikov commented on seismicpro/src/decorators.py
> -            kwargs = set_text_formatting(kwargs)
This would allow for more flexibility in plotters, since now `set_text_formatting` can be applied not only to `title` and `*_ticker`, but to any text-related parameters of the plot, e.g., legends or any other text caption on the axes.

2022-02-01 23:33 UTC, dpodvyaznikov commented on seismicpro/src/utils/plot_utils.py
> +                  for arg in args)
Like this? I don't fancy it, but would switch to this one If others agree

```suggestion
    dict_args = ({} if arg is None else as_dict(arg, key="label") for arg in args)
    text_args = ({**global_formatting, **arg} for arg in dict_args)
```

2022-02-01 23:45 UTC, dpodvyaznikov commented on seismicpro/src/gather.py
> +            ax.fill_betweenx(y_coords, i, i + trace, where=(trace > 0), color=col, **kwargs)
This change seemed to make sense since the most common parameters, like `'label'`, `'linewidth'`, `'linestyle'`, `'color'` are identical.

2022-02-01 23:56 UTC, dpodvyaznikov commented on seismicpro/src/utils/plot_utils.py
> +    """Pop text formatting args from `kwargs` and set them as defaults for args transformed to dickts."""
See in next commit

2022-02-01 23:56 UTC, dpodvyaznikov commented on seismicpro/src/utils/plot_utils.py
> +    ax_obj.set_label_text(label, **kwargs)
See in next commit

2022-02-01 23:56 UTC, dpodvyaznikov commented on seismicpro/src/utils/plot_utils.py
> +              step_labels=None, tick_range=None, round_to=0, **kwargs):
See in next commit

2022-02-03 07:20 UTC, a-arefina commented on seismicpro/src/gather.py
> +        x_tick_src = (self.sort_by if self.sort_by is not None else "index") if x_tick_src is None else x_tick_src
```suggestion
        x_tick_src = x_tick_src or self.sort_by or "index" 
```

2022-02-03 07:20 UTC, a-arefina commented on seismicpro/src/gather.py
> +            top_ax = self._plot_top_subplot(ax=ax, divider=divider, header_values=self[top_header].ravel())
you're returning top_ax to place a plot title there? 
Maybe move `ax.set_title(**{'label': None, **title})` from `plot` to `_finalize_plot`?

Or, at least add a comment

2022-02-03 07:20 UTC, a-arefina commented on seismicpro/src/semblance.py
> +        set_ticks(ax, "y", "Time", y_ticklabels, **y_ticker)
why did you remove '(ms)' ?

2022-02-03 12:39 UTC, nikita-klsh reviewed
How fully does hist mode support our ticker parametrization?

1. In this case `bins=10` and `step_ticks=1`. We expect that each of 10 bin would have it's own tick?

![image](https://user-images.githubusercontent.com/8656643/152338622-bccc90ce-1ea6-469d-bfb3-51b4a33519b5.png)
2. y locators has no effect when `log=True`
![image](https://user-images.githubusercontent.com/8656643/152339675-2c8717f8-2776-4e80-b9ac-0957ee211f75.png)
![image](https://user-images.githubusercontent.com/8656643/152339771-5395b83a-fecd-4139-98f9-839c64fc9a78.png)
3. y locators not working correctly when `log=False`
![image](https://user-images.githubusercontent.com/8656643/152339929-e307b84f-5922-47ff-b967-7ea8655ccc14.png)
![image](https://user-images.githubusercontent.com/8656643/152339985-9cd38d17-5594-4462-aeec-ff30bc5a1b41.png)
4. 
![image](https://user-images.githubusercontent.com/8656643/152340870-7cc34a75-8d0d-4bac-9ea9-f55e8154adbe.png)

2022-02-03 13:28 UTC, dpodvyaznikov commented on seismicpro/src/gather.py
> +            top_ax = self._plot_top_subplot(ax=ax, divider=divider, header_values=self[top_header].ravel())
Yes
I don't think that title setting should be in `finalize_plot`. Moreover - finalize_plot is not called in `_plot_histogram`, so we'd also need to call it there.

2022-02-03 13:34 UTC, dpodvyaznikov commented on seismicpro/src/gather.py
> +    def _finalize_plot(self, ax, divider, event_headers, top_header, x_ticker, y_ticker, x_tick_src, y_tick_src):
I don't mind renaming this function, but don't want to move tick setting. 
What do others think? @alexandrkuvaev @a-arefina

2022-02-03 13:34 UTC, dpodvyaznikov commented on seismicpro/src/gather.py
> +    def _finalize_plot(self, ax, divider, event_headers, top_header, x_ticker, y_ticker, x_tick_src, y_tick_src):
I don't mind renaming this function, but don't want to move tick setting. 
What do others think? @alexandrkuvaev @a-arefina

2022-02-03 13:40 UTC, dpodvyaznikov commented on seismicpro/src/semblance.py
> +        set_ticks(ax, "y", "Time", y_ticklabels, **y_ticker)
It is going to be added in `set_tick`

2022-02-03 13:56 UTC, dpodvyaznikov commented on seismicpro/src/utils/plot_utils.py
>          return label_value
Current implementation for `label_value=1.1` with `round_to=3` produces '1.1', while suggested option would produce '1.100', which may be excessive.
Moreover, in current implementation one can set `round_to=None` and get the full representation for each label regardless of number of decimals.

2022-02-03 14:50 UTC, nikita-klsh commented on seismicpro/src/utils/plot_utils.py
>          return label_value
For me getting 1.100 is what I expect passing `round_to=3`, if I understand `round_to` functionality correctly.
Here is how `round_to` works atm, it looks confusing to me
![image](https://user-images.githubusercontent.com/8656643/152364218-e795f57d-4403-456c-aca8-1d13f65ce7cd.png)

Refering to the [documentation](https://github.com/matplotlib/matplotlib/blob/710fce3df95e22701bd68bf6af2c8adbc9d67a79/lib/matplotlib/ticker.py#L312-L337), FuncFormatter is supposed to be instantiated by the function, which produces a string. We, however, return numpy scalar, which is somehow formatted latter(in different ways, as can be seen on the pic)

Btw my suggestion behaves exactly like the current in case of `None`

2022-02-03 15:03 UTC, dpodvyaznikov commented on seismicpro/src/utils/plot_utils.py
>          return label_value
Yep, my bad: in cases of `0` or `None` it works similarly, I'll use your version

2022-02-03 15:09 UTC, dpodvyaznikov commented on seismicpro/src/gather.py
> +        x_tick_src = (self.sort_by if self.sort_by is not None else "index") if x_tick_src is None else x_tick_src
Done

2022-02-03 16:56 UTC, a-arefina commented on seismicpro/src/gather.py
> +    def _finalize_plot(self, ax, divider, event_headers, top_header, x_ticker, y_ticker, x_tick_src, y_tick_src):
I also wanted to propose renaming but got stuck with a new name :(

I like the idea of separate functions that set ticks, draw optional axes, and set titles where needed. As I commented above, I feel rather uneasy that this function returns an axis, that is further returned to `plot` with a sole aim of setting a title at the correct place.

2022-02-04 11:19 UTC, dpodvyaznikov commented on seismicpro/src/gather.py
> +            top_ax = self._plot_top_subplot(ax=ax, divider=divider, header_values=self[top_header].ravel())
Done

2022-02-04 11:29 UTC, dpodvyaznikov commented
Replies for the Nikita's comment:
1. In this case `bins=10` and `step_ticks=1`. We expect that each of 10 bin would have it's own tick?
— step_ticks work in the units of the x-axis for hist plot. if the data range is 0-1 and you specify `step_ticks=0.1`, you'll get 10 ticks.
2. y locators has no effect when `log=True`
— this is intended and mentioned in docstrings.
3. y locators not working correctly when `log=False`
— This behavior is similar with  `wiggle` and `seismogram` modes. The problem is caused by `num` argument and LinearLocator - it usually sets from `num` to `num-2` ticks, depending on the data intervals and some edge cases.
4. step_labels have no effect
— in `hist` mode `tick_labels` are None, so that was intended. For clarity, now if `labels=None` and `step_labels` is specified, an error is raised.

2022-02-06 21:46 UTC, nikita-klsh approved these changes
Please modify docs for `x_ticker` and `y_ticker`, now they do not control source for tick labels.

2022-02-06 21:46 UTC, nikita-klsh commented on seismicpro/src/gather.py
> +    def _plot_wiggle(self, ax, title='', x_ticker=None, y_ticker=None, x_tick_src=None, y_tick_src='time',
Can we unify default value `title=None` like in other modes?

2022-02-06 21:46 UTC, nikita-klsh commented on seismicpro/src/gather.py
> +    def _plot_wiggle(self, ax, title='', x_ticker=None, y_ticker=None, x_tick_src=None, y_tick_src='time',
Can we actually make `ax, title, x_ticker and y_ticker` required positional args for all the modes. Now we just repeating defaults from `self.plot`

2022-02-06 21:46 UTC, nikita-klsh commented on seismicpro/src/gather.py
> +            Source of the labels to be plotted on x axis. For "seismogram" and "wiggle" can be either "index" (default
```suggestion
            Source of the tick labels to be plotted on x axis. For "seismogram" and "wiggle" can be either "index" (default
```

2022-02-06 21:46 UTC, nikita-klsh commented on seismicpro/src/gather.py
> +            Source of the data to be plotted on y axis. For "seismogram" and "wiggle" can be either "time" (default) or
```suggestion
            Source of the tick labels to be plotted on y axis. For "seismogram" and "wiggle" can be either "time" (default) or
```

2022-02-07 08:18 UTC, alexandrkuvaev approved these changes

2022-02-07 08:18 UTC, alexandrkuvaev commented on seismicpro/src/utils/plot_utils.py
>      ax_obj = getattr(ax, f"{axis}axis")
Move to `ax_obj` processing lines

2022-02-07 08:28 UTC, alexandrkuvaev approved these changes

2022-02-07 08:28 UTC, alexandrkuvaev commented on seismicpro/src/utils/plot_utils.py
>      FORMAT_ARGS = {'fontsize', 'size', 'fontfamily', 'family', 'fontweight', 'weight'}
Let's remove all the synonyms and keep only parameters, starting with `font`

2022-02-07 08:35 UTC, merged