Add resample action
gazprom-neft/SeismicPro pull request #81
Opened 2022-01-27 14:21 UTC by nikita-klsh

This adds gather resample action. 

When new sample rate is not an integer multiple of the old rate, amplitude interpolation is required.  `nearest`, `linear`, `cubic`, `fft`, `sinc` are available methods for interpolation with the most efficient backend under the hood(opencv, pillow or scipy).

Resampling at a less frequent rate(e.g. from 2ms to 4ms) decreases the frequency bandwidth and may cause a loss of information that cannot be restored. Because of that, prior to downsampling, anti-alias filter is applied by default. Anti-alis filter is Hanning tapper that acts like a low pass filter

2022-02-10 16:59 UTC, nikita-klsh commented on seismicpro/src/utils/interpolation.py
> +    for j in prange(len(data)):  # pylint: disable=not-an-iterable
Agree

2022-02-10 16:59 UTC, nikita-klsh commented on seismicpro/src/utils/interpolation.py
> +                        L[i, k] = common_multiplier * binomial(n, k) * (-1) ** (n - k)  / (y - k)
Done

2022-02-10 16:59 UTC, nikita-klsh commented on seismicpro/src/gather.py
> +            fir = scipy.signal.firwib(n, low, window=window, fs=fs, pass_zero='highpass', **kwargs)
thx, fixed

2022-02-11 14:58 UTC, anton-br commented on seismicpro/src/utils/interpolation.py
> +def calculate_lagrange_polynomials(n, new_samples, old_samples, indices):
rename `indices` since it a little bit confusing with `indices` from `resample`

2022-02-25 16:43 UTC, nikita-klsh commented on seismicpro/src/utils/interpolation.py
> +    L = np.empty((len(new_samples), n + 1))
Agree

2022-02-25 16:43 UTC, nikita-klsh commented on seismicpro/src/gather.py
> +    def bandpass(self, n, low=None, high=None, window='hamm', **kwargs):
Rename to `bandpass_filtter`

2022-03-30 12:08 UTC, dpodvyaznikov commented on seismicpro/src/gather.py
> +    def bandpass_filter(self, n, low=None, high=None, window='hamm', **kwargs):
Move both `bandpass_filter` and `resample` to general processing methods section

2022-03-30 12:14 UTC, dpodvyaznikov commented
Also, merge master into your branch to resolve conflicts. Also, that should fix pylint errors

2022-04-07 11:15 UTC, alexandrkuvaev requested changes

2022-04-07 11:15 UTC, alexandrkuvaev commented on seismicpro/src/gather/gather.py
> +            self.bandpass_filter(n, high=cutoff_ratio * nyquist_frequency)
```suggestion
            # Smoothly attenuate frequencies starting from 0.8 of the new Nyquist frequency so that all frequencies
            # above are zeroed out
            nyquist_frequency = 1000 / (2 * new_sample_rate)
            filter_size = int(40 * new_sample_rate / current_sample_rate)
            self.bandpass_filter(high=0.9 * nyquist_frequency, filter_size=filter_size, window="hann")
```
Mimic paradigm algorithm

2022-04-07 11:15 UTC, alexandrkuvaev commented on seismicpro/src/gather/gather.py
> +            self.bandpass_filter(n, high=cutoff_ratio * nyquist_frequency)
```suggestion
            # Smoothly attenuate frequencies starting from 0.8 of the new Nyquist frequency so that all frequencies
            # above are zeroed out
            nyquist_frequency = 1000 / (2 * new_sample_rate)
            filter_size = int(40 * new_sample_rate / current_sample_rate)
            self.bandpass_filter(high=0.9 * nyquist_frequency, filter_size=filter_size, window="hann")
```
Mimic paradigm algorithm

2022-04-11 12:02 UTC, alexanderkuvaev requested changes

2022-04-11 12:02 UTC, alexanderkuvaev commented on seismicpro/src/utils/interpolation.py
> +                polynomials[i, k] = common_multiplier * binomials[k] * (-1) ** (n - k)  / (y - k)
Replace this block of code into two for loops before and after interpolation point. This will:
1. Simplify the code a lot
2. Allow you to remove `binomial` function
3. Avoid overflow in `binomials` calculation

2022-04-13 14:20 UTC, alexanderkuvaev requested changes

2022-04-13 14:20 UTC, alexanderkuvaev commented on seismicpro/src/utils/interpolation.py
> +        for i, ix in enumerate(indices):
Consider swapping the loops and make the `indices` loop parallel. It would probably speed up the method in case of small number of traces of 1d `y`

2022-04-26 10:34 UTC, alexanderkuvaev approved these changes

2022-04-26 10:34 UTC, alexanderkuvaev commented on seismicpro/src/utils/interpolation.py
> +
Remove line

2022-04-26 10:34 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +        In case new sample rate is greater that the current one, the anti aliasing filter is used
```suggestion
        In case new sample rate is greater than the current one, the anti aliasing filter is used
```

2022-04-26 10:34 UTC, alexanderkuvaev commented on seismicpro/src/utils/interpolation.py
> +    # For given point, n + 1 neighbor samples are required to construct polynomial, find the index of leftmsot one
```suggestion
    # For given point, n + 1 neighbor samples are required to construct polynomial, find the index of the leftmost one
```

2022-04-26 10:34 UTC, alexanderkuvaev commented on seismicpro/src/utils/interpolation.py
> +    # Redflect times accordingly
```suggestion
    # Reflect times accordingly
```

2022-04-26 10:34 UTC, alexanderkuvaev commented on seismicpro/src/utils/interpolation.py
> +    # calculate Lagrange basis polynomials only once: they are the same at given position for all the traces
```suggestion
    # Calculate values of Lagrange basis polynomials only once: they are the same at given position for all the traces
```

2022-04-26 10:34 UTC, alexanderkuvaev commented on seismicpro/src/utils/interpolation.py
> +            # interpolate at given point: multiply base polynomials and correspondoing function values and sum
```suggestion
            # Interpolate function at given point by calculating dot product between values of Lagrange polynomials and
            # function values at the reference samples
```

2022-04-26 10:48 UTC, bestetc commented on seismicpro/src/utils/interpolation.py
> +        leftmost_indices = np.rint(_times_to_indices(x_new , x, False)) - N // 2
`_times_to_indices ` uses `np.rint` if round is True. 
Change to `_times_to_indices(x_new , x, True)` could be a good idea.

2022-04-26 11:10 UTC, nikita-klsh commented on seismicpro/src/utils/interpolation.py
> +        leftmost_indices = np.rint(_times_to_indices(x_new , x, False)) - N // 2
This is done intentionally to implicitely highlight the difference of rounding logic in if-else branches(which is a bit complicated).

2022-04-27 05:47 UTC, dpodvyaznikov commented on seismicpro/src/gather/gather.py
> +        Apply bandpass filter: remain  freequencies inside [30, 100] range.
```suggestion
        Apply bandpass filter: keep freequencies within [30, 100] Hz range.
```

2022-04-27 05:47 UTC, dpodvyaznikov commented on seismicpro/src/gather/gather.py
> +        Apply lowpass filter,  remove all the freequencies above 100.
```suggestion
        Apply lowpass filter, remove all the freequencies above 100 Hz.
```

2022-04-27 05:47 UTC, dpodvyaznikov commented on seismicpro/src/gather/gather.py
> +        Apply highpass filter: remove all the freequencies bellow 30.
```suggestion
        Apply highpass filter: remove all the freequencies bellow 30 Hz.
```

2022-04-27 05:47 UTC, dpodvyaznikov commented on seismicpro/src/gather/gather.py
> +            In case str, deligate interpolation to scipy.interp1d.
```suggestion
            The interpolation method to use.
            If int, use piecewise polynomial interpolation with degree `kind`; if str, deligate interpolation to scipy.interp1d with mode `kind`.
```

2022-04-27 08:50 UTC, nikita-klsh commented on seismicpro/src/gather/gather.py
> +            In case str, deligate interpolation to scipy.interp1d.
Too long line.
The resulted version is somewhere in between

2022-04-27 09:54 UTC, dpodvyaznikov approved these changes

2022-04-27 10:27 UTC, merged