Add gain functions and update Benchmark
gazprom-neft/SeismicPro pull request #95
Opened 2022-04-22 07:25 UTC by dpodvyaznikov

Summary of changes:
* `apply_agc` method was intorduced for automated gain control, which irreversably modifies trace amplitudes by applying a scaling factor that depends on aggregated trace amplitudes in  shifting time windows;
* `apply_sdc` and `undo_sdc `gather methods were added for spherical divergence corrections;
* benchmark notebook was completely re-run and has undergone a several other updates:
    * if benchmark data is not present, it generates automatically upon notebook run using a new utulity functions, which allows for easier benchmarking;
    * number of itertations (actions repeats used to calcalate statistics) was reduced to make overall runtime tolerable;
    * long-running benchmarks are tested against smaller set of bacth sizes;
* `scale_minmax` and `scale_maxabs` targets were modified according to the new benchmark results.

2022-04-22 08:43 UTC, alexanderkuvaev requested changes

2022-04-22 08:43 UTC, alexanderkuvaev commented on seismicpro/src/gather/utils/general_utils.py
> +    sdc_coefficient /= sdc_coefficient[-1]
Probably it will be faster if written as a single c-style loop, here several unnecessary allocations are performed

2022-04-22 08:43 UTC, alexanderkuvaev commented on seismicpro/src/gather/utils/general_utils.py
> +    for i in prange(n_traces):  # pylint: disable=not-an-iterable
```suggestion
    for i in prange(len(data)):  # pylint: disable=not-an-iterable
```
As well as in another func

2022-04-22 08:43 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +            raise ValueError("Only VelocityCube or StackingVelocity instances can be passed as a stacking_velocity")
You don't handle cube case here. And I actually would not. Same in other func

2022-04-22 08:43 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +        window_size_samples = window_size // int(self.sample_rate)
```suggestion
        window_size_samples = int(window_size / self.sample_rate)
```
Current version may return wrong size in case of float sample rate

2022-04-22 08:43 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +            raise ValueError(f'window should be at least {3*self.sample_rate} and'
```suggestion
            raise ValueError(f'window should be at least {3*self.sample_rate} milliseconds and'
```

2022-04-22 08:43 UTC, alexanderkuvaev commented on seismicpro/benchmark/utils.py
> +def make_benchmark_data(path):
Is this generation slow compared to the whole benchmark run? If not, I'd combine both functions into a single one and generate the seg y file in a temp dir. This will make code much clearer

2022-04-22 08:43 UTC, alexanderkuvaev commented on seismicpro/src/const.py
> +DEFAULT_STACKING_VELOCITY  = StackingVelocity.from_points(times=DEFAULT_TIMES, velocities=DEFAULT_VELOCITIES)
Let's move list definition into the stacking velocity itself. They are meaningless without it and I don't want them to be exposed in the outer scope. Also add a comment, describing this velocity

2022-04-22 08:43 UTC, alexanderkuvaev commented on seismicpro/src/gather/utils/general_utils.py
> +@njit(parallel=True)
Let's move these functions into a separate `gain.py`

2022-04-22 08:43 UTC, alexanderkuvaev commented on seismicpro/src/gather/utils/general_utils.py
> +        coefs = np.sqrt(coefs) * factor if mode=='rms' else coefs * factor
Do we really need factor?

2022-04-22 09:44 UTC, dpodvyaznikov commented on seismicpro/benchmark/utils.py
> +def make_benchmark_data(path):
Good idea to make a temp dir to store data and dumps.
Data generation takes 4 mins, which is ~ 3% of the whole run; if we combine generation and loading, it makes sense to remove that dir in the end of the notebook.

2022-04-25 08:19 UTC, dpodvyaznikov commented on seismicpro/src/gather/utils/general_utils.py
> +    for i in prange(n_traces):  # pylint: disable=not-an-iterable
Done

2022-04-25 08:21 UTC, dpodvyaznikov commented on seismicpro/src/gather/utils/general_utils.py
> +    sdc_coefficient /= sdc_coefficient[-1]
Speed-up is neglegible, let's keep this way for readability

2022-04-25 08:22 UTC, dpodvyaznikov commented on seismicpro/src/gather/utils/general_utils.py
> +        coefs = np.sqrt(coefs) * factor if mode=='rms' else coefs * factor
Agreed, removing it

2022-04-25 08:22 UTC, dpodvyaznikov commented on seismicpro/src/gather/utils/general_utils.py
> +@njit(parallel=True)
Done

2022-04-25 08:22 UTC, dpodvyaznikov commented on seismicpro/src/gather/gather.py
> +            raise ValueError("Only VelocityCube or StackingVelocity instances can be passed as a stacking_velocity")
Done

2022-04-25 10:22 UTC, alexanderkuvaev requested changes

2022-04-25 10:22 UTC, alexanderkuvaev commented on seismicpro/src/gather/utils/gain.py
> +    return data
```suggestion
@njit(nogil=True)
def process_amp(amp, mode):
    non_zero = 1 if amp != 0 else 0
    amp = amp**2 if mode=='rms' else abs(amp)
    return amp, non_zero


@njit(nogil=True, parallel=True)
def apply_agc(data, window_size=125, mode='abs'):
    """ TODO """
    n_traces, trace_len = data.shape
    win_left, win_right = window_size // 2, window_size - window_size // 2
    # start is the first trace index that fits the full window, end is the last.
    # AGC coefficients before start and after end are extrapolated.
    start, end = win_left, trace_len - win_right

    for i in prange(n_traces):  # pylint: disable=not-an-iterable
        trace = data[i]
        coefs = np.empty_like(trace)

        # Calculate AGC scaling factor for the first window
        win_sum = 0
        win_count = 0
        for j in range(window_size):
            amp, non_zero = process_amp(trace[j], mode)
            win_count += non_zero
            win_sum += amp
        coefs[start] = win_count / (win_sum + 1e-6)
        if mode=='rms':
            coefs[start] = np.sqrt(coefs[start])

        # Move the window by one trace element and recalculate the AGC factor
        for j in range(start + 1, end):
            amp, non_zero = process_amp(trace[j + win_right], mode)
            win_count += non_zero
            win_sum += amp

            amp, non_zero = process_amp(trace[j - win_left], mode)
            win_count -= non_zero
            win_sum -= amp

            coefs[j] = win_count / (win_sum + 1e-6)
            if mode=='rms':
                coefs[start] = np.sqrt(coefs[start])

        # Extrapolate AGC coefs for trace indices that don't fit the full window
        coefs[:start] = coefs[start]
        coefs[end:] = coefs[end-1]

        data[i] *= coefs
    return data
```

This code:
1. runs ~2 times faster
2. avoids overflows in cumsums
3. Does not produce `nan`s in my tests (actually does not know why does yours produce)
4. looks scarry a bit :(

Also, you've benchmarked your code with `threads` target but without `nogil` flag which skews results. And please, consider avoidind direct comparison with 0 for float variables.

2022-04-25 13:49 UTC, dpodvyaznikov commented on seismicpro/src/gather/gather.py
> +    def apply_sdc(self, t_pow=1, v_pow=2, velocity=None):
Done

2022-04-25 20:31 UTC, dpodvyaznikov commented on seismicpro/benchmark/utils.py
> +def make_benchmark_data(path):
Done

2022-04-25 20:38 UTC, dpodvyaznikov commented on seismicpro/src/gather/utils/gain.py
> +    return data
Done

2022-04-28 08:24 UTC, alexanderkuvaev requested changes

2022-04-28 08:24 UTC, alexanderkuvaev commented on seismicpro/benchmark/utils.py
> +    survey = (sur.filter(lambda x: (x>cl_min+3) & (x<=cl_max-3), 'CROSSLINE_3D')
Fix all filters as I suggested

2022-04-28 08:24 UTC, alexanderkuvaev commented on seismicpro/benchmark/utils.py
> +    """ Generate a SEGY file with specific geometry and filter it to obtain survey objects for benchmark. """
```suggestion
    """ Generate a SEG-Y file with specific geometry so that CDP gathers contain the same number of traces and construct survey objects for benchmark. """
```

2022-04-28 08:24 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +        """Calculate instantaneous of RMS amplitude AGC coefficients and apply them to gather data.
```suggestion
        """Calculate instantaneous or RMS amplitude AGC coefficients and apply them to gather data.
```

2022-04-28 08:24 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +            Window size to calculate AGC scaling coefficient in, measured in samples. Defaults to 125.
Its 250 and in milliseconds

2022-04-28 08:24 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +        window_size : int
```suggestion
        window_size : int, optional, defaults to 250
```
Similar in other cases

2022-04-28 08:24 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +            is used as scaling coefficient(RMS amplitude AGC), if 'abs' - mean of absolute non-zero
```suggestion
            is used as scaling coefficient (RMS amplitude AGC), if 'abs' - mean of absolute non-zero
```

2022-04-28 08:24 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +        if (window_size_samples < 3) or (window_size_samples >= self.n_samples):
Won't `n_samples` window work?

2022-04-28 08:24 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +        SDC coefficients are a function of time and velocity, so self.times are used as time values.
Is this note necessary?

2022-04-28 08:24 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +        velocities: 1d np.ndarray
Copy from `apply_sdc`

2022-04-28 08:24 UTC, alexanderkuvaev commented on seismicpro/src/gather/utils/gain.py
> +    """Calculate instantaneous of RMS amplitude AGC coefficients and apply them to gather data.
```suggestion
    """Calculate instantaneous or RMS amplitude AGC coefficients and apply them to gather data.
```

2022-04-28 08:24 UTC, alexanderkuvaev commented on seismicpro/src/gather/utils/gain.py
> +        coefficient(RMS amplitude AGC), if 'abs' - mean of absolute non-zero amplitudes (instantaneous AGC).
```suggestion
        coefficient (RMS amplitude AGC), if 'abs' - mean of absolute non-zero amplitudes (instantaneous AGC).
```

2022-04-28 11:42 UTC, nikita-klsh commented
Please rename stack benchmark from `apply_nmo_bm` to `stack_bm`

2022-04-28 12:51 UTC, alexanderkuvaev requested changes

2022-04-28 12:51 UTC, alexanderkuvaev commented on seismicpro/src/gather/gather.py
> +                             f' {(self.n_samples-1)*self.sample_rate} at most, but {window_size} was given')
```suggestion
                             f' {self.n_samples * self.sample_rate} at most, but {window_size} was given')
```

2022-04-28 13:29 UTC, dpodvyaznikov commented on seismicpro/src/gather/gather.py
> +        window_size_samples = int(window_size / self.sample_rate)
```suggestion
        window_size_samples = int(window_size // self.sample_rate) + 1
```

2022-04-28 13:29 UTC, dpodvyaznikov commented on seismicpro/src/gather/gather.py
> +                             f' {(self.n_samples-1)*self.sample_rate} at most, but {window_size} was given')
```suggestion
                             f' {self.n_samples*self.sample_rate - 1} at most, but {window_size} was given')
```

2022-04-28 13:41 UTC, alexanderkuvaev approved these changes

2022-04-28 13:41 UTC, merged